[package]
name = "thermite"
version = "0.1.0"
edition = "2024"
categories = ["no_std"]

[features]
default = ["document_registers"]

# Disable Fast FMA emulation to ensure correctness, instead using scalar libm fma,
# which is very, very slow. Only set this feature if you need bitwise identical results with
# scalar fma implementations. The emulated Fast FMA will be accurate, but not bitwise identical,
# using compensated arithmetic.
disable_fast_fma = []

# Disable all static dispatch on the SIMD ISA, instead opting for an #[inline(always)] signatures.
# This will bloat code, and if you do not guarantee that the function will be inlined, it will be very slow.
# Only enable this feature if you know what you're doing.
disable_dispatch = []

std = ["num-traits/std"] # required for decent scalar support
partial-ord = []         # Implements PartialOrd for Vector, only if all lanes are that order
document_registers = []
neon = []

# Uses wasm32 or wasm64 backend, where wasm64 is only available on nightly (with "nightly" feature)
wasm = []

avx512-tier1 = []               # Oldest AVX512 CPUs
avx512-tier2 = ["avx512-tier1"] # Common AVX512 CPUs
avx512-tier3 = ["avx512-tier2"] # Modern AVX512 CPUs
avx512-tier4 = ["avx512-tier3"] # Cutting-edge AVX512 CPUs

# Nightly features
nightly = []
std_simd = ["nightly", "std"]


[dependencies]
thermite-macros = { path = "../thermite-macros" }
thermite-dispatch = { path = "../dispatch" }
fast_polynomial = { version = "0.4", default-features = false }
generic-array = { git = "https://github.com/fizyk20/generic-array", features = ["bitvec"] }
bitvec = { version = "1.0.1", default-features = false }
const-default = { version = "1.0.0", default-features = false }
libm = "0.2.13"
paste = "1.0.15"
num-traits = { version = "0.2.19", default-features = false }
rustversion = "1"
rand = { version = "0.9", optional = true, default-features = false }

[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))'.dependencies]
core_detect = "1"

[dev-dependencies]
glam = "0.30.3"
num-traits = { version = "0.2.19", default-features = true }

[package.metadata.docs.rs]
features = ["const-default", "document_registers", "std"]
rustdoc-args = ["--cfg", "docsrs"]
