[package]
name = "thermite"
version = "0.1.0"
edition = "2024"
categories = ["no_std"]

[features]
default = ["document_registers"]
nightly = []
std = ["num-traits/std"]         # required for decent scalar support
partial-ord = []                 # Implements PartialOrd for Vector, only if all lanes are that order
float-trait = ["partial-ord"]    # Implements the Float/FloatCore traits as best as possible
document_registers = []
neon = []
wasm32 = []

[dependencies]
fast_polynomial = { version = "0.4", default-features = false }
generic-array = "1.2.0"
libm = "0.2.13"
paste = "1.0.15"
num-traits = { version = "0.2.19", default-features = false }
rustversion = "1"

const-default = { version = "1.0.0", optional = true, default-features = false }

[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))'.dependencies]
core_detect = "1"

[dev-dependencies]
glam = "0.30.3"
num-traits = { version = "0.2.19", default-features = true }

[package.metadata.docs.rs]
features = ["const-default", "document_registers", "std"]
rustdoc-args = ["--cfg", "docsrs"]
