//! Block sort: `N` vectors into one row-major sorted run, the cheap way.
//!
//! This is the other half of [`crate::columns`]. A columnar network sorts the
//! lane columns of `[V; N]` independently and pays nothing but `min`/`max`; it
//! leaves the block *column*-sorted, which is not sorted. What follows is the
//! merge that turns `LANES` sorted columns into one sorted run of `N * LANES`,
//! read row-major (`v0`'s lanes, then `v1`'s, ...).
//!
//! # Why not the bitonic tree
//!
//! The obvious construction - sort each vector's lanes, then merge the vectors
//! pairwise - sits at the *bitonic* floor, wasting no comparator: 736
//! `min`/`max` for 16 vectors of 8 lanes. The bitonic floor is not the
//! achievable floor, though. This decomposition is not bitonic and lands at
//! 504, with well under half the shuffles and a third of the blends:
//!
//! | 16 vectors x 8 lanes | `min`/`max` | shuffles | blends |
//! |---|---|---|---|
//! | bitonic merge tree | 736 | 288 | 288 |
//! | this | 504 | 192 | 96 |
//!
//! The difference is where the work lands. A bitonic tree of `N` vectors runs
//! a full `LANES`-lane network *inside* every vector at every level, and an
//! in-vector layer costs a permute, a `min`, a `max` and a blend to service
//! `LANES/2` comparators. The columnar network up front sorts 16 inputs in 60
//! comparators with no shuffles at all, and the merge that follows touches
//! lanes only in `log2` many passes at the end of each stage. Comparators
//! migrate from the expensive axis to the free one.
//!
//! # The construction
//!
//! The hybrid bitonic/odd-even merge used by vqsort
//! (`hwy/contrib/sort/sorting_networks-inl.h`, Apache-2.0). `merge_N_cC`
//! merges adjacent `C/2`-wide column groups into `C`-wide ones, so running
//! `c2`, `c4`, `c8`, ... up to `LANES` widens a column-sorted block into a
//! fully sorted one.
//!
//! Each `merge_N_cC` is `log2(N)` row stages followed by one per-row tail:
//!
//! - A **row stage** reverses the lanes of the upper row of every pair within
//!   groups of `C`, then compare-exchanges the pair as whole vectors. Only the
//!   reversal costs a shuffle; the compare-exchange is columnar.
//! - The **tail** ([`tail_2`] and friends) finishes each row on its own with
//!   `SortPairsReverse` at `C` followed by `SortPairsDistance` at `C/4`, `C/8`,
//!   ... `1` - the odd-even half of the hybrid.
//!
//! Both are the same primitive, [`pair`]: permute each lane to face its partner,
//! take the pair's first and last under `O`, then blend so the lower index of
//! every pair keeps the first. Identical in shape to `cmp_merge` in core's
//! `backend::generic::polyfills::sort`, which cannot be reused here because it
//! is a register-layer function and [`NumericVector`] exposes no register type.
//!
//! # Lane-count range
//!
//! Valid for `LANES <= 16`, which is what the widest merge here (`c16`) covers.
//! At `LANES == 1` the columnar network alone is already the answer and every
//! merge is skipped. Wider registers need a `c32` stage; until one exists,
//! [`crate::base`] keeps them on the bitonic tree.

use core::marker::PhantomData;

use thermite::generic_array::{ArrayLength, GenericArray};
use thermite::mask::GenericMask;
use thermite::sort::SortOrder;
use thermite::swizzle::SwizzleIndices;
use thermite::vector::{NumericVector, SwizzleVector};

use crate::columns::{sort_columns_2_by, sort_columns_4_by, sort_columns_8_by, sort_columns_16_by};

/// Widest column group the merges here cover, in lanes.
pub const MAX_LANES: usize = 16;

/// A vector this network runs on: numeric, plus compile-time lane permutes.
///
/// The permutes ([`SwizzleVector`]) are what the merge stages need beyond
/// [`NumericVector`]; every `Vector<R>` is both, so this is only a shorthand -
/// `V: NumericVector + SwizzleVector` is the same bound spelled out.
pub trait MergeVector: NumericVector + SwizzleVector {}
impl<V: NumericVector + SwizzleVector> MergeVector for V {}

// ---------------------------------------------------------------------------
// Lane index sets
//
// Both are generated by a `const fn` over the lane count rather than typed out,
// so one definition covers every width. `GenericArray<u32, N>` has no const
// literal constructor for a generic `N`, hence the zero-init-then-fill through
// a raw pointer - the same shape as `thermite`'s `AlignIndices`.
// ---------------------------------------------------------------------------

/// Lane `i` faces lane `i ^ K`: the partner set of a distance-`K`
/// compare-exchange.
struct XorIdx<const K: usize, N>(PhantomData<N>);

impl<const K: usize, N: ArrayLength> SwizzleIndices<N> for XorIdx<K, N> {
    const INDICES: GenericArray<u32, N> = const {
        let mut idxs: GenericArray<u32, N> = unsafe { core::mem::zeroed() };
        let ptr = &mut idxs as *mut GenericArray<u32, N> as *mut u32;

        // A stage wider than the register is dead code the caller's `if const`
        // ladder never reaches, but its indices are still const-evaluated and
        // must stay in range - out-of-range swizzle indices are UB by contract.
        let k = if K < N::USIZE { K } else { 0 };

        let mut i = 0;
        while i < N::USIZE {
            unsafe { *ptr.add(i) = (i ^ k) as u32 };
            i += 1;
        }
        idxs
    };
}

/// Lane `i` faces its mirror within its contiguous group of `K` lanes.
struct RevIdx<const K: usize, N>(PhantomData<N>);

impl<const K: usize, N: ArrayLength> SwizzleIndices<N> for RevIdx<K, N> {
    const INDICES: GenericArray<u32, N> = const {
        let mut idxs: GenericArray<u32, N> = unsafe { core::mem::zeroed() };
        let ptr = &mut idxs as *mut GenericArray<u32, N> as *mut u32;

        // As above: clamp rather than emit an out-of-range index.
        let k = if K < N::USIZE { K } else { N::USIZE };

        let mut i = 0;
        while i < N::USIZE {
            unsafe { *ptr.add(i) = ((i & !(k - 1)) | (k - 1 - (i & (k - 1)))) as u32 };
            i += 1;
        }
        idxs
    };
}

/// Lanes whose index has `bit` set - the lanes that receive the *last* of their
/// pair. `bit == 0` means no lane does.
const fn keep_bits(bit: usize) -> u64 {
    let mut mask = 0u64;
    if bit == 0 {
        return mask;
    }
    let mut i = 0;
    while i < 64 {
        if i & bit != 0 {
            mask |= 1 << i;
        }
        i += 1;
    }
    mask
}

/// One in-vector compare-exchange layer: a partner permutation plus the lane
/// mask saying which side of each pair keeps the larger element.
trait PairStage<N: ArrayLength> {
    /// Where each lane finds its partner.
    type Indices: SwizzleIndices<N>;
    /// Bit `i` set means lane `i` receives `O::vector_last` of its pair.
    const KEEP_LAST: u64;
}

/// Compare-exchange lane `i` with lane `i ^ K` (vqsort's
/// `SortPairsDistance{K}`). The high lane of each pair keeps the last.
struct Distance<const K: usize>;

impl<const K: usize, N: ArrayLength> PairStage<N> for Distance<K> {
    type Indices = XorIdx<K, N>;
    const KEEP_LAST: u64 = keep_bits(K);
}

/// Compare-exchange each lane with its mirror in its group of `K` (vqsort's
/// `SortPairsReverse{K}`). The upper *half* of each group keeps the last, so the
/// mask is the distance-`K/2` one.
struct RevPairs<const K: usize>;

impl<const K: usize, N: ArrayLength> PairStage<N> for RevPairs<K> {
    type Indices = RevIdx<K, N>;
    const KEEP_LAST: u64 = keep_bits(K / 2);
}

/// Run one in-vector compare-exchange layer.
///
/// Permute, take both sides of every pair, blend by a constant lane mask. The
/// order is free: [`Ascending`](thermite::sort::Ascending) resolves
/// `vector_first`/`vector_last` to `min`/`max` and
/// [`Descending`](thermite::sort::Descending) the other way, so the same
/// permute + `min` + `max` + blend is emitted either direction with only the
/// blend operands swapped.
#[inline(always)]
fn pair<V: MergeVector, O: SortOrder, S: PairStage<V::Lanes>>(v: V) -> V {
    let partner = v.permute_const::<S::Indices>();
    let first = O::vector_first(v, partner);
    let last = O::vector_last(v, partner);

    // A constant bitmask, so this folds to a materialized mask constant.
    let keep_last = <V::Mask as GenericMask>::from_native_bitmask(S::KEEP_LAST);

    keep_last.select(last, first)
}

/// Reverse the lanes of each contiguous group of `K`.
#[inline(always)]
fn rev_group<V: MergeVector, const K: usize>(v: V) -> V {
    v.permute_const::<RevIdx<K, V::Lanes>>()
}

// ---------------------------------------------------------------------------
// Per-row tails
//
// `tail_C` finishes one row of a `C`-wide merge on its own: the odd-even half
// of the hybrid. `SortPairsReverse` at `C`, then halving distances from `C/4`.
// (`tail_2` is only the reverse, because reversing a group of 2 *is* the
// distance-1 stage.)
// ---------------------------------------------------------------------------

macro_rules! tail_fn {
    ($(#[$attr:meta])* $name:ident, $c:literal, [$($d:literal),*]) => {
        $(#[$attr])*
        #[inline(always)]
        fn $name<V: MergeVector, O: SortOrder>(v: V) -> V {
            let v = pair::<V, O, RevPairs<$c>>(v);
            $( let v = pair::<V, O, Distance<$d>>(v); )*
            v
        }
    };
}

tail_fn!(
    /// Finish a row of a 2-wide merge. 1 layer.
    tail_2, 2, []
);
tail_fn!(
    /// Finish a row of a 4-wide merge. 2 layers.
    tail_4, 4, [1]
);
tail_fn!(
    /// Finish a row of an 8-wide merge. 3 layers.
    tail_8, 8, [2, 1]
);
tail_fn!(
    /// Finish a row of a 16-wide merge. 4 layers.
    tail_16, 16, [4, 2, 1]
);

// ---------------------------------------------------------------------------
// Row stages
//
// `merge_{rows}_c{C}` widens a block of `rows` vectors from `C/2`-wide sorted
// column groups to `C`-wide ones. The stage lists are the bitonic row pairings
// - mirror pairs within halving group sizes - and the upper row of every pair
// is lane-reversed within its group of `C` first. That reversal is the only
// shuffle in a stage; the compare-exchange itself is columnar.
// ---------------------------------------------------------------------------

macro_rules! merge_fn {
    (
        $name:ident, $rows:literal, $c:literal, $tail:ident,
        [ $( [ $( ($lo:tt, $hi:tt) )+ ] )+ ],
        [ $($row:tt)+ ]
    ) => {
        #[doc = concat!(
            "Widen ", stringify!($rows), " vectors from ", stringify!($c),
            "/2-wide to ", stringify!($c), "-wide sorted column groups."
        )]
        #[inline(always)]
        fn $name<V: MergeVector, O: SortOrder>(c: &mut [V; $rows]) {
            $(
                $( c[$hi] = rev_group::<V, $c>(c[$hi]); )+
                $(
                    {
                        let (a, b) = (c[$lo], c[$hi]);
                        c[$lo] = O::vector_first(a, b);
                        c[$hi] = O::vector_last(a, b);
                    }
                )+
            )+

            $( c[$row] = $tail::<V, O>(c[$row]); )+
        }
    };
}

/// Emit the four column widths for one row count from a single stage list.
macro_rules! merge_group {
    (
        $rows:literal, [ $($row:tt)+ ], $f2:ident, $f4:ident, $f8:ident, $f16:ident,
        $($stage:tt)+
    ) => {
        merge_fn!($f2,  $rows, 2,  tail_2,  [$($stage)+], [$($row)+]);
        merge_fn!($f4,  $rows, 4,  tail_4,  [$($stage)+], [$($row)+]);
        merge_fn!($f8,  $rows, 8,  tail_8,  [$($stage)+], [$($row)+]);
        merge_fn!($f16, $rows, 16, tail_16, [$($stage)+], [$($row)+]);
    };
}

merge_group! {
    2, [0 1], merge_2_c2, merge_2_c4, merge_2_c8, merge_2_c16,
    [(0,1)]
}

merge_group! {
    4, [0 1 2 3], merge_4_c2, merge_4_c4, merge_4_c8, merge_4_c16,
    [(0,3)(1,2)]
    [(0,1)(2,3)]
}

merge_group! {
    8, [0 1 2 3 4 5 6 7], merge_8_c2, merge_8_c4, merge_8_c8, merge_8_c16,
    [(0,7)(1,6)(2,5)(3,4)]
    [(0,3)(1,2)(4,7)(5,6)]
    [(0,1)(2,3)(4,5)(6,7)]
}

merge_group! {
    16, [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15],
    merge_16_c2, merge_16_c4, merge_16_c8, merge_16_c16,
    [(0,15)(1,14)(2,13)(3,12)(4,11)(5,10)(6,9)(7,8)]
    [(0,7)(1,6)(2,5)(3,4)(8,15)(9,14)(10,13)(11,12)]
    [(0,3)(1,2)(4,7)(5,6)(8,11)(9,10)(12,15)(13,14)]
    [(0,1)(2,3)(4,5)(6,7)(8,9)(10,11)(12,13)(14,15)]
}

// ---------------------------------------------------------------------------
// Block sorts
// ---------------------------------------------------------------------------

/// Column-sort, then widen the column groups until they span the register.
///
/// The ladder is on an associated const, so every arm that a given `V` cannot
/// reach folds away at monomorphization.
macro_rules! sort_block_fn {
    (
        $(#[$attr:meta])* $name:ident, $rows:literal, $cols:ident,
        $f2:ident, $f4:ident, $f8:ident, $f16:ident
    ) => {
        $(#[$attr])*
        ///
        /// Requires `V::LANES <= 16`; see the module docs.
        #[inline(always)]
        pub fn $name<V: MergeVector, O: SortOrder>(c: [V; $rows]) -> [V; $rows] {
            debug_assert!(V::LANES <= MAX_LANES, "no merge stage wider than {MAX_LANES} lanes");

            let mut c = $cols::<V, O>(c);

            if const { V::LANES >= 2 } {
                $f2::<V, O>(&mut c);

                if const { V::LANES >= 4 } {
                    $f4::<V, O>(&mut c);

                    if const { V::LANES >= 8 } {
                        $f8::<V, O>(&mut c);

                        if const { V::LANES >= 16 } {
                            $f16::<V, O>(&mut c);
                        }
                    }
                }
            }

            c
        }
    };
}

sort_block_fn!(
    /// Sort `2 * LANES` keys held in 2 vectors into one row-major run.
    sort_block_2, 2, sort_columns_2_by, merge_2_c2, merge_2_c4, merge_2_c8, merge_2_c16
);
sort_block_fn!(
    /// Sort `4 * LANES` keys held in 4 vectors into one row-major run.
    sort_block_4, 4, sort_columns_4_by, merge_4_c2, merge_4_c4, merge_4_c8, merge_4_c16
);
sort_block_fn!(
    /// Sort `8 * LANES` keys held in 8 vectors into one row-major run.
    sort_block_8, 8, sort_columns_8_by, merge_8_c2, merge_8_c4, merge_8_c8, merge_8_c16
);
sort_block_fn!(
    /// Sort `16 * LANES` keys held in 16 vectors into one row-major run.
    ///
    /// 16 live vectors is the whole ymm register file on AVX2, so this spills.
    /// The spills are close to free: they ride load/store units that have
    /// slack, while the comparators saturate the FP pipes.
    sort_block_16, 16, sort_columns_16_by, merge_16_c2, merge_16_c4, merge_16_c8, merge_16_c16
);
