// @generated by gen_consts.py at the workspace root. DO NOT EDIT BY HAND.
//! Enclosure constants: exact `(RD(c), RU(c))` pairs for every [`FloatConsts`]
//! name, meaning the two consecutive floats bracketing the true mathematical
//! value, so that pi _as an interval_ actually contains pi, one ulp wide, and an
//! exactly representable constant (`EPSILON`, `FRAC_1_4`, ...) is degenerate.
//!
//! The pairs live in `consts_table.rs`. Both that file and this one come from
//! `gen_consts.py` at the workspace root, which computes each constant from its
//! mathematical definition with mpmath at 80 digits and brackets it by exact
//! rational comparison, with no float rounding and no "step one ulp and hope"
//! anywhere. The `bounded_consts!` machinery is hand-written in `macros.rs`.
//!
//! Structure mirrors thermite-compensated's `SplitFloatConsts`: element impls
//! (`f32`/`f64`) from the table, lifted to `Vector<R>` through one
//! splat-carrier pair per constant name.

#[macro_use]
mod macros;

use core::marker::PhantomData;

use thermite::prelude::*;
use thermite::register::FloatRegister;
use thermite::vector::{SplatConst, const_splat};

thermite::for_each_float_const!(bounded_consts);
