[workspace]
members = ["crates/*"]
resolver = "3"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
codegen-units = 1
lto = true

[profile.bench]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = false

[profile.release-ffi]
inherits = "release"
opt-level = 3
codegen-units = 1
lto = "fat"
debug = false
strip = true
panic = "abort"
