use thermite::math::{
    MathWithPolicy,
    policy::{
        PrecisionPolicy,
        policies::{AveragePrecision, ExtraPrecision, MediumPrecision},
    },
};

use super::*;

impl<R> SpecialMathInternal<f32> for R
where
    R: FloatRegister<Element = f32>,
{
    #[inline(always)]
    fn tgamma<P: Policy>(x: Vf<Self>) -> Vf<Self> {
        let is_negative = x.is_negative();

        if P::POLICY.avoid_branching || is_negative.any() {
            // TODO: Negatives

            let x = x.abs();
        }

        // TODO: Full Lanczos approximation for tgamma for higher precision policies
        medium_lgamma0::<Self, P>(x).exp_p::<P>()
    }
}

/**
 * "An accurate approximation formula for gamma function"
 * https://journalofinequalitiesandapplications.springeropen.com/articles/10.1186/s13660-018-1646-6
 *
 * This has been reformulated as lgamma, to avoid multiple calls to exp and ln,
 * and to use a Padé approximation for the logarithm of the exponential function
 * generated by expanding sinh.
 */
#[inline(always)]
fn medium_lgamma0<R: FloatRegister<Element = f32>, P: Policy>(x: Vf<R>) -> Vf<R> {
    // probably the most expensive call here, and most important for accuracy,
    // so we give it extra precision policy
    let lnx = x.ln_p::<ExtraPrecision<P>>();

    // 1/2 + ln(pi)/2, constant parts added together
    const C: f32 = 1.072364942924700087071713675676529355823647406457655785756811535736068884942413;

    // (3x+1)/2 * ln(x) - x
    let a = x.mul_adde(Vf::splat(1.5), Vf::HALF).mul_sube(lnx, x);

    // (1-x)/2 * ln(2) + (1/2 * ln(pi)/2)
    let b = x.nmul_adde(Vf::HALF, Vf::HALF).mul_adde(Vf::LN_2, Vf::splat(C));

    // x/2 * ln(1 - e^(-2/x)) - ln(x)
    let c = {
        // 2/x
        let xr2 = if const { !R::HAS_APPROX_RCP || P::POLICY.precision.gt(PrecisionPolicy::Average) } {
            Vf::TWO / x
        } else {
            let mut y = x.rcp(); // approximate reciprocal

            if const { P::POLICY.precision.le(PrecisionPolicy::Worst) } {
                // one iteration of Newton's method adjusted to produce 2/x,
                // at the cost of linear convergence
                y * x.nmul_adde(y, Vf::splat(3.0))
            } else {
                // regular Newton's method with quadratic convergence
                y = y * x.nmul_adde(y, Vf::splat(2.0));

                y + y // 2/x via addition
            }
        };

        // ln(1 - e^(-x))/2 Padé approximations
        let hln1m_en2x = if const { P::POLICY.precision.le(PrecisionPolicy::Worst) } {
            // PadeApproximate[2/4] generated around 0.5 by WolframAlpha
            xr2.poly_p::<P, 3>(&[-0.50923904, -3.5926868, 0.65650414])
                / xr2.poly_p::<P, 5>(&[0.232837568, 4.2072807, 7.9589356, 1.62386099, 1.0])
        } else {
            // PadeApproximate[4/8] around 0.5
            xr2.poly_p::<P, 5>(&[-0.2552735, -10.662572, -74.56021, -101.24353, 15.36103])
                / xr2.poly_p::<P, 9>(&[
                    0.09122715, 6.549227, 80.03404, 268.0743, 269.3426, 90.85682, 28.00484, 3.244918, 1.0,
                ])
        };

        // NOTE: Both Padé approximations go above zero near x=0.2, but since the original function approaches
        // zero (from below) anyway, clamping it to zero actually improves the accuracy near zero.
        hln1m_en2x.min(Vf::ZERO).mul_sube(x, lnx) // do -lnx here as well, since it should be computed by now
    };

    // 7/324 * 1/(x^3(35x^2 + 33)) + b
    let d = {
        let c0 = Vf::splat(7.0 / 324.0);
        let c1 = Vf::splat(35.0);
        let c2 = Vf::splat(33.0);

        let x2 = x * x;
        let d0 = x2.mul_adde(c1, c2) * (x * x2);

        // since d is relatively cheap to compute on its own, throw b in as well
        d0.reciprocal_p::<P>().mul_adde(c0, b)
    };

    a + c + d
}

const LANCZOS_G: f32 = 1.428456135094165802001953125;

const LANCZOS_P: &[f32] = &[
    58.52061591769095910314047740215847630266,
    182.5248962595894264831189414768236280862,
    211.0971093028510041839168287718170827259,
    112.2526547883668146736465390902227161763,
    27.5192015197455403062503721613097825345,
    2.50662858515256974113978724717473206342,
];

const LANCZOS_Q: &[f32] = &[0.0, 24.0, 50.0, 35.0, 10.0, 1.0];

const LANCZOS_P_EXPG_SCALED: &[f32] = &[
    14.0261432874996476619570577285003839357,
    43.74732405540314316089531289293124360129,
    50.59547402616588964511581430025589038612,
    26.90456680562548195593733429204228910299,
    6.595765571169314946316366571954421695196,
    0.6007854010515290065101128585795542383721,
];
