[package]
name = "thermite-complex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "Generic SIMD complex numbers built on Thermite"
publish = false                                                # not ready for release yet

[dependencies]
thermite = { workspace = true }
