[package]
name = "thermite-ffi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"] # Both dynamic and static

[dependencies]
paste = "1"
thermite = { path = "../thermite", default-features = false }
thermite-special = { path = "../thermite-special", default-features = false }
libc = { version = "0.2", default-features = false }

[build-dependencies]
cbindgen = "0.29"
