[package]
name = "thermite-ffi"
version = "0.1.0"
edition = "2024"
publish = false # C ABI cdylib build artifact, not a Rust dependency for crates.io

[lib]
name = "thermite"
crate-type = ["cdylib"]
doc = false

[features]
default = ["high_performance", "high_precision"] # Enable all policies by default

high_performance = [] # Enable high-performance policy
high_precision = []   # Enable high-precision policy

# Disable dispatch in thermite for maximum performance, but massive code bloat
disable_dispatch = ["thermite/disable_dispatch", "thermite-special/disable_dispatch"]

# Make no attempts to handle denormal values in Thermite. This assumes
# that either the hardware can reasonably handle denormal values or
# denormals have been disabled (flush to zero, etc.) manually before
# computation.
ignore_denormals = ["thermite/ignore_denormals"]

# Preserve and handle denormals correctly in Thermite, even though they can be very slow to operate on.
# Only enable this if you need to handle denormal values correctly, and are okay with the performance implications.
preserve_denormals = ["thermite/preserve_denormals"]

[dependencies]
paste = "1"
thermite = { workspace = true }
thermite-special = { workspace = true }
libc = { version = "0.2", default-features = false }

[build-dependencies]
cbindgen = "0.29"
