[package]
name = "thermite-compensated"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "Double-double compensated arithmetic built on Thermite"
keywords = ["simd", "double-double", "precision", "float", "no-std"]
categories = ["mathematics", "science", "no-std", "hardware-support"]
publish = false                                                                           # not ready for release yet
readme = "README.md"
include = ["/src", "/README.md", "/katex-header.html", "/LICENSE-APACHE", "/LICENSE-MIT"]

[package.metadata.docs.rs]
features = ["std"]
rustdoc-args = ["--cfg", "docsrs", "--html-in-header", "katex-header.html"]

[features]
default = ["special"]
special = ["dep:thermite-special"]
std = ["thermite/std"]

[dependencies]
thermite = { workspace = true }
# thermite-macros = { workspace = true }
thermite-special = { workspace = true, optional = true }
fast_polynomial = { version = "0.4", default-features = false }
num-traits = { version = "0.2", default-features = false }
hexf = "0.2.1"
paste = "1"

[dev-dependencies]
libm = "0.2"
rand = "0.10"

[lints]
workspace = true
