[package]
name = "thermite-dispatch"
version = "0.1.0"
authors = ["novacrazy <novacrazy@gmail.com>"]
edition = "2024"

[lib]
proc-macro = true

[dependencies]
cfg-if = "1"
quote = "1"
proc-macro2 = "1"
syn = { version = "2", features = ["full", "extra-traits", "visit", "visit-mut"] }

[features]
x86 = []
neon = []
wasm = []
spirv = []
