[package]
name = "thermite-dispatch"
version = "0.1.0"
authors = ["novacrazy <novacrazy@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1"
syn = { version = "1", features = ["full", "extra-traits", "visit-mut"] }

[features]
neon = []
wasm32 = []