[package]
name = "thermite-geometry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "SIMD geometry primitives built on Thermite"
publish = false                                            # not ready for release yet

[dependencies]
thermite = { path = "../thermite", version = "0.2.0-beta.0" }
