// @generated by gen_consts.py at the workspace root. DO NOT EDIT BY HAND.
//! Bernoulli numbers at double-double precision.
//!
//! The `thermite-special` [`BernoulliNumbers`] tables, split into `(value, error)`
//! limbs. Entry `i` is `$B_{2i+2}$`, same as there.
//!
//! The lengths match the underlying format's exactly: a double-double carries twice
//! the mantissa but the SAME exponent range, so `Compensated<f64>` runs out at
//! `$B_{260}$` just as `f64` does. Widening buys precision, not reach.

use thermite_special::tables::bernoulli::BernoulliNumbers;

use crate::Compensated;

impl BernoulliNumbers for Compensated<f32> {
    #[rustfmt::skip]
    const B2N: &'static [Compensated<f32>] = &[
        Compensated { value: hexf::hexf32!("0x1.5555560000000p-3"), error: hexf::hexf32!("-0x1.5555560000000p-28") },  // B_2
        Compensated { value: hexf::hexf32!("-0x1.1111120000000p-5"), error: hexf::hexf32!("0x1.ddddde0000000p-30") },  // B_4
        Compensated { value: hexf::hexf32!("0x1.8618620000000p-6"), error: hexf::hexf32!("-0x1.e79e7a0000000p-32") },  // B_6
        Compensated { value: hexf::hexf32!("-0x1.1111120000000p-5"), error: hexf::hexf32!("0x1.ddddde0000000p-30") },  // B_8
        Compensated { value: hexf::hexf32!("0x1.364d940000000p-4"), error: hexf::hexf32!("-0x1.364d940000000p-29") },  // B_10
        Compensated { value: hexf::hexf32!("-0x1.0330340000000p-2"), error: hexf::hexf32!("0x1.f99f9a0000000p-27") },  // B_12
        Compensated { value: hexf::hexf32!("0x1.2aaaaa0000000p+0"), error: hexf::hexf32!("0x1.5555560000000p-25") },  // B_14
        Compensated { value: hexf::hexf32!("-0x1.c5e5e60000000p+2"), error: hexf::hexf32!("0x1.a1a1a20000000p-26") },  // B_16
        Compensated { value: hexf::hexf32!("0x1.b7c4f80000000p+5"), error: hexf::hexf32!("0x1.e27c780000000p-20") },  // B_18
        Compensated { value: hexf::hexf32!("-0x1.088fe80000000p+9"), error: hexf::hexf32!("0x1.a6031a0000000p-16") },  // B_20
        Compensated { value: hexf::hexf32!("0x1.8301f80000000p+12"), error: hexf::hexf32!("0x1.28cfc40000000p-13") },  // B_22
        Compensated { value: hexf::hexf32!("-0x1.5234400000000p+16"), error: hexf::hexf32!("-0x1.9819820000000p-9") },  // B_24
        Compensated { value: hexf::hexf32!("0x1.5c06d20000000p+20"), error: hexf::hexf32!("0x1.5555560000000p-5") },  // B_26
        Compensated { value: hexf::hexf32!("-0x1.a089b80000000p+24"), error: hexf::hexf32!("0x1.dd47360000000p-1") },  // B_28
        Compensated { value: hexf::hexf32!("0x1.1edb2a0000000p+29"), error: hexf::hexf32!("0x1.3cd2100000000p+3") },  // B_30
        Compensated { value: hexf::hexf32!("-0x1.c280560000000p+33"), error: hexf::hexf32!("-0x1.dc5e5e0000000p+6") },  // B_32
        Compensated { value: hexf::hexf32!("0x1.901c1c0000000p+38"), error: hexf::hexf32!("0x1.bba9560000000p+13") },  // B_34
        Compensated { value: hexf::hexf32!("-0x1.8f0fca0000000p+43"), error: hexf::hexf32!("-0x1.9e38160000000p+18") },  // B_36
        Compensated { value: hexf::hexf32!("0x1.bc22ba0000000p+48"), error: hexf::hexf32!("0x1.9e7a640000000p+22") },  // B_38
        Compensated { value: hexf::hexf32!("-0x1.12388c0000000p+54"), error: hexf::hexf32!("0x1.78c54e0000000p+25") },  // B_40
        Compensated { value: hexf::hexf32!("0x1.75c96c0000000p+59"), error: hexf::hexf32!("-0x1.f974660000000p+32") },  // B_42
        Compensated { value: hexf::hexf32!("-0x1.17e6d00000000p+65"), error: hexf::hexf32!("0x1.5e769a0000000p+40") },  // B_44
        Compensated { value: hexf::hexf32!("0x1.caa23e0000000p+70"), error: hexf::hexf32!("-0x1.9836aa0000000p+44") },  // B_46
        Compensated { value: hexf::hexf32!("-0x1.9982c60000000p+76"), error: hexf::hexf32!("-0x1.c35e520000000p+48") },  // B_48
        Compensated { value: hexf::hexf32!("0x1.8d17b40000000p+82"), error: hexf::hexf32!("-0x1.762d200000000p+57") },  // B_50
        Compensated { value: hexf::hexf32!("-0x1.a0cc460000000p+88"), error: hexf::hexf32!("-0x1.a49a720000000p+63") },  // B_52
        Compensated { value: hexf::hexf32!("0x1.d81f960000000p+94"), error: hexf::hexf32!("-0x1.96c4e40000000p+69") },  // B_54
        Compensated { value: hexf::hexf32!("-0x1.1fc3980000000p+101"), error: hexf::hexf32!("0x1.c3b3200000000p+75") },  // B_56
        Compensated { value: hexf::hexf32!("0x1.7887b20000000p+107"), error: hexf::hexf32!("-0x1.4f52ee0000000p+81") },  // B_58
        Compensated { value: hexf::hexf32!("-0x1.07c6560000000p+114"), error: hexf::hexf32!("0x1.5066fe0000000p+89") },  // B_60
        Compensated { value: hexf::hexf32!("0x1.8ad59e0000000p+120"), error: hexf::hexf32!("-0x1.8b8fba0000000p+95") },  // B_62
        Compensated { value: hexf::hexf32!("-0x1.3b0a440000000p+127"), error: hexf::hexf32!("0x1.08537e0000000p+100") },  // B_64
    ];
}

impl BernoulliNumbers for Compensated<f64> {
    #[rustfmt::skip]
    const B2N: &'static [Compensated<f64>] = &[
        Compensated { value: hexf::hexf64!("0x1.5555555555555p-3"), error: hexf::hexf64!("0x1.5555555555555p-57") },  // B_2
        Compensated { value: hexf::hexf64!("-0x1.1111111111111p-5"), error: hexf::hexf64!("-0x1.1111111111111p-61") },  // B_4
        Compensated { value: hexf::hexf64!("0x1.8618618618618p-6"), error: hexf::hexf64!("0x1.8618618618618p-60") },  // B_6
        Compensated { value: hexf::hexf64!("-0x1.1111111111111p-5"), error: hexf::hexf64!("-0x1.1111111111111p-61") },  // B_8
        Compensated { value: hexf::hexf64!("0x1.364d9364d9365p-4"), error: hexf::hexf64!("-0x1.364d9364d9365p-59") },  // B_10
        Compensated { value: hexf::hexf64!("-0x1.0330330330330p-2"), error: hexf::hexf64!("-0x1.981981981981ap-57") },  // B_12
        Compensated { value: hexf::hexf64!("0x1.2aaaaaaaaaaabp+0"), error: hexf::hexf64!("-0x1.5555555555555p-54") },  // B_14
        Compensated { value: hexf::hexf64!("-0x1.c5e5e5e5e5e5ep+2"), error: hexf::hexf64!("-0x1.7979797979798p-52") },  // B_16
        Compensated { value: hexf::hexf64!("0x1.b7c4f8f13e3c5p+5"), error: hexf::hexf64!("-0x1.c3b070ec1c3b0p-53") },  // B_18
        Compensated { value: hexf::hexf64!("-0x1.088fe72cfe72dp+9"), error: hexf::hexf64!("0x1.8d3018d3018d3p-51") },  // B_20
        Compensated { value: hexf::hexf64!("0x1.8301f89467e25p+12"), error: hexf::hexf64!("0x1.9f89467e251a0p-44") },  // B_22
        Compensated { value: hexf::hexf64!("-0x1.523440cc0cc0dp+16"), error: hexf::hexf64!("0x1.f99f99f99f9a0p-39") },  // B_24
        Compensated { value: hexf::hexf64!("0x1.5c06d2aaaaaabp+20"), error: hexf::hexf64!("-0x1.5555555555555p-34") },  // B_26
        Compensated { value: hexf::hexf64!("-0x1.a089b7115c654p+24"), error: hexf::hexf64!("0x1.ba8e6b1ba8e6bp-30") },  // B_28
        Compensated { value: hexf::hexf64!("0x1.1edb2a4f34840p+29"), error: hexf::hexf64!("-0x1.c996f807265bep-26") },  // B_30
        Compensated { value: hexf::hexf64!("-0x1.c280563b8bcbdp+33"), error: hexf::hexf64!("0x1.0d0d0d0d0d0d1p-21") },  // B_32
        Compensated { value: hexf::hexf64!("0x1.901c1cddd4aabp+38"), error: hexf::hexf64!("-0x1.5555555555555p-16") },  // B_34
        Compensated { value: hexf::hexf64!("-0x1.8f0fcacf1c0aap+43"), error: hexf::hexf64!("-0x1.8473226a98473p-11") },  // B_36
        Compensated { value: hexf::hexf64!("0x1.bc22ba679e993p+48"), error: hexf::hexf64!("-0x1.5555555555555p-6") },  // B_38
        Compensated { value: hexf::hexf64!("-0x1.12388bf439d59p+54"), error: hexf::hexf64!("-0x1.3066530665306p-3") },  // B_40
        Compensated { value: hexf::hexf64!("0x1.75c96bc0d1733p+59"), error: hexf::hexf64!("0x1.b801224dadc90p+5") },  // B_42
        Compensated { value: hexf::hexf64!("-0x1.17e6cf50c4b2cp+65"), error: hexf::hexf64!("-0x1.da89d4f65a871p+9") },  // B_44
        Compensated { value: hexf::hexf64!("0x1.caa23d99f255bp+70"), error: hexf::hexf64!("-0x1.8d0fdac7b7604p+16") },  // B_46
        Compensated { value: hexf::hexf64!("-0x1.9982c61c35e52p+76"), error: hexf::hexf64!("0x1.46fca58127218p+21") },  // B_48
        Compensated { value: hexf::hexf64!("0x1.8d17b344e96f9p+82"), error: hexf::hexf64!("0x1.7f05c5026c9b2p+27") },  // B_50
        Compensated { value: hexf::hexf64!("-0x1.a0cc46d24d38ap+88"), error: hexf::hexf64!("-0x1.7f099a770d5d1p+32") },  // B_52
        Compensated { value: hexf::hexf64!("0x1.d81f95349d8dbp+94"), error: hexf::hexf64!("0x1.ed638e20f5f14p+39") },  // B_54
        Compensated { value: hexf::hexf64!("-0x1.1fc3978f1337dp+101"), error: hexf::hexf64!("0x1.88c6b4ba549ddp+43") },  // B_56
        Compensated { value: hexf::hexf64!("0x1.7887b1ac2b44ap+107"), error: hexf::hexf64!("0x1.bf349dfffbe01p+50") },  // B_58
        Compensated { value: hexf::hexf64!("-0x1.07c65557cc80dp+114"), error: hexf::hexf64!("0x1.090c9cbededecp+60") },  // B_60
        Compensated { value: hexf::hexf64!("0x1.8ad59d3a3822ep+120"), error: hexf::hexf64!("0x1.f31c2675fca1dp+63") },  // B_62
        Compensated { value: hexf::hexf64!("-0x1.3b0a43def5904p+127"), error: hexf::hexf64!("0x1.e3a565dd24964p+72") },  // B_64
        Compensated { value: hexf::hexf64!("0x1.0b74e7cb06eddp+134"), error: hexf::hexf64!("0x1.271a3c74fbcfap+79") },  // B_66
        Compensated { value: hexf::hexf64!("-0x1.e2472911cf671p+140"), error: hexf::hexf64!("0x1.7fcf60d67abf3p+86") },  // B_68
        Compensated { value: hexf::hexf64!("0x1.ccf8ea0670bd7p+147"), error: hexf::hexf64!("0x1.90da353b7d803p+92") },  // B_70
        Compensated { value: hexf::hexf64!("-0x1.d255341e3d7e2p+154"), error: hexf::hexf64!("0x1.addc4dc946b2bp+99") },  // B_72
        Compensated { value: hexf::hexf64!("0x1.f2849cf200430p+161"), error: hexf::hexf64!("-0x1.f0ee567e9eb4ap+107") },  // B_74
        Compensated { value: hexf::hexf64!("-0x1.19295efde4dd3p+169"), error: hexf::hexf64!("0x1.e64eaf2f6ae3dp+113") },  // B_76
        Compensated { value: hexf::hexf64!("0x1.4e2c57caa4986p+176"), error: hexf::hexf64!("-0x1.db75063abb9c4p+122") },  // B_78
        Compensated { value: hexf::hexf64!("-0x1.a1f1e397d4418p+183"), error: hexf::hexf64!("-0x1.4fbb9cf63c8e0p+127") },  // B_80
        Compensated { value: hexf::hexf64!("0x1.12aca530989d2p+191"), error: hexf::hexf64!("-0x1.84bf7ae2d091cp+136") },  // B_82
        Compensated { value: hexf::hexf64!("-0x1.7af88c216db70p+198"), error: hexf::hexf64!("0x1.1d6a37c0b6c5ep+144") },  // B_84
        Compensated { value: hexf::hexf64!("0x1.121bf0e8b3b62p+206"), error: hexf::hexf64!("0x1.65d629ec726cfp+152") },  // B_86
        Compensated { value: hexf::hexf64!("-0x1.9f4b48fe4ba89p+213"), error: hexf::hexf64!("0x1.37d9f4e0db222p+159") },  // B_88
        Compensated { value: hexf::hexf64!("0x1.49255f089de35p+221"), error: hexf::hexf64!("-0x1.86954cb0b7d4ep+166") },  // B_90
        Compensated { value: hexf::hexf64!("-0x1.10a86bb07f7ccp+229"), error: hexf::hexf64!("0x1.7f3749449d079p+174") },  // B_92
        Compensated { value: hexf::hexf64!("0x1.d7b155e1828d1p+236"), error: hexf::hexf64!("0x1.482ca5b4f1e81p+182") },  // B_94
        Compensated { value: hexf::hexf64!("-0x1.a9a6d19a8b278p+244"), error: hexf::hexf64!("-0x1.2c752e3110f27p+189") },  // B_96
        Compensated { value: hexf::hexf64!("0x1.905c91b9e0c60p+252"), error: hexf::hexf64!("-0x1.64fb4d04ffadbp+196") },  // B_98
        Compensated { value: hexf::hexf64!("-0x1.882ea65d5f668p+260"), error: hexf::hexf64!("0x1.89183e5130551p+204") },  // B_100
        Compensated { value: hexf::hexf64!("0x1.8fc5039bbe2f0p+268"), error: hexf::hexf64!("-0x1.c06472726c549p+213") },  // B_102
        Compensated { value: hexf::hexf64!("-0x1.a7b8bb5da7189p+276"), error: hexf::hexf64!("0x1.27bb55a137096p+222") },  // B_104
        Compensated { value: hexf::hexf64!("0x1.d2a238669d52cp+284"), error: hexf::hexf64!("-0x1.7d9b017aa8caep+228") },  // B_106
        Compensated { value: hexf::hexf64!("-0x1.0ac7c7f017b6dp+293"), error: hexf::hexf64!("-0x1.2557577df3e69p+239") },  // B_108
        Compensated { value: hexf::hexf64!("0x1.3c7ff095babe9p+301"), error: hexf::hexf64!("-0x1.b75cdb005bc3fp+245") },  // B_110
        Compensated { value: hexf::hexf64!("-0x1.8553c0208c906p+309"), error: hexf::hexf64!("-0x1.47066ce7e0f86p+255") },  // B_112
        Compensated { value: hexf::hexf64!("0x1.f03f588f752f0p+317"), error: hexf::hexf64!("0x1.35feebe96ffb6p+263") },  // B_114
        Compensated { value: hexf::hexf64!("-0x1.478287faf03b2p+326"), error: hexf::hexf64!("-0x1.f7d5de13301d8p+272") },  // B_116
        Compensated { value: hexf::hexf64!("0x1.bf65810e09281p+334"), error: hexf::hexf64!("0x1.7dbe0423361b4p+280") },  // B_118
        Compensated { value: hexf::hexf64!("-0x1.3c136050812b0p+343"), error: hexf::hexf64!("-0x1.c214bb5807440p+289") },  // B_120
        Compensated { value: hexf::hexf64!("0x1.cdacdd12aa6d3p+351"), error: hexf::hexf64!("0x1.b59b4afa5b523p+295") },  // B_122
        Compensated { value: hexf::hexf64!("-0x1.5c5d45469aefcp+360"), error: hexf::hexf64!("-0x1.b256542adc401p+305") },  // B_124
        Compensated { value: hexf::hexf64!("0x1.0f725a4bfb8fdp+369"), error: hexf::hexf64!("-0x1.e291ee99adcf3p+312") },  // B_126
        Compensated { value: hexf::hexf64!("-0x1.b49d69397c7aap+377"), error: hexf::hexf64!("-0x1.7e6a39bec3770p+323") },  // B_128
        Compensated { value: hexf::hexf64!("0x1.6a3e9d3cfb97bp+386"), error: hexf::hexf64!("-0x1.a0d7f05862b78p+332") },  // B_130
        Compensated { value: hexf::hexf64!("-0x1.35e5a4aa27b05p+395"), error: hexf::hexf64!("0x1.54ffec180f17bp+340") },  // B_132
        Compensated { value: hexf::hexf64!("0x1.113d6c7398f81p+404"), error: hexf::hexf64!("0x1.f0e6012a162bep+350") },  // B_134
        Compensated { value: hexf::hexf64!("-0x1.f0621f0c35b1dp+412"), error: hexf::hexf64!("0x1.9a93000a9b439p+355") },  // B_136
        Compensated { value: hexf::hexf64!("0x1.d049a19e883adp+421"), error: hexf::hexf64!("0x1.66e73b46d92bdp+364") },  // B_138
        Compensated { value: hexf::hexf64!("-0x1.befe15011e6d4p+430"), error: hexf::hexf64!("0x1.413de27e9623fp+371") },  // B_140
        Compensated { value: hexf::hexf64!("0x1.bac5126b77da1p+439"), error: hexf::hexf64!("0x1.7803dedd9e3e6p+383") },  // B_142
        Compensated { value: hexf::hexf64!("-0x1.c312b055ddc82p+448"), error: hexf::hexf64!("0x1.840034415a35fp+387") },  // B_144
        Compensated { value: hexf::hexf64!("0x1.d86e3a145c6ebp+457"), error: hexf::hexf64!("0x1.b36c4fcfc1443p+402") },  // B_146
        Compensated { value: hexf::hexf64!("-0x1.fc7eeb0cea20ap+466"), error: hexf::hexf64!("0x1.1801ae439838bp+412") },  // B_148
        Compensated { value: hexf::hexf64!("0x1.1920f263c8a25p+476"), error: hexf::hexf64!("0x1.a95fa0c6ce2fep+421") },  // B_150
        Compensated { value: hexf::hexf64!("-0x1.3f396f67416fcp+485"), error: hexf::hexf64!("0x1.69a154a8feed7p+430") },  // B_152
        Compensated { value: hexf::hexf64!("0x1.741db97596caep+494"), error: hexf::hexf64!("-0x1.21545ca606d58p+440") },  // B_154
        Compensated { value: hexf::hexf64!("-0x1.bd260eb8bdbd0p+503"), error: hexf::hexf64!("-0x1.9a3d3a45fdcd8p+448") },  // B_156
        Compensated { value: hexf::hexf64!("0x1.11268c0f0c635p+513"), error: hexf::hexf64!("-0x1.6bbae7730e70ap+459") },  // B_158
        Compensated { value: hexf::hexf64!("-0x1.57c97cdb0f740p+522"), error: hexf::hexf64!("0x1.2d5319a912149p+466") },  // B_160
        Compensated { value: hexf::hexf64!("0x1.bb9c00546c061p+531"), error: hexf::hexf64!("0x1.9842f4998bd70p+475") },  // B_162
        Compensated { value: hexf::hexf64!("-0x1.25573f0242fc7p+541"), error: hexf::hexf64!("0x1.0aa764143ced9p+482") },  // B_164
        Compensated { value: hexf::hexf64!("0x1.8d7f74eab9b91p+550"), error: hexf::hexf64!("0x1.22c33675a76afp+495") },  // B_166
        Compensated { value: hexf::hexf64!("-0x1.13de226920b34p+560"), error: hexf::hexf64!("-0x1.0a92f7d160a54p+502") },  // B_168
        Compensated { value: hexf::hexf64!("0x1.881be6eab9930p+569"), error: hexf::hexf64!("-0x1.fbfa62d202591p+515") },  // B_170
        Compensated { value: hexf::hexf64!("-0x1.1d47bcba0d968p+579"), error: hexf::hexf64!("-0x1.54e98b3decdeep+523") },  // B_172
        Compensated { value: hexf::hexf64!("0x1.a8da06689c810p+588"), error: hexf::hexf64!("0x1.884dd4f3ea376p+533") },  // B_174
        Compensated { value: hexf::hexf64!("-0x1.43b075f0ac6c9p+598"), error: hexf::hexf64!("0x1.894762947a32ep+543") },  // B_176
        Compensated { value: hexf::hexf64!("0x1.f8892493f213dp+607"), error: hexf::hexf64!("-0x1.7e00ed0a847abp+553") },  // B_178
        Compensated { value: hexf::hexf64!("-0x1.921f36b405c55p+617"), error: hexf::hexf64!("0x1.acf6f378eff16p+562") },  // B_180
        Compensated { value: hexf::hexf64!("0x1.47adb617d6c17p+627"), error: hexf::hexf64!("-0x1.74d1523da7aa0p+573") },  // B_182
        Compensated { value: hexf::hexf64!("-0x1.10ef0a5f997aep+637"), error: hexf::hexf64!("0x1.ca36a6b8d5ea2p+583") },  // B_184
        Compensated { value: hexf::hexf64!("0x1.d0a2a4573cd82p+646"), error: hexf::hexf64!("0x1.b45e368c78bc0p+592") },  // B_186
        Compensated { value: hexf::hexf64!("-0x1.9410d186f5debp+656"), error: hexf::hexf64!("-0x1.4f5fc59ed4986p+602") },  // B_188
        Compensated { value: hexf::hexf64!("0x1.66eda4abe908fp+666"), error: hexf::hexf64!("-0x1.c92e9d47508fcp+611") },  // B_190
        Compensated { value: hexf::hexf64!("-0x1.45994135d6528p+676"), error: hexf::hexf64!("-0x1.31486c6497072p+622") },  // B_192
        Compensated { value: hexf::hexf64!("0x1.2d90d1afaccefp+686"), error: hexf::hexf64!("0x1.a77b2fcdbe47fp+632") },  // B_194
        Compensated { value: hexf::hexf64!("-0x1.1d1c3db39f23ep+696"), error: hexf::hexf64!("0x1.6f7b3bb6dd078p+640") },  // B_196
        Compensated { value: hexf::hexf64!("0x1.1318a33735a3dp+706"), error: hexf::hexf64!("0x1.4d2c46b4d33b8p+652") },  // B_198
        Compensated { value: hexf::hexf64!("-0x1.0ed6473e25b10p+716"), error: hexf::hexf64!("0x1.04a961640c069p+662") },  // B_200
        Compensated { value: hexf::hexf64!("0x1.10044ea7d6917p+726"), error: hexf::hexf64!("0x1.6a8aa1b9c5b36p+672") },  // B_202
        Compensated { value: hexf::hexf64!("-0x1.16a6ee4e5d42bp+736"), error: hexf::hexf64!("0x1.c8eafe043e901p+681") },  // B_204
        Compensated { value: hexf::hexf64!("0x1.23166b4aa4086p+746"), error: hexf::hexf64!("-0x1.e67a628450703p+691") },  // B_206
        Compensated { value: hexf::hexf64!("-0x1.3606924daed60p+756"), error: hexf::hexf64!("-0x1.0ef2657d74267p+701") },  // B_208
        Compensated { value: hexf::hexf64!("0x1.509780bd94a8cp+766"), error: hexf::hexf64!("0x1.ddb71a3fd6ccbp+712") },  // B_210
        Compensated { value: hexf::hexf64!("-0x1.7471ec747a9f0p+776"), error: hexf::hexf64!("-0x1.1566d71469e66p+721") },  // B_212
        Compensated { value: hexf::hexf64!("0x1.a3f2c51c999aep+786"), error: hexf::hexf64!("-0x1.39d38643c4c68p+732") },  // B_214
        Compensated { value: hexf::hexf64!("-0x1.e26c64034384ep+796"), error: hexf::hexf64!("0x1.359ff8e5a843ap+740") },  // B_216
        Compensated { value: hexf::hexf64!("0x1.1a437c7ec5494p+807"), error: hexf::hexf64!("0x1.0a5bdc166e8cep+751") },  // B_218
        Compensated { value: hexf::hexf64!("-0x1.506797fc03c19p+817"), error: hexf::hexf64!("0x1.5fd930f3e3741p+763") },  // B_220
        Compensated { value: hexf::hexf64!("0x1.984524707c094p+827"), error: hexf::hexf64!("0x1.872e8256a3497p+773") },  // B_222
        Compensated { value: hexf::hexf64!("-0x1.f879ed6383b1fp+837"), error: hexf::hexf64!("0x1.55dc4357605e5p+782") },  // B_224
        Compensated { value: hexf::hexf64!("0x1.3d478d9282c46p+848"), error: hexf::hexf64!("-0x1.81b7a324b0b97p+794") },  // B_226
        Compensated { value: hexf::hexf64!("-0x1.9633f1cfe7836p+858"), error: hexf::hexf64!("-0x1.411dab0524dacp+803") },  // B_228
        Compensated { value: hexf::hexf64!("0x1.089dc8734bdcdp+869"), error: hexf::hexf64!("-0x1.045ad7fa3a778p+815") },  // B_230
        Compensated { value: hexf::hexf64!("-0x1.5ecc403e5c99cp+879"), error: hexf::hexf64!("0x1.5d11f5891f7f6p+822") },  // B_232
        Compensated { value: hexf::hexf64!("0x1.d91e14a3e64bdp+889"), error: hexf::hexf64!("-0x1.29904b28d1c21p+835") },  // B_234
        Compensated { value: hexf::hexf64!("-0x1.448882abcec43p+900"), error: hexf::hexf64!("-0x1.1c9e8cc3deef7p+846") },  // B_236
        Compensated { value: hexf::hexf64!("0x1.c4d1b4dd2f84cp+910"), error: hexf::hexf64!("0x1.a4878a17e65e4p+855") },  // B_238
        Compensated { value: hexf::hexf64!("-0x1.4140363042a28p+921"), error: hexf::hexf64!("0x1.156911097a742p+867") },  // B_240
        Compensated { value: hexf::hexf64!("0x1.cf770c1bf7fabp+931"), error: hexf::hexf64!("-0x1.77a89f0e103e4p+876") },  // B_242
        Compensated { value: hexf::hexf64!("-0x1.53e0d5577b05dp+942"), error: hexf::hexf64!("0x1.7ed59e2539663p+888") },  // B_244
        Compensated { value: hexf::hexf64!("0x1.fab75fb4b91c3p+952"), error: hexf::hexf64!("-0x1.fa55205a34ec2p+898") },  // B_246
        Compensated { value: hexf::hexf64!("-0x1.7fe7b1445db22p+963"), error: hexf::hexf64!("0x1.484d76af82d00p+909") },  // B_248
        Compensated { value: hexf::hexf64!("0x1.27943589f4ed2p+974"), error: hexf::hexf64!("0x1.1efc860e277e8p+920") },  // B_250
        Compensated { value: hexf::hexf64!("-0x1.ce798b814fe1ap+984"), error: hexf::hexf64!("-0x1.4c495c3041276p+930") },  // B_252
        Compensated { value: hexf::hexf64!("0x1.6f94a39e67a04p+995"), error: hexf::hexf64!("0x1.d0d53bcbfd69ap+940") },  // B_254
        Compensated { value: hexf::hexf64!("-0x1.28c927cd93856p+1006"), error: hexf::hexf64!("-0x1.3da9a47616f59p+950") },  // B_256
        Compensated { value: hexf::hexf64!("0x1.e6c8ad47dd95ap+1016"), error: hexf::hexf64!("-0x1.e5317c3746b63p+960") },  // B_258
    ];
}
