// @generated by gen_consts.py at the workspace root. DO NOT EDIT BY HAND.
//
// Double-double `(value, error)` splits of every `FloatConsts` constant, plus the
// reciprocal-log table `log_base` reduces through. The carrier/macro machinery is
// hand-written in `macros.rs` beside this file.
#![allow(clippy::approx_constant)]

#[macro_use]
mod macros;

use core::marker::PhantomData;

use thermite::{
    Vector,
    math::FloatConsts,
    vector::{SplatConst, const_splat},
};

use super::{Compensated, ScalarValue};

use self::macros::{Ln2Extended, LogTableError, LogTableValue};

pub const LOG_TABLE_SIZE: usize = 30;

/// Helper trait to store precomputed compensated logarithm table for small integer bases.
pub trait CompensatedLogTable<T = Self>: FloatConsts {
    /// The log table entries for bases 3..=32 as (high, low) pairs.
    const LOG_TABLE: [Compensated<T>; LOG_TABLE_SIZE];

    /// Third part of extended precision ln(2), where the first two parts are provided by `LN_2`.
    const LN_2_EXTENDED: [T; 3];
}

impl<R: thermite::register::FloatRegister> CompensatedLogTable<Self> for Vector<R>
where
    R::Element: CompensatedLogTable<R::Element>,
{
    #[rustfmt::skip]
    const LOG_TABLE: [Compensated<Self>; LOG_TABLE_SIZE] = log_table!(
         0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
        10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
    );

    const LN_2_EXTENDED: [Self; 3] = [
        const_splat::<Self, Ln2Extended<R::Element, 0>>(),
        const_splat::<Self, Ln2Extended<R::Element, 1>>(),
        const_splat::<Self, Ln2Extended<R::Element, 2>>(),
    ];
}

thermite::for_each_float_const!(impl_consts);

impl_consts!(f32 {
    NEG_ZERO = ("-0x0.0p+0", "0x0.0p+0"),
    E = ("0x1.5bf0a80000000p+1", "0x1.628aee0000000p-24"),
    EULER_GAMMA = ("0x1.2788d00000000p-1", "-0x1.c824f40000000p-28"),
    PI_SQUARED = ("0x1.3bd3cc0000000p+3", "0x1.37c8bc0000000p-22"),
    PI_CUBED = ("0x1.f019b60000000p+4", "-0x1.b1d8a00000000p-22"),
    PI_FOURTH = ("0x1.85a2e80000000p+6", "0x1.8521040000000p-19"),
    FRAC_1_PI = ("0x1.45f3060000000p-2", "0x1.b939100000000p-27"),
    FRAC_1_SQRT_2 = ("0x1.6a09e60000000p-1", "0x1.9fcef40000000p-27"),
    FRAC_1_SQRT_3 = ("0x1.279a740000000p-1", "0x1.640cc80000000p-27"),
    FRAC_1_SQRT_5 = ("0x1.c9f25c0000000p-2", "0x1.6ffb760000000p-28"),
    FRAC_2_PI = ("0x1.45f3060000000p-1", "0x1.b939100000000p-26"),
    FRAC_1_SQRT_PI = ("0x1.20dd760000000p-1", "-0x1.f7ac920000000p-26"),
    FRAC_2_SQRT_PI = ("0x1.20dd760000000p+0", "-0x1.f7ac920000000p-25"),
    FRAC_SQRT_PI_2 = ("0x1.c5bf8a0000000p-1", "-0x1.c962120000000p-26"),
    FRAC_1_SQRT_TAU = ("0x1.9884540000000p-2", "-0x1.8579360000000p-27"),
    FRAC_PI_2 = ("0x1.921fb60000000p+0", "-0x1.777a5c0000000p-25"),
    FRAC_PI_3 = ("0x1.0c15240000000p+0", "-0x1.f4a3260000000p-26"),
    FRAC_PI_4 = ("0x1.921fb60000000p-1", "-0x1.777a5c0000000p-26"),
    FRAC_PI_6 = ("0x1.0c15240000000p-1", "-0x1.f4a3260000000p-27"),
    FRAC_PI_8 = ("0x1.921fb60000000p-2", "-0x1.777a5c0000000p-27"),
    FRAC_PI_180 = ("0x1.1df46a0000000p-6", "0x1.294e9c0000000p-33"),
    FRAC_180_PI = ("0x1.ca5dc20000000p+5", "-0x1.670f820000000p-21"),
    LN_2 = ("0x1.62e4300000000p-1", "-0x1.05c6100000000p-29"),
    LN_10 = ("0x1.26bb1c0000000p+1", "-0x1.12aaba0000000p-25"),
    LN_PI = ("0x1.250d040000000p+0", "0x1.1cf4380000000p-25"),
    LN_TAU = ("0x1.d67f1c0000000p+0", "0x1.0c97d60000000p-25"),
    FRAC_LN_PI_2 = ("0x1.250d040000000p-1", "0x1.1cf4380000000p-26"),
    FRAC_LN_TAU_2 = ("0x1.d67f1c0000000p-1", "0x1.0c97d60000000p-26"),
    LOG2_10 = ("0x1.a934f00000000p+1", "0x1.2f346e0000000p-24"),
    LOG2_E = ("0x1.7154760000000p+0", "0x1.4ae0c00000000p-26"),
    LOG2_PI = ("0x1.a6c8740000000p+0", "-0x1.6ce4420000000p-25"),
    LOG10_2 = ("0x1.3441360000000p-2", "-0x1.ec10c00000000p-27"),
    LOG10_E = ("0x1.bcb7b20000000p-2", "-0x1.5b235e0000000p-27"),
    PI = ("0x1.921fb60000000p+1", "-0x1.777a5c0000000p-24"),
    SQRT_2 = ("0x1.6a09e60000000p+0", "0x1.9fcef40000000p-26"),
    SQRT_3 = ("0x1.bb67ae0000000p+0", "0x1.0b09960000000p-25"),
    SQRT_5 = ("0x1.1e377a0000000p+1", "-0x1.1a02d60000000p-25"),
    SQRT_E = ("0x1.a612980000000p+0", "0x1.c3c0d40000000p-25"),
    EPSILON = ("0x1.0000000000000p-47", "0x0.0p+0"),
    SQRT_EPSILON = ("0x1.6a09e60000000p-24", "0x1.9fcef40000000p-50"),
    FOURTH_ROOT_EPSILON = ("0x1.306fe00000000p-12", "0x1.4636e20000000p-37"),
    TAU = ("0x1.921fb60000000p+2", "-0x1.777a5c0000000p-23"),
    SQRT_FRAC_PI_2 = ("0x1.40d9320000000p+0", "-0x1.3b1f4e0000000p-33"),
    SQRT_TAU = ("0x1.40d9320000000p+1", "-0x1.3b1f4e0000000p-32"),
    PHI = ("0x1.9e377a0000000p+0", "-0x1.1a02d60000000p-26"),
    FRAC_1_PHI = ("0x1.3c6ef40000000p-1", "-0x1.1a02d60000000p-26"),
    FRAC_1_PHI_SQUARED = ("0x1.87221a0000000p-2", "-0x1.cbfa540000000p-27"),
    GOLDEN_ANGLE = ("0x1.3331fe0000000p+1", "0x1.7f49800000000p-24"),
    FRAC_1_3 = ("0x1.5555560000000p-2", "-0x1.5555560000000p-27"),
    FRAC_2_3 = ("0x1.5555560000000p-1", "-0x1.5555560000000p-26"),
    FRAC_1_4 = ("0x1.0000000000000p-2", "0x0.0p+0"),
    FRAC_1_6 = ("0x1.5555560000000p-3", "-0x1.5555560000000p-28"),
    FRAC_1_E = ("0x1.78b5640000000p-2", "-0x1.3a621a0000000p-27"),
    FRAC_NEG_1_E = ("-0x1.78b5640000000p-2", "0x1.3a621a0000000p-27"),
    FRAC_1_2 = ("0x1.0000000000000p-1", "0x0.0p+0"),
    FRAC_3_4 = ("0x1.8000000000000p-1", "0x0.0p+0"),
    LN_LN_2 = ("-0x1.774f2a0000000p-2", "0x1.08a5180000000p-28"),
    SQRT_LN_4 = ("0x1.2d6abe0000000p+0", "0x1.12bf100000000p-26"),
    FRAC_2PI_3 = ("0x1.0c15240000000p+1", "-0x1.f4a3260000000p-25"),
    FRAC_3PI_4 = ("0x1.2d97c80000000p+1", "-0x1.99bc5c0000000p-28"),
    FRAC_4PI_3 = ("0x1.0c15240000000p+2", "-0x1.f4a3260000000p-24"),
    FOUR_PI = ("0x1.921fb60000000p+3", "-0x1.777a5c0000000p-22"),
    FRAC_1_4PI = ("0x1.45f3060000000p-4", "0x1.b939100000000p-29"),
    FRAC_1_TAU = ("0x1.45f3060000000p-3", "0x1.b939100000000p-28"),
    SQRT_PI = ("0x1.c5bf8a0000000p+0", "-0x1.c962120000000p-25"),
    PI_MINUS_3 = ("0x1.21fb540000000p-3", "0x1.10b4620000000p-29"),
    FOUR_MINUS_PI = ("0x1.b7812a0000000p-1", "0x1.dde9740000000p-26"),
    PI_POW_E = ("0x1.6758b60000000p+4", "-0x1.e3f7780000000p-23"),
    CBRT_2 = ("0x1.428a300000000p+0", "-0x1.9ca35e0000000p-26"),
    CBRT_3 = ("0x1.7137440000000p+0", "0x1.2247de0000000p-25"),
    CBRT_PI = ("0x1.76ef7e0000000p+0", "0x1.cc412e0000000p-26"),
    FRAC_1_CBRT_PI = ("0x1.5d95e00000000p-1", "-0x1.285aa20000000p-26"),
    FRAC_1_SQRT_E = ("0x1.368b300000000p-1", "-0x1.c834fc0000000p-28"),
    E_POW_PI = ("0x1.7240460000000p+4", "0x1.d612680000000p-21"),
    GELFOND_SCHNEIDER = ("0x1.5523720000000p+1", "-0x1.0c05000000000p-24"),
    SIN_1 = ("0x1.aed5480000000p-1", "0x1.e1219e0000000p-26"),
    COS_1 = ("0x1.14a2800000000p-1", "0x1.f6a0d20000000p-26"),
    TAN_1 = ("0x1.8eb2460000000p+0", "-0x1.a08e2e0000000p-27"),
    SINH_1 = ("0x1.2cd9fc0000000p+0", "0x1.13ae600000000p-26"),
    COSH_1 = ("0x1.8b07560000000p+0", "-0x1.c4c1560000000p-25"),
    TANH_1 = ("0x1.85efac0000000p-1", "-0x1.5d618e0000000p-26"),
    LN_PHI = ("0x1.ecc2ca0000000p-2", "0x1.d8a2c20000000p-27"),
    FRAC_1_LN_PHI = ("0x1.09fec00000000p+1", "0x1.24f3240000000p-24"),
    FRAC_1_EULER_GAMMA = ("0x1.bb82260000000p+0", "0x1.ea057e0000000p-25"),
    EULER_GAMMA_SQUARED = ("0x1.552c980000000p-2", "-0x1.7f25aa0000000p-32"),
    ZETA_2 = ("0x1.a51a660000000p+0", "0x1.2983ea0000000p-27"),
    ZETA_3 = ("0x1.33ba000000000p+0", "0x1.3c01880000000p-26"),
    ZETA_4 = ("0x1.1513220000000p+0", "0x1.58fb0a0000000p-25"),
    CATALAN = ("0x1.d4f9720000000p-1", "-0x1.82fd940000000p-26"),
    GLAISHER = ("0x1.484d240000000p+0", "0x1.e5fb0e0000000p-25"),
    KHINCHIN = ("0x1.57bce40000000p+1", "0x1.1e36860000000p-26"),
    LEVY = ("0x1.a34e2a0000000p+1", "0x1.5ecb7e0000000p-25"),
    EXTREME_VALUE_SKEWNESS = ("0x1.23b95c0000000p+0", "-0x1.5e71680000000p-27"),
    RAYLEIGH_SKEWNESS = ("0x1.4320f00000000p-1", "-0x1.6415c00000000p-27"),
    RAYLEIGH_KURTOSIS_EXCESS = ("0x1.f5f1620000000p-3", "-0x1.cf27420000000p-28"),
    RAYLEIGH_KURTOSIS = ("0x1.9f5f160000000p+1", "0x1.186c600000000p-27"),
    FEIGENBAUM_DELTA = ("0x1.2ad4320000000p+2", "0x1.f8c3920000000p-23"),
    PLASTIC_RATIO = ("0x1.5320b80000000p+0", "-0x1.626b760000000p-25"),
    FRAC_1_PLASTIC_RATIO = ("0x1.827f540000000p-1", "-0x1.5bf5680000000p-26"),
    FRAC_1_PLASTIC_RATIO_SQUARED = ("0x1.23c21c0000000p-1", "-0x1.68e1860000000p-26"),
    GAUSS = ("0x1.ab54360000000p-1", "-0x1.952b300000000p-27"),
    LEMNISCATE = ("0x1.4f9f940000000p+1", "0x1.f3ea160000000p-24"),
    DOTTIE = ("0x1.7a695e0000000p-1", "-0x1.3e18ea0000000p-28"),
    OMEGA = ("0x1.22609a0000000p-1", "0x1.f1d2ca0000000p-26"),
    PSI = ("0x1.ae10bc0000000p+1", "-0x1.c4beda0000000p-26"),
    LAPLACE_LIMIT = ("0x1.53531a0000000p-1", "0x1.fef9ce0000000p-26"),
    ERDOS_BORWEIN = ("0x1.9b50600000000p+0", "-0x1.86f0380000000p-26"),
    NIVEN = ("0x1.b488b80000000p+0", "-0x1.81e3ea0000000p-26"),
    SOLDNER = ("0x1.738cf00000000p+0", "-0x1.b382bc0000000p-25"),
    FRANSEN_ROBINSON = ("0x1.6765040000000p+1", "-0x1.5e71ac0000000p-27"),
    GOLOMB_DICKMAN = ("0x1.3fa82e0000000p-1", "0x1.2b4e420000000p-28"),
    TWIN_PRIME = ("0x1.5200ba0000000p-1", "0x1.8485680000000p-26"),
    MERTENS = ("0x1.0bc5ec0000000p-2", "0x1.c967fe0000000p-27"),
    ARTIN = ("0x1.7eee460000000p-2", "-0x1.4b68140000000p-29"),
});

impl_consts!(f64 {
    NEG_ZERO = ("-0x0.0p+0", "0x0.0p+0"),
    E = ("0x1.5bf0a8b145769p+1", "0x1.4d57ee2b1013ap-53"),
    EULER_GAMMA = ("0x1.2788cfc6fb619p-1", "-0x1.6cb90701fbfabp-58"),
    PI_SQUARED = ("0x1.3bd3cc9be45dep+3", "0x1.692b71366cc04p-51"),
    PI_CUBED = ("0x1.f019b59389d7cp+4", "0x1.e019558e5380dp-52"),
    PI_FOURTH = ("0x1.85a2e8c290826p+6", "-0x1.cc0cdf4bfa1e7p-48"),
    FRAC_1_PI = ("0x1.45f306dc9c883p-2", "-0x1.6b01ec5417056p-56"),
    FRAC_1_SQRT_2 = ("0x1.6a09e667f3bcdp-1", "-0x1.bdd3413b26456p-55"),
    FRAC_1_SQRT_3 = ("0x1.279a74590331cp-1", "0x1.34863e0792bedp-55"),
    FRAC_1_SQRT_5 = ("0x1.c9f25c5bfedd9p-2", "0x1.ab294a33804a5p-57"),
    FRAC_2_PI = ("0x1.45f306dc9c883p-1", "-0x1.6b01ec5417056p-55"),
    FRAC_1_SQRT_PI = ("0x1.20dd750429b6dp-1", "0x1.1ae3a914fed80p-57"),
    FRAC_2_SQRT_PI = ("0x1.20dd750429b6dp+0", "0x1.1ae3a914fed80p-56"),
    FRAC_SQRT_PI_2 = ("0x1.c5bf891b4ef6bp-1", "-0x1.618f13eb7ca89p-55"),
    FRAC_1_SQRT_TAU = ("0x1.9884533d43651p-2", "-0x1.cbc0d30ebfd15p-56"),
    FRAC_PI_2 = ("0x1.921fb54442d18p+0", "0x1.1a62633145c07p-54"),
    FRAC_PI_3 = ("0x1.0c152382d7366p+0", "-0x1.ee6913347c2a6p-54"),
    FRAC_PI_4 = ("0x1.921fb54442d18p-1", "0x1.1a62633145c07p-55"),
    FRAC_PI_6 = ("0x1.0c152382d7366p-1", "-0x1.ee6913347c2a6p-55"),
    FRAC_PI_8 = ("0x1.921fb54442d18p-2", "0x1.1a62633145c07p-56"),
    FRAC_PI_180 = ("0x1.1df46a2529d39p-6", "0x1.5c1d8becdd291p-62"),
    FRAC_180_PI = ("0x1.ca5dc1a63c1f8p+5", "-0x1.1e7ab456405f9p-49"),
    LN_2 = ("0x1.62e42fefa39efp-1", "0x1.abc9e3b39803fp-56"),
    LN_10 = ("0x1.26bb1bbb55516p+1", "-0x1.f48ad494ea3e9p-53"),
    LN_PI = ("0x1.250d048e7a1bdp+0", "0x1.7abf2ad8d5088p-57"),
    LN_TAU = ("0x1.d67f1c864beb5p+0", "-0x1.65b5a1b7ff5dfp-54"),
    FRAC_LN_PI_2 = ("0x1.250d048e7a1bdp-1", "0x1.7abf2ad8d5088p-58"),
    FRAC_LN_TAU_2 = ("0x1.d67f1c864beb5p-1", "-0x1.65b5a1b7ff5dfp-55"),
    LOG2_10 = ("0x1.a934f0979a371p+1", "0x1.7f2495fb7fa6dp-53"),
    LOG2_E = ("0x1.71547652b82fep+0", "0x1.777d0ffda0d24p-56"),
    LOG2_PI = ("0x1.a6c873498ddf7p+0", "0x1.6c36cb93c202ap-54"),
    LOG10_2 = ("0x1.34413509f79ffp-2", "-0x1.9dc1da994fd21p-59"),
    LOG10_E = ("0x1.bcb7b1526e50ep-2", "0x1.95355baaafad3p-57"),
    PI = ("0x1.921fb54442d18p+1", "0x1.1a62633145c07p-53"),
    SQRT_2 = ("0x1.6a09e667f3bcdp+0", "-0x1.bdd3413b26456p-54"),
    SQRT_3 = ("0x1.bb67ae8584caap+0", "0x1.cec95d0b5c1e3p-54"),
    SQRT_5 = ("0x1.1e3779b97f4a8p+1", "-0x1.f506319fcfd19p-54"),
    SQRT_E = ("0x1.a61298e1e069cp+0", "-0x1.b4690082a4906p-55"),
    EPSILON = ("0x1.0000000000000p-105", "0x0.0p+0"),
    SQRT_EPSILON = ("0x1.6a09e667f3bcdp-53", "-0x1.bdd3413b26456p-107"),
    FOURTH_ROOT_EPSILON = ("0x1.ae89f995ad3adp-27", "0x1.7a1cd345dcc81p-81"),
    TAU = ("0x1.921fb54442d18p+2", "0x1.1a62633145c07p-52"),
    SQRT_FRAC_PI_2 = ("0x1.40d931ff62706p+0", "-0x1.a6a0d6f814637p-54"),
    SQRT_TAU = ("0x1.40d931ff62706p+1", "-0x1.a6a0d6f814637p-53"),
    PHI = ("0x1.9e3779b97f4a8p+0", "-0x1.f506319fcfd19p-55"),
    FRAC_1_PHI = ("0x1.3c6ef372fe950p-1", "-0x1.f506319fcfd19p-55"),
    FRAC_1_PHI_SQUARED = ("0x1.8722191a02d61p-2", "-0x1.5f39cc0605ceep-60"),
    GOLDEN_ANGLE = ("0x1.3331febfa4bfcp+1", "-0x1.9ebb7adf6e3c9p-53"),
    FRAC_1_3 = ("0x1.5555555555555p-2", "0x1.5555555555555p-56"),
    FRAC_2_3 = ("0x1.5555555555555p-1", "0x1.5555555555555p-55"),
    FRAC_1_4 = ("0x1.0000000000000p-2", "0x0.0p+0"),
    FRAC_1_6 = ("0x1.5555555555555p-3", "0x1.5555555555555p-57"),
    FRAC_1_E = ("0x1.78b56362cef38p-2", "-0x1.ca8a4270fadf5p-57"),
    FRAC_NEG_1_E = ("-0x1.78b56362cef38p-2", "0x1.ca8a4270fadf5p-57"),
    FRAC_1_2 = ("0x1.0000000000000p-1", "0x0.0p+0"),
    FRAC_3_4 = ("0x1.8000000000000p-1", "0x0.0p+0"),
    LN_LN_2 = ("-0x1.774f29bdd6b9fp-2", "0x1.7c1fc8982991dp-56"),
    SQRT_LN_4 = ("0x1.2d6abe44afc43p+0", "0x1.fb5e9fb2b55bbp-56"),
    FRAC_2PI_3 = ("0x1.0c152382d7366p+1", "-0x1.ee6913347c2a6p-53"),
    FRAC_3PI_4 = ("0x1.2d97c7f3321d2p+1", "0x1.a79394c9e8a0ap-54"),
    FRAC_4PI_3 = ("0x1.0c152382d7366p+2", "-0x1.ee6913347c2a6p-52"),
    FOUR_PI = ("0x1.921fb54442d18p+3", "0x1.1a62633145c07p-51"),
    FRAC_1_4PI = ("0x1.45f306dc9c883p-4", "-0x1.6b01ec5417056p-58"),
    FRAC_1_TAU = ("0x1.45f306dc9c883p-3", "-0x1.6b01ec5417056p-57"),
    SQRT_PI = ("0x1.c5bf891b4ef6bp+0", "-0x1.618f13eb7ca89p-54"),
    PI_MINUS_3 = ("0x1.21fb54442d184p-3", "0x1.a62633145c06ep-57"),
    FOUR_MINUS_PI = ("0x1.b7812aeef4b9fp-1", "-0x1.a62633145c06ep-57"),
    PI_POW_E = ("0x1.6758b5c381111p+4", "0x1.c590b3b71e332p-51"),
    CBRT_2 = ("0x1.428a2f98d728bp+0", "-0x1.ddc22548ea41ep-56"),
    CBRT_3 = ("0x1.7137449123ef6p+0", "0x1.73779fc5b15b9p-54"),
    CBRT_PI = ("0x1.76ef7e73104b8p+0", "-0x1.d41ba28e4f999p-54"),
    FRAC_1_CBRT_PI = ("0x1.5d95df6bd2aeep-1", "-0x1.9749756e80c72p-55"),
    FRAC_1_SQRT_E = ("0x1.368b2fc6f960ap-1", "-0x1.85314b9559e64p-61"),
    E_POW_PI = ("0x1.724046eb0933ap+4", "-0x1.84c962dd81952p-50"),
    GELFOND_SCHNEIDER = ("0x1.55237179fd803p+1", "0x1.718b63176f20ep-55"),
    SIN_1 = ("0x1.aed548f090ceep-1", "0x1.06374f484e288p-59"),
    COS_1 = ("0x1.14a280fb5068cp-1", "-0x1.b71edcc9344bcp-55"),
    TAN_1 = ("0x1.8eb245cbee3a6p+0", "-0x1.1d4ce0afb373bp-54"),
    SINH_1 = ("0x1.2cd9fc44eb982p+0", "0x1.6a0092521fc19p-54"),
    COSH_1 = ("0x1.8b07551d9f550p+0", "0x1.30af4a040065bp-54"),
    TANH_1 = ("0x1.85efab514f394p-1", "0x1.5618caf8a4f11p-55"),
    LN_PHI = ("0x1.ecc2caec5160ap-2", "-0x1.ad07ef7ed5a5dp-56"),
    FRAC_1_LN_PHI = ("0x1.09fec09279922p+1", "-0x1.6bb3871417f12p-53"),
    FRAC_1_EULER_GAMMA = ("0x1.bb8226f502bf8p+0", "-0x1.7abec73926687p-56"),
    EULER_GAMMA_SQUARED = ("0x1.552c97fa03695p-2", "0x1.456320745c86bp-56"),
    ZETA_2 = ("0x1.a51a6625307d3p+0", "0x1.1873d8912200cp-55"),
    ZETA_3 = ("0x1.33ba004f00621p+0", "0x1.c1b8b8ae2cf35p-55"),
    ZETA_4 = ("0x1.151322ac7d848p+0", "0x1.b5f91211196e5p-55"),
    CATALAN = ("0x1.d4f9713e8135dp-1", "0x1.1485608b8df4dp-58"),
    GLAISHER = ("0x1.484d24f2fd873p+0", "0x1.313ed56e343dap-56"),
    KHINCHIN = ("0x1.57bce423c6d0dp+1", "0x1.de5fbe7c728cdp-53"),
    LEVY = ("0x1.a34e2a57b2df8p+1", "-0x1.4fd4e0ab83370p-53"),
    EXTREME_VALUE_SKEWNESS = ("0x1.23b95bd431d31p+0", "0x1.08492b4c8dae6p-54"),
    RAYLEIGH_SKEWNESS = ("0x1.4320efa6fa904p-1", "-0x1.8bc4ccb8fa389p-56"),
    RAYLEIGH_KURTOSIS_EXCESS = ("0x1.f5f161186c5f2p-3", "-0x1.59a3e3c6197d7p-58"),
    RAYLEIGH_KURTOSIS = ("0x1.9f5f161186c5fp+1", "0x1.d4cb83873cd05p-55"),
    FEIGENBAUM_DELTA = ("0x1.2ad432fc61c97p+2", "0x1.1d1c04ed45ae2p-52"),
    PLASTIC_RATIO = ("0x1.5320b74eca44bp+0", "-0x1.29f43bb41df5dp-55"),
    FRAC_1_PLASTIC_RATIO = ("0x1.827f5352054c6p-1", "0x1.47a1a7fb8d96dp-55"),
    FRAC_1_PLASTIC_RATIO_SQUARED = ("0x1.23c21b4b8f3cfp-1", "0x1.8e6a1c5054736p-55"),
    GAUSS = ("0x1.ab54359ab5344p-1", "-0x1.29db2257d3fd6p-57"),
    LEMNISCATE = ("0x1.4f9f94f9f50b0p+1", "0x1.b9e61ddaeb023p-53"),
    DOTTIE = ("0x1.7a695dd83ce2ep-1", "-0x1.1a9573fe3c5bdp-55"),
    OMEGA = ("0x1.22609af8e9657p-1", "0x1.2f57eed531437p-55"),
    PSI = ("0x1.ae10bbc76824bp+1", "-0x1.c2c8f175467e3p-53"),
    LAPLACE_LIMIT = ("0x1.53531aff7ce6dp-1", "0x1.2ce0dafecc8fbp-57"),
    ERDOS_BORWEIN = ("0x1.9b505f9e43f22p+0", "0x1.0dfcdcb14a049p-54"),
    NIVEN = ("0x1.b488b79f87059p+0", "-0x1.6e8abc567bd64p-56"),
    SOLDNER = ("0x1.738cef263ea25p+0", "-0x1.bd39894e88b11p-55"),
    FRANSEN_ROBINSON = ("0x1.676503ea18e54p+1", "-0x1.a3c17cf5296e0p-53"),
    GOLOMB_DICKMAN = ("0x1.3fa82e2569c83p-1", "0x1.ea135cf9792a6p-55"),
    TWIN_PRIME = ("0x1.5200bac242b40p-1", "-0x1.7c24cb5afd011p-55"),
    MERTENS = ("0x1.0bc5ece4b3fedp-2", "0x1.1f379936e0b34p-56"),
    ARTIN = ("0x1.7eee45d692fd8p-2", "0x1.3e0716e745b46p-56"),
});

impl_consts!(LOG f32 [
    ("0x1.d20ae00000000p-1", "0x1.de60aa0000000p-28"),  // 1/ln(3)
    ("0x1.7154760000000p-1", "0x1.4ae0c00000000p-27"),  // 1/ln(4)
    ("0x1.3e1f9c0000000p-1", "0x1.9f2eee0000000p-26"),  // 1/ln(5)
    ("0x1.1dc0ae0000000p-1", "-0x1.dda6380000000p-26"),  // 1/ln(6)
    ("0x1.071dae0000000p-1", "0x1.f7c96a0000000p-26"),  // 1/ln(7)
    ("0x1.ec709e0000000p-2", "-0x1.e2fe020000000p-29"),  // 1/ln(8)
    ("0x1.d20ae00000000p-2", "0x1.de60aa0000000p-29"),  // 1/ln(9)
    ("0x1.bcb7b20000000p-2", "-0x1.5b235e0000000p-27"),  // 1/ln(10)
    ("0x1.ab0a8a0000000p-2", "0x1.4518740000000p-31"),  // 1/ln(11)
    ("0x1.9c16820000000p-2", "-0x1.a3cddc0000000p-28"),  // 1/ln(12)
    ("0x1.8f3a680000000p-2", "0x1.8014a80000000p-28"),  // 1/ln(13)
    ("0x1.8404700000000p-2", "0x1.10dfaa0000000p-28"),  // 1/ln(14)
    ("0x1.7a21c00000000p-2", "0x1.17d8500000000p-29"),  // 1/ln(15)
    ("0x1.7154760000000p-2", "0x1.4ae0c00000000p-28"),  // 1/ln(16)
    ("0x1.696d540000000p-2", "0x1.0760680000000p-27"),  // 1/ln(17)
    ("0x1.62479a0000000p-2", "-0x1.e2a68a0000000p-28"),  // 1/ln(18)
    ("0x1.5bc6340000000p-2", "-0x1.1fffc20000000p-31"),  // 1/ln(19)
    ("0x1.55d1d20000000p-2", "-0x1.b703f60000000p-27"),  // 1/ln(20)
    ("0x1.50577c0000000p-2", "0x1.a83cf40000000p-27"),  // 1/ln(21)
    ("0x1.4b47a20000000p-2", "0x1.1831800000000p-27"),  // 1/ln(22)
    ("0x1.4695520000000p-2", "0x1.22d24e0000000p-29"),  // 1/ln(23)
    ("0x1.4235b40000000p-2", "-0x1.8912be0000000p-28"),  // 1/ln(24)
    ("0x1.3e1f9c0000000p-2", "0x1.9f2eee0000000p-27"),  // 1/ln(25)
    ("0x1.3a4b400000000p-2", "-0x1.37ecc00000000p-28"),  // 1/ln(26)
    ("0x1.36b1ea0000000p-2", "0x1.a5101c0000000p-27"),  // 1/ln(27)
    ("0x1.334dd80000000p-2", "-0x1.40ea420000000p-27"),  // 1/ln(28)
    ("0x1.301a020000000p-2", "-0x1.03afa00000000p-27"),  // 1/ln(29)
    ("0x1.2d12080000000p-2", "0x1.02e7c00000000p-27"),  // 1/ln(30)
    ("0x1.2a32160000000p-2", "-0x1.8a11340000000p-27"),  // 1/ln(31)
    ("0x1.2776c60000000p-2", "-0x1.e20c800000000p-27"),  // 1/ln(32)
],
// LN_2_EXTENDED: Cody-Waite pieces, NOT simply ln(2) to ever more digits.
//
// `exp_internal` reduces with `r -= k * LN_2_EXTENDED[i]`, where both `k` and the piece
// are plain (uncompensated) vectors, so each product is a single rounded multiply. The
// pieces therefore have to be narrow enough that those products are exact, which is
// what buys the reduction its accuracy. The compensated subtraction around them is
// already exact on its own.
//
// f32 carries 24 mantissa bits and `exp` overflows near 88.7, so |k| <= 128 needs 8 of
// them: the leading pieces get 24 - 8 = 16 bits each and the tail takes the remainder.
// Verified exact for |k| <= 160. Worst-case reduction error 5.2e-17, against the ~3.6e-15
// that double-single needs.
//
// Widening these to "more accurate" full-precision values silently makes `exp` WORSE.
// It was previously ~21 bits per piece, which is inexact past about k = 16.
["0x1.62e4000000000p-1", "0x1.7f7e000000000p-20", "-0x1.c610ca0000000p-37"]);

impl_consts!(LOG f64 [
    ("0x1.d20ae03bcc153p-1", "-0x1.3a34bf2f1ab83p-55"),  // 1/ln(3)
    ("0x1.71547652b82fep-1", "0x1.777d0ffda0d24p-57"),  // 1/ln(4)
    ("0x1.3e1f9ccf97777p-1", "-0x1.db618df721f98p-55"),  // 1/ln(5)
    ("0x1.1dc0ad112ce3ep-1", "0x1.769f645267d4ap-55"),  // 1/ln(6)
    ("0x1.071daefbe4b4ap-1", "-0x1.9ea6c1f1794eep-55"),  // 1/ln(7)
    ("0x1.ec709dc3a03fdp-2", "0x1.d27f05548af0cp-56"),  // 1/ln(8)
    ("0x1.d20ae03bcc153p-2", "-0x1.3a34bf2f1ab83p-56"),  // 1/ln(9)
    ("0x1.bcb7b1526e50ep-2", "0x1.95355baaafad3p-57"),  // 1/ln(10)
    ("0x1.ab0a8a0a28c3ap-2", "0x1.b6455c79fed99p-56"),  // 1/ln(11)
    ("0x1.9c1681970c88fp-2", "0x1.e3221f6298af5p-59"),  // 1/ln(12)
    ("0x1.8f3a6860052a1p-2", "-0x1.afe7dc91a78f0p-56"),  // 1/ln(13)
    ("0x1.8404704437eabp-2", "0x1.ac5dd927e6112p-56"),  // 1/ln(14)
    ("0x1.7a21c022fb0a1p-2", "0x1.a9f5bd6a60428p-56"),  // 1/ln(15)
    ("0x1.71547652b82fep-2", "0x1.777d0ffda0d24p-58"),  // 1/ln(16)
    ("0x1.696d5483b0344p-2", "0x1.78ec9931dd399p-58"),  // 1/ln(17)
    ("0x1.62479987565dap-2", "0x1.2708bb7e5784cp-56"),  // 1/ln(18)
    ("0x1.5bc633f70001fp-2", "-0x1.1e2e054e1a1f4p-57"),  // 1/ln(19)
    ("0x1.55d1d1247e049p-2", "-0x1.09a5cb7ff50e7p-56"),  // 1/ln(20)
    ("0x1.50577cd41e7a0p-2", "-0x1.795d4f1c45fa7p-56"),  // 1/ln(21)
    ("0x1.4b47a28c18bfbp-2", "-0x1.a4ad57d5c1ac2p-58"),  // 1/ln(22)
    ("0x1.469552245a49dp-2", "-0x1.5b806338b1165p-59"),  // 1/ln(23)
    ("0x1.4235b39dbb506p-2", "0x1.15529d613d714p-56"),  // 1/ln(24)
    ("0x1.3e1f9ccf97777p-2", "-0x1.db618df721f98p-56"),  // 1/ln(25)
    ("0x1.3a4b3fb204cfep-2", "-0x1.431b7d1b937b5p-60"),  // 1/ln(26)
    ("0x1.36b1ead2880e2p-2", "-0x1.a2f0fee978f59p-57"),  // 1/ln(27)
    ("0x1.334dd75f8adeep-2", "-0x1.c3950ba6ceb12p-56"),  // 1/ln(28)
    ("0x1.301a017e282fcp-2", "0x1.dbdacfa0d9b0fp-57"),  // 1/ln(29)
    ("0x1.2d12088173e01p-2", "0x1.bffac2f932436p-57"),  // 1/ln(30)
    ("0x1.2a32153af765ep-2", "0x1.c22c8956209efp-56"),  // 1/ln(31)
    ("0x1.2776c50ef9bfep-2", "0x1.e4b29ccc535d4p-56"),  // 1/ln(32)
],
// LN_2_EXTENDED: Cody-Waite pieces. See the f32 table above for why these are narrow.
//
// f64 carries 53 mantissa bits and `exp` overflows near 709.8, so |k| <= 1024 needs 11
// of them: 53 - 11 = 42 bits per leading piece, tail takes the remainder. Verified exact
// for |k| <= 1100. Worst-case reduction error 2.9e-42, against the ~1.2e-32 that
// double-double needs.
//
// These were previously full-precision f64 values, which made every `k * piece` a rounded
// multiply and capped `exp` at about 50 bits (1.1e-15 relative at x = 29, growing with
// |k|). `ln` inherited that ceiling through its Halley step, and everything built on the
// pair (`powf`, the gamma family) inherited it in turn.
["0x1.62e42fefa3800p-1", "0x1.ef35793c76800p-45", "-0x1.9ff0342542fc3p-90"]);
