"""Extract the J/Y coefficient tables from Boost.Math and emit tables/bessel/jy.rs.

Transcribed by machine on purpose. There are thirty-four arrays and nineteen scalar constants
across the four headers, several near-identical between orders, and this project has already
paid for hand-typed reference values more than once. The script also asserts the structural
facts the Rust side relies on (numerator/denominator pairs match in length, the Hankel pair
matches, every expected array is present) so a Boost update that changes them fails loudly
rather than silently.

Boost keeps ONE coefficient set per function here, unlike I and K which it tiers by digit
count. f32 therefore shares f64's coefficients and simply evaluates a longer chain than it
strictly needs. The same values are emitted at both widths so the kernel stays generic.

Source: Boost.Math's J0/J1/Y0/Y1 rational approximations (BSL-1.0).
        Struct definitions live in tables/bessel/mod.rs, hand-written.
"""

import os
import re

from mpmath import mp

mp.dps = 60

HERE = os.path.dirname(__file__)
SRC = os.path.join(HERE, "..", "..", "..", "reference", "boost-math", "include", "boost",
                   "math", "special_functions", "detail")
OUT = os.path.join(HERE, "..", "src", "tables", "bessel_jy.rs")

BIG = re.compile(r"BOOST_MATH_BIG_CONSTANT\(\s*T\s*,\s*64\s*,\s*([^)]+?)\s*\)")
ARRAY = re.compile(r"const\s+T\s+(\w+)\[\s*\]\s*=\s*\{(.*?)\};", re.S)
SCALAR = re.compile(r"(\bx\d+)\s*=\s*static_cast<T>\(BOOST_MATH_BIG_CONSTANT\(\s*T\s*,\s*64\s*,\s*([^)]+?)\s*\)\)")

# name, header, arrays, how many small regions, region upper edges (None = J, fixed at 4 and 8)
FUNCS = [
    ("J0", "bessel_j0.hpp", ["P1", "Q1", "P2", "Q2", "PC", "QC", "PS", "QS"], 2, None),
    ("J1", "bessel_j1.hpp", ["P1", "Q1", "P2", "Q2", "PC", "QC", "PS", "QS"], 2, None),
    ("Y0", "bessel_y0.hpp", ["P1", "Q1", "P2", "Q2", "P3", "Q3", "PC", "QC", "PS", "QS"], 3, (3.0, 5.5)),
    ("Y1", "bessel_y1.hpp", ["P1", "Q1", "P2", "Q2", "PC", "QC", "PS", "QS"], 2, (4.0, 8.0)),
]


# Region-2 rationals re-expressed in the bounded variable u = 1 - x^2/64.
#
# Boost does this for `bessel_j0` and for none of the other three, which is measurable: real
# Boost, compiled and graded against mpmath over (4, 8], lands at 3.20 eps for `j0` and at
# 35.60 / 37.49 for `j1` / `y1`, whose region-2 argument `y = x^2` runs to 64 against
# coefficients reaching 1.7e18. In `u` the same rational's coefficients top out near 7.4e5.
#
# This is exact algebra on the published coefficients, `y = 64(1 - u)`, not a refit, so the
# function is unchanged and there is no approximation risk. Y0 is deliberately NOT in this set:
# it splits (0, 8] into three narrow regions instead, which bounds its argument a different way
# and measures 4.43.
SUBST_REGION2 = {"J1", "Y1"}


def subst_u(vals):
    """Constant-first coefficients in `y` -> the same polynomial in `u`, for y = 64(1 - u)."""
    n = len(vals)
    out = [mp.mpf(0)] * n
    for i, s in enumerate(vals):
        c = mp.mpf(s) * mp.mpf(64) ** i
        for k in range(i + 1):
            out[k] += c * mp.binomial(i, k) * (-1) ** k
    return out


def subst_region2(arrays):
    """Rewrite P2/Q2 in `u`, renormalized so the top denominator coefficient stays 1."""
    pu = subst_u(arrays["P2"])
    qu = subst_u(arrays["Q2"])
    s = qu[-1]
    assert s != 0, "denominator lost its leading term under substitution"
    arrays["P2"] = [mp.nstr(c / s, 20, strip_zeros=False) for c in pu]
    arrays["Q2"] = [mp.nstr(c / s, 20, strip_zeros=False) for c in qu]


def parse(fn):
    src = open(os.path.join(SRC, fn)).read()
    arrays = {}
    for m in ARRAY.finditer(src):
        vals = BIG.findall(m.group(2))
        if vals:
            arrays[m.group(1)] = vals
    return arrays, dict(SCALAR.findall(src))


def fmt(v, suffix):
    v = v.strip()
    if not ("e" in v or "E" in v or "." in v):
        v += ".0"
    return v + suffix


def main():
    with open(OUT, "w", newline="\n") as f:
        f.write("//! Coefficient tables for the oscillatory Bessel functions `J_0`, `J_1`,\n")
        f.write("//! `Y_0` and `Y_1`.\n//!\n")
        f.write("//! GENERATED by `scripts/bessel_jy_tables.py` from Boost.Math (BSL-1.0). Do not\n")
        f.write("//! hand-edit, re-run the script. The struct definitions are hand-written in\n")
        f.write("//! [`super`] and carry the explanation of what each field is for.\n//!\n")
        f.write("//! Every array is constant-term-first. Boost keeps one set per function here\n")
        f.write("//! rather than tiering by digit count as it does for `I` and `K`, so the f32 and\n")
        f.write("//! f64 tables hold the same values and f32 simply evaluates a longer chain than\n")
        f.write("//! it needs.\n\n")
        f.write("#![allow(clippy::excessive_precision)]\n\n")
        f.write("use super::{BesselJ, BesselY};\n")

        for tag, fn, want, nregions, edges in FUNCS:
            arrays, scalars = parse(fn)
            missing = [w for w in want if w not in arrays]
            assert not missing, f"{fn}: missing {missing}"
            for name in want:
                if name.startswith("Q"):
                    p = arrays["P" + name[1:]]
                    assert len(p) == len(arrays[name]), f"{fn}: {name}/P length mismatch"
            assert len(arrays["PC"]) == len(arrays["PS"]), f"{fn}: Hankel pair length mismatch"

            # Must run AFTER the length assertions, which check Boost's own arrays.
            if tag in SUBST_REGION2:
                subst_region2(arrays)

            is_j = tag.startswith("J")
            lens = [len(arrays["P1"]), len(arrays["P2"])]
            if not is_j:
                lens.append(len(arrays["P3"]) if nregions == 3 else len(arrays["P2"]))
            lens.append(len(arrays["PC"]))

            for suffix, ty in (("f32", "f32"), ("f64", "f64")):
                sfx = "_" + suffix if False else ""
                name = f"BESSEL_{tag}_{suffix.upper()}"
                kind = "BesselJ" if is_j else "BesselY"
                f.write(f"\n/// Boost.Math `bessel_{tag.lower()}` (BSL-1.0), as `{suffix}`.\n")
                f.write(f"pub const {name}: {kind}<{ty}, {', '.join(str(n) for n in lens)}> = {kind} {{\n")

                fields = [("p1", "P1"), ("q1", "Q1"), ("p2", "P2"), ("q2", "Q2")]
                if not is_j:
                    # Y1 has two regions and repeats the second so the kernel keeps one shape.
                    third = "P3" if nregions == 3 else "P2"
                    fields += [("p3", third), ("q3", "Q" + third[1:])]
                fields += [("pc", "PC"), ("qc", "QC"), ("ps", "PS"), ("qs", "QS")]

                for field, src_name in fields:
                    f.write(f"    {field}: [\n")
                    for v in arrays[src_name]:
                        f.write(f"        {fmt(v, ty)},\n")
                    f.write("    ],\n")

                nroots = 3 if (not is_j and nregions == 3) else 2
                for k in range(1, nroots + 1):
                    f.write(f"    root{k}: {fmt(scalars[f'x{k}'], ty)},\n")
                    f.write(f"    root{k}_hi: {fmt(scalars[f'x{k}1'], ty)},\n")
                    f.write(f"    root{k}_lo: {fmt(scalars[f'x{k}2'], ty)},\n")
                if not is_j:
                    if nregions == 2:
                        # Repeat region 2's root, and put the third threshold at region 2's
                        # own edge so it can never be selected.
                        f.write(f"    root3: {fmt(scalars['x2'], ty)},\n")
                        f.write(f"    root3_hi: {fmt(scalars['x21'], ty)},\n")
                        f.write(f"    root3_lo: {fmt(scalars['x22'], ty)},\n")
                    f.write(f"    threshold1: {edges[0]}{ty},\n")
                    f.write(f"    threshold2: {edges[1]}{ty},\n")
                f.write("};\n")

    print(f"wrote {os.path.normpath(OUT)}")
    for tag, fn, want, _, _ in FUNCS:
        arrays, scalars = parse(fn)
        print(f"  {tag}: " + ", ".join(f"{n}={len(arrays[n])}" for n in want))


if __name__ == "__main__":
    main()
