"""Reference table for the modified Bessel functions I_0 and I_1.

Writes tests/bessel_ref/table.rs. mpmath at 60 dps, rounded to f64 once.

The x-grid is chosen to hammer the seams rather than the easy middle: dense either
side of the 7.75 series/asymptotic handover, either side of the far-fit handover
(50 for f32, 500 for f64), and out past where the unscaled form overflows so the
scaled entry point is exercised where its twin cannot go.

The oracle is checked against its own defining series before anything is written:
a wrong reference table is worse than no table, and this one is cheap to verify.
"""

import os
from mpmath import mp, mpf, besseli, exp, factorial

mp.dps = 60

OUT = os.path.join(os.path.dirname(__file__), "..", "tests", "bessel_ref", "table.rs")


def grid():
    xs = []
    # Small-argument region, including where I_1 ~ x/2 dominates.
    xs += [mpf(0), mpf("1e-8"), mpf("1e-4"), mpf("0.001"), mpf("0.01"), mpf("0.1")]
    xs += [mpf(f"{v}") for v in ("0.25 0.5 0.75 1 1.5 2 2.5 3 4 5 6 7").split()]
    # The series/asymptotic seam at 7.75, from both sides and on it.
    xs += [mpf("7.7"), mpf("7.74"), mpf("7.749"), mpf("7.75"), mpf("7.751"), mpf("7.8")]
    xs += [mpf(f"{v}") for v in ("8 9 10 12 15 20 30 40 49").split()]
    # The f32 far seam at 50.
    xs += [mpf("49.9"), mpf("50"), mpf("50.1")]
    xs += [mpf(f"{v}") for v in ("60 80 100 150 200 300 400 499").split()]
    # The f64 far seam at 500.
    xs += [mpf("499.9"), mpf("500"), mpf("500.1")]
    # Past f64 overflow of the unscaled form (~713.99): scaled only.
    xs += [mpf(f"{v}") for v in ("600 700 713 720 800 1000 5000 1e6").split()]
    return xs


def check_oracle():
    """Independent check of mpmath's besseli against its defining series."""
    worst = mpf(0)
    for x in [mpf("0.5"), mpf(3), mpf("7.75"), mpf(12)]:
        for nu in (0, 1):
            s = mp.nsum(
                lambda k: (x / 2) ** (2 * k + nu) / (factorial(k) * factorial(k + nu)),
                [0, mp.inf],
            )
            ref = besseli(nu, x)
            worst = max(worst, abs(s - ref) / abs(ref))
    assert worst < mpf("1e-50"), f"oracle disagrees with its own series: {worst}"
    return worst


def main():
    worst = check_oracle()
    rows = []
    for x in grid():
        for nu in (0, 1):
            v = besseli(nu, x)
            sv = v * exp(-abs(x))
            # `float()` overflows to inf exactly where the f64 kernel must, which is the
            # behaviour the unscaled test asserts. The scaled column stays finite.
            fv = float(v)
            rows.append((nu, float(x), fv, float(sv)))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", newline="\n") as f:
        f.write("// Generated by scripts/bessel_ref.py (mpmath, 60 dps), rounded to f64 once.\n")
        f.write("// Do not hand-edit.\n")
        f.write(f"// Oracle cross-checked against the defining series to {float(worst):.2e} relative.\n\n")
        f.write("// (nu, x, I_nu(x), exp(-|x|) I_nu(x))\n")
        f.write("#[rustfmt::skip]\n")
        f.write(f"const BESSEL_I: [(u32, f64, f64, f64); {len(rows)}] = [\n")
        def lit(v):
            # `repr(inf)` is not Rust. Overflow is a real row here, not one to drop: it is
            # exactly what the unscaled form must do where the scaled form keeps working.
            return "f64::INFINITY" if v == float("inf") else repr(v)

        for nu, x, v, sv in rows:
            f.write(f"    ({nu}, {x!r}, {lit(v)}, {lit(sv)}),\n")
        f.write("];\n")
    print(f"wrote {len(rows)} rows to {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
