"""Reference `erfc(x)` on a dense grid, at 50 digits, for the tail-accuracy test.

Generates `tests/erfc_ref/table.rs`. The grid is dense where the kernel's error grows -
the far tail, where the rounding of `x*x` under the exp is amplified by `x^2` - and
covers both the f64 range (to 26, where erfc is still normal) and the f32 one (to 9).

    python scripts/erfc_ref.py
"""
import os

import numpy as np
from mpmath import mp, mpf, erfc

mp.dps = 50
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "tests", "erfc_ref", "table.rs")

# Offset the grids off the binary lattice: a step of 1/4 gives `x` whose square is exact
# in f64, which would hide the rounding of `x * x` under the exp, which is the tail's whole story.
xs = sorted(set(
    [float(v) + 0.0137 for v in np.linspace(0.0, 1.0, 21)]
    + [float(v) + 0.0137 for v in np.linspace(1.0, 6.0, 51)]
    + [float(v) + 0.0137 for v in np.linspace(6.0, 26.0, 81)]
    + [0.0, 0.84375, 0.85, 1.25, 8.9, 9.0, 9.2, 26.4]
))

# `mpf(x)` from the float is the exact binary value the kernel will see; `mpf(repr(x))`
# would be the decimal, and `erfc` at 9.2 differs from `erfc` at fl(9.2) by 60 ulp.
rows = [(x, float(erfc(mpf(x)))) for x in xs]
out = [
    "// Generated by scripts/erfc_ref.py (mpmath, 50 dps), rounded to f64 once. Do not edit.",
    "// (x, erfc(x))",
    "#[rustfmt::skip]",
    "#[allow(clippy::excessive_precision)]",
    f"const ERFC: [(f64, f64); {len(rows)}] = [",
]
for x, e in rows:
    out.append(f"    ({x!r}, {e!r}),")
out.append("];")
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", newline="\n") as f:
    f.write("\n".join(out) + "\n")
print("wrote", OUT, len(rows), "rows")
