"""Reference values for `fresnel` and `sici`, at 60 digits.

Generates `tests/fresnel_ref/table.rs` and `tests/sici_ref/table.rs`.

Rows are chosen for the places these two are hard rather than for a tidy sweep:

- both sides of each crossover, and the crossover itself;
- `Ci`'s first zero at x ~ 0.6165, where nothing is relatively accurate;
- the arguments where a naively computed Fresnel phase has already failed
  (98765.4321 is 5.3e-6 off, 9.876543e8 has the wrong sign), which is what makes
  the two-word reduction a regression test rather than a nicety;
- both cutoffs, from just under to just over.

Every x is emitted as an exact binary double, and every reference is mpmath
evaluated AT THAT DOUBLE - not at the decimal that produced it.

    python scripts/fresnel_sici_ref.py
"""

import os

from mpmath import mp, mpf

mp.dps = 60
HERE = os.path.dirname(os.path.abspath(__file__))

CUT64 = 1.147e16

FRESNEL_X = [
    0.0, 1e-30, 1e-8, 0.001, 0.1, 0.25, 0.5, 0.7511255444649425,  # C's inflection
    1.0, 1.5, 2.0, 2.4, 2.5264, 2.5265, 2.5266, 2.6, 3.0, 4.0, 5.0, 7.0,
    10.0, 25.0, 100.0, 123.4567, 1234.5678, 98765.4321, 1e6,
    9.876543e8, 3.14159e11, 7.7e14, 1e15, 1.1e16, CUT64, 1.2e16, 1e20, 1e30,
]

SICI_X = [
    0.0, 1e-30, 1e-8, 0.001, 0.1, 0.3, 0.6165054856207162,  # Ci's first zero
    1.0, 2.0, 3.0, 5.0, 8.0, 11.9, 12.0, 12.1, 13.0, 15.0, 20.0, 30.0,
    50.0, 100.0, 1000.0, 98765.4321, 1e6, 9.876543e8, 7.7e14, 1e15,
    1.1e16, CUT64, 1.2e16, 1e20,
]


def ci_envelope(x, x0):
    """The scale `Ci` can actually be accurate to at `x`.

    `Ci` has zeros (0.6165, 3.384, 6.427, ...) and nothing is relatively accurate at
    one, so it is graded against the magnitudes the kernel combines. Below the
    crossover that is `|gamma + ln x| + |Cin|`, and the cancellation between them is
    real: at x = 11.9 they are both about 2.7 while `Ci` is -0.057, so 50x of the
    result's relative accuracy is gone before any coefficient is consulted. Above the
    crossover the value IS the oscillation, of size `|f| + |g| ~ 1/x`."""
    if x == 0:
        return mpf(1)
    xm = mpf(x)
    # `>`, not `>=`: the kernel's test is `|x| <= x0`, so the crossover itself is the
    # last point on the small branch and takes the cancellation envelope.
    if xm > x0:
        return max(abs(mp.ci(xm)), 1 / xm)
    return abs(mp.euler + mp.log(xm)) + abs(mp.euler + mp.log(xm) - mp.ci(xm))


def rows(xs, fns, as_f32=False):
    """Rows anchored at the exact binary value the kernel will see.

    The f32 table is NOT the f64 table read at lower precision: rounding x to f32
    first moves the argument by up to x*eps32, and dC/dx is O(1), so a reference
    taken at the f64 x charges the f32 kernel x ulps for its own input. At
    x = 1e6 that is a million."""
    import struct

    out = []
    seen = set()
    for x in xs:
        v = struct.unpack("f", struct.pack("f", float(x)))[0] if as_f32 else float(x)
        if v in seen or not (abs(v) < float("inf")):
            continue
        seen.add(v)
        out.append((v, *[float(f(mpf(v))) for f in fns]))
    return out


def rows_with_envelope(xs, fns, x0, as_f32=False):
    return [r + (float(ci_envelope(r[0], x0)),) for r in rows(xs, fns, as_f32)]


def rust_f64(v):
    """`repr` gives `inf`/`-inf`/`nan`, none of which are Rust literals."""
    if v != v:
        return "f64::NAN"
    if v == float("inf"):
        return "f64::INFINITY"
    if v == float("-inf"):
        return "f64::NEG_INFINITY"
    return repr(v)


def emit(path, cols, ty, tables):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="\n") as fh:
        fh.write("// Generated by scripts/fresnel_sici_ref.py (mpmath, 60 dps). Do not edit.\n")
        fh.write(f"// {cols}\n")
        fh.write("//\n// `REFS_F32` repeats the same arguments ROUNDED TO f32 FIRST, with the\n")
        fh.write("// references taken there: the f64 rows would otherwise charge the f32 kernel\n")
        fh.write("// for its own argument rounding, which is about x ulps (dC/dx is O(1), so\n")
        fh.write("// moving x by x*eps32 moves C by the same: a million ulp at x = 1e6).\n")
        for name, data in tables:
            fh.write("#[rustfmt::skip]\n#[allow(clippy::excessive_precision, dead_code)]\n")
            fh.write(f"const {name}: [{ty}; {len(data)}] = [\n")
            for row in data:
                fh.write("    (" + ", ".join(rust_f64(v) for v in row) + "),\n")
            fh.write("];\n")
        print(f"wrote {path} ({', '.join(f'{n} {len(d)}' for n, d in tables)})")


def main():
    fres = [mp.fresnelc, mp.fresnels]
    sici = [mp.si, lambda x: mp.ci(x) if x > 0 else mpf("-inf")]
    emit(
        os.path.join(HERE, "..", "tests", "fresnel_ref", "table.rs"),
        "(x, C(x), S(x))", "(f64, f64, f64)",
        [("REFS", rows(FRESNEL_X, fres)),
         ("REFS_F32", rows([x for x in FRESNEL_X if x <= 3.4e38], fres, as_f32=True))],
    )
    # The fourth column is the scale Ci can be accurate to. The crossover it is keyed
    # to differs by precision (12 in f64, 6 in f32), which is why the two tables carry
    # their own.
    emit(
        os.path.join(HERE, "..", "tests", "sici_ref", "table.rs"),
        "(x, Si(x), Ci(x), Ci envelope)", "(f64, f64, f64, f64)",
        [("REFS", rows_with_envelope(SICI_X, sici, mpf(12))),
         ("REFS_F32", rows_with_envelope([x for x in SICI_X if x <= 3.4e38], sici, mpf(6), as_f32=True))],
    )


if __name__ == "__main__":
    main()
