"""Reference values for the Newton inverses: `inv_log_ndtr`, `inv_digamma`, `wright_omega`.

Generates `tests/inverses_ref/table.rs`. Every row is `(y, x)` with `x` the exact inverse
of the f64 value `y` (found by `findroot` at 50 digits from the forward, never from any
seed the kernels use), so a test compares the kernel to the true inverse of the argument
it was actually given.

    python scripts/inverses_ref.py
"""
import os

from mpmath import mp, mpf, exp, log, ncdf, digamma, lambertw, findroot, sqrt, pi

mp.dps = 50
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "tests", "inverses_ref", "table.rs")


def log_ndtr(x):
    x = mpf(x)
    # right side through the complement so 50 digits are not wasted on the 1
    if x > 0:
        return log(1 - ncdf(-x))
    return log(ncdf(x))


def inv_log_ndtr_rows():
    xs = [-1e6, -1e4, -1000.0, -300.0, -100.0, -40.0, -38.0, -30.0, -20.0, -10.0, -6.0, -4.0,
          -3.0, -2.0, -1.0, -0.5, -0.1, -1e-3, 0.0, 1e-3, 0.5, 1.0, 2.0, 4.0, 6.0, 8.0]
    rows = []
    for x0 in xs:
        y = float(log_ndtr(x0))            # the f64 argument the kernel sees
        if y == 0.0:
            continue
        ym = mpf(y)
        # inverse of the ROUNDED y: newton from x0 at 50 digits
        x = findroot(lambda t: log_ndtr(t) - ym, mpf(x0))
        rows.append((y, float(x)))
    return rows


def inv_digamma_rows():
    xs = [1e-6, 1e-3, 0.01, 0.1, 0.25, 0.5, 1.0, 1.4616321449683623, 2.0, 5.0, 10.0, 19.0,
          21.0, 25.0, 60.0, 100.0, 250.0, 500.0, 1000.0, 5000.0, 1e4, 1e8, 1e15]
    rows = []
    for x0 in xs:
        y = float(digamma(mpf(x0)))
        ym = mpf(y)
        x = findroot(lambda t: digamma(t) - ym, mpf(x0))
        rows.append((y, float(x)))
    return rows


def wright_omega_rows():
    xs = [-745.0, -700.0, -100.0, -20.0, -5.0, -2.0, -1.0, -0.5, 0.0, 0.5, 1.0, 2.0, 5.0,
          20.0, 100.0, 1e4, 1e8, 1e15, 1e100, 1e300]
    rows = []
    for x0 in xs:
        xm = mpf(x0)
        if x0 < 700:
            w = lambertw(exp(xm))
        else:
            w = findroot(lambda t: t + log(t) - xm, xm - log(xm))
        rows.append((x0, float(w)))
    return rows


def emit(name, rows, comment):
    out = [f"// ({comment})", "#[rustfmt::skip]", "#[allow(clippy::excessive_precision, clippy::approx_constant)]",
           f"const {name}: [(f64, f64); {len(rows)}] = ["]
    out += [f"    ({a!r}, {b!r})," for a, b in rows]
    out.append("];")
    return out


out = ["// Generated by scripts/inverses_ref.py (mpmath, 50 dps). Do not edit.", ""]
out += emit("INV_LOG_NDTR", inv_log_ndtr_rows(), "y = log_ndtr(x) as f64, exact inverse of that y")
out.append("")
out += emit("INV_DIGAMMA", inv_digamma_rows(), "y = digamma(x) as f64, exact inverse of that y")
out.append("")
out += emit("WRIGHT_OMEGA", wright_omega_rows(), "x, omega(x)")
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", newline="\n") as f:
    f.write("\n".join(out) + "\n")
print("wrote", OUT)
