"""mpmath oracle for tests/langevin.rs. Writes tests/langevin_ref/table.rs (an include! table).

Forward: L(x) = coth(x) - 1/x at 120 dps. Inverse: findroot, not the implementation's
own formula. Values are printed at full f64 width; f32 tests round the f64 reference.
"""
import mpmath as mp
mp.mp.dps = 120
L = lambda x: mp.coth(x) - 1/x
def Linv(y):
    if y == 0: return mp.mpf(0)
    return mp.findroot(lambda x: L(x) - y, y*(3-y*y)/(1-y*y), tol=mp.mpf(10)**-45)
def dL(x): return 1/(x*x) - 1/mp.sinh(x)**2

xs = [mp.mpf(2)**-k for k in range(60, 0, -4)]                       # deep small-x
xs += [mp.mpf(k)/64 for k in range(1, 4*64)]                          # (0, 4] dense, straddles 2
xs += [mp.mpf(1)/1024 + mp.mpf(k)/1000 * 2 for k in range(1, 100)]    # non-dyadic near 2 (crossover)
xs += [mp.mpf(k) for k in [5, 8, 12, 17, 20, 25, 30, 44, 50, 88, 100, 200, 1e3, 1e5, 1e8, 1e12, 1e16]]
ys = [mp.mpf(k)/1000 for k in range(1, 1000)]                         # (0, 1)
ys += [1 - mp.mpf(2)**-k for k in range(2, 53)]                       # pole sweep to f64's limit
ys += [mp.mpf('0.85') + mp.mpf(k)*mp.mpf(10)**-4 for k in range(-20, 21)]  # seed crossover

# The reference is at the f64 the test can actually feed in, not at the exact
# rational. The inverse's condition number is 1/(1-y), so rounding y first matters.
xs = [mp.mpf(float(x)) for x in xs]
ys = [mp.mpf(float(y)) for y in ys]

def f(v): return repr(float(v))
with open('crates/thermite-special/tests/langevin_ref/table.rs', 'w') as o:
    o.write("// Generated by scripts/langevin_oracle.py (mpmath, 120 dps). Do not edit.\n")
    o.write("// (x, L(x), L'(x))\n#[rustfmt::skip]\nconst FORWARD: &[(f64, f64, f64)] = &[\n")
    for x in xs: o.write(f"    ({f(x)}, {f(L(x))}, {f(dL(x))}),\n")
    o.write("];\n// (y, L^-1(y), L'(L^-1(y)))\n#[rustfmt::skip]\nconst INVERSE: &[(f64, f64, f64)] = &[\n")
    for y in ys:
        x = Linv(y)
        o.write(f"    ({f(y)}, {f(x)}, {f(dL(x))}),\n")
    o.write("];\n")
print(len(xs), len(ys))

# --- complement pair: (x, 1 - L(x)) deep into the tail, and (t, L^-1(1 - t)) at tiny t
xs1m = [mp.mpf(float(v)) for v in [0.5, 1, 1.9, 2, 2.1, 3, 5, 10, 20, 50, 1e2, 1e3, 1e4, 1e5, 1e6, 1e7, 1e8, 1e10, 1e12, 1e15, 1e18]]
ts = [mp.mpf(2)**-k for k in range(1, 61)] + [mp.mpf(float(v)) for v in [0.13, 0.14, 0.15, 0.16, 0.17, 0.3, 0.5, 0.9, 1.0, 1.5]]
def Linv_t(t):  # L^-1(1 - t), root-found in the complement so the tail is exact
    if t >= 1: return Linv(1 - t)
    return mp.findroot(lambda x: (1/x - 2/mp.expm1(2*x)) - t if x > 1 else L(x) - (1 - t), 1/t)
with open('crates/thermite-special/tests/langevin_ref/table.rs', 'a') as o:
    o.write("// (x, 1 - L(x))\n#[rustfmt::skip]\nconst FORWARD_1M: &[(f64, f64)] = &[\n")
    for x in xs1m: o.write(f"    ({f(x)}, {f(1 - L(x))}),\n")
    o.write("];\n// (t, L^-1(1 - t))\n#[rustfmt::skip]\nconst INVERSE_1M: &[(f64, f64)] = &[\n")
    for t in ts: o.write(f"    ({f(t)}, {f(Linv_t(t))}),\n")
    o.write("];\n")
