"""Reference values for `ndtr`, `log_ndtr` and `logerfc`, at 60 digits.

Generates `tests/ndtr_ref/table.rs`. The rows are chosen for the two places the naive
spellings fail: the far left tail, where `ndtr` itself has underflowed and only the log
form carries information, and the region just right of zero, where `ln(1 - small)`
needs `ln_1p`.

Also runs the f64 model of the kernels (scipy's `erfcx`, numpy's `log1p`/`exp`) against
the oracle and prints the worst error in ulps, so a design change can be checked here
before it is written in Rust.

    python scripts/ndtr_ref.py
"""
import os

import numpy as np
from mpmath import mp, mpf, erfc, log, log1p, sqrt
from scipy.special import erfcx as sp_erfcx

mp.dps = 60
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "tests", "ndtr_ref", "table.rs")


def f64(v):
    return repr(float(v))


def ndtr(x):
    return erfc(-x / sqrt(2)) / 2


def log_ndtr(x):
    # On the right, ndtr -> 1 and even 60 digits lose the complement (erfc(-13)/2 rounds to
    # exactly 1), so take the log of the small side directly.
    if x > 0:
        return log1p(-erfc(x / sqrt(2)) / 2)
    return log(ndtr(x))


def logerfc(x):
    # Same on the left, where erfc(x) = 1 + erf(|x|) and erf(|x|) may be 1e-20.
    if x < 0:
        return log1p(-erfc(-x) + 1)
    return log(erfc(x))


XS = [
    -1.3e154, -1e100, -1e20, -1e10, -1e6, -1000.0, -100.0, -40.0, -38.5, -37.0, -30.0,
    -26.0, -20.0, -13.0, -10.0, -8.0, -5.0, -3.0, -2.0, -1.0, -0.75, -0.5, -0.25, -0.1,
    -1e-3, -1e-8, -1e-20, 0.0, 1e-20, 1e-8, 1e-3, 0.1, 0.25, 0.5, 0.75, 1.0, 2.0, 3.0,
    5.0, 8.0, 10.0, 13.0, 20.0, 26.0, 30.0, 37.0, 38.5, 40.0, 100.0, 1000.0, 1e6, 1e10,
    1e20, 1e100, 1.3e154,
]


def lit(v):
    if v == mpf("-inf"):
        return "f64::NEG_INFINITY"
    if v == mpf("inf"):
        return "f64::INFINITY"
    return f64(v)


rows = []
for x in XS:
    # The exact binary value the kernel sees, not the decimal: the tail's derivative turns a
    # 1e-16 difference in x into tens of ulp.
    xm = mpf(x)
    n = ndtr(xm)
    ln = log_ndtr(xm)
    # logerfc(x) for x > ~1.3e154 is below -MAX; mpmath is happy, f64 is not.
    le = logerfc(xm)
    rows.append((x, n, ln, le))

out = [
    "// Generated by scripts/ndtr_ref.py (mpmath, 60 dps), rounded to f64 once. Do not edit.",
    "// (x, ndtr(x), log_ndtr(x), logerfc(x))",
    "#[rustfmt::skip]",
    "// `logerfc(-x)` is `ln 2` at every row past `x = 6`, which clippy reads as a spelled-out constant.",
    "#[allow(clippy::excessive_precision, clippy::approx_constant)]",
    f"const REFS: [(f64, f64, f64, f64); {len(rows)}] = [",
]
for x, n, ln, le in rows:
    out.append(f"    ({f64(x)}, {lit(n)}, {lit(ln)}, {lit(le)}),")
out.append("];")
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", newline="\n") as f:
    f.write("\n".join(out) + "\n")
print("wrote", OUT, len(rows), "rows")


# ---- f64 model of the kernels ------------------------------------------------------

EPS = np.finfo(np.float64).eps
SEAM = float(os.environ.get("SEAM", "0.5"))


def model_log_ndtr(x):
    ax = abs(x)
    u = ax * (1 / np.sqrt(2.0))
    u2 = (ax * 0.5) * ax
    a = sp_erfcx(u) * 0.5
    if x < 0:
        # a - 1 rounds to exactly -1 once a < 2^-54 (x < -7e15), so clamp to keep ln_1p
        # finite. The ln term is ~-40 against a result of -u^2 < -2.5e31 there.
        return np.log1p(max(a - 1.0, EPS - 1.0)) - u2
    return np.log1p(-(a * np.exp(-u2)))


def model_logerfc(x):
    from scipy.special import erf as sp_erf
    ax = abs(x)
    if x < 0:
        return np.log1p(sp_erf(ax))
    if ax < SEAM:
        # erfcx(x) - 1 cancels for small x, while ln(1 - erf(x)) does not.
        return np.log1p(-sp_erf(ax))
    c = sp_erfcx(ax)
    return np.log1p(c - 1.0) - ax * ax


def ulps(got, want):
    want_f = float(want)
    if got == want_f:
        return 0.0
    if not np.isfinite(got) or not np.isfinite(want_f):
        return float("inf")
    return abs(got - want_f) / (np.spacing(abs(want_f)))


grid = np.concatenate([
    -np.logspace(-20, 2.1, 400),   # -1e-20 .. -125
    np.logspace(-20, 2.1, 400),
    -np.logspace(2.1, 150, 50),
])
REGIONS = [("x < -1", lambda x: x < -1), ("-1..0", lambda x: -1 <= x < 0), ("0..0.25", lambda x: 0 <= x < 0.25),
           ("0.25..0.5", lambda x: 0.25 <= x < 0.5), ("0.5..1", lambda x: 0.5 <= x < 1), ("1..2", lambda x: 1 <= x < 2),
           ("x >= 2", lambda x: x >= 2)]
for name, model, oracle in (("log_ndtr", model_log_ndtr, log_ndtr), ("logerfc", model_logerfc, logerfc)):
    worst = {r: (0.0, None) for r, _ in REGIONS}
    for x in grid:
        got = model(float(x))
        want = oracle(mpf(float(x)))
        u = ulps(got, want)
        for r, pred in REGIONS:
            if pred(x) and u > worst[r][0]:
                worst[r] = (u, float(x))
    print(f"model {name} (seam {SEAM}):")
    for r, _ in REGIONS:
        print(f"    {r:>10}: worst {worst[r][0]:8.2f} ulp at x = {worst[r][1]!r}")
