"""Reference values for the orthonormal Hermite and Laguerre functions.

    python crates/thermite-special/scripts/orthonormal_ref.py

Writes crates/thermite-special/tests/{hermite,laguerre}_ref/table.rs. Everything is
mpmath at 50 digits, rounded to f64 once at print time; the x grid is dyadic so the
arguments themselves are exact.

The point of these tables, over the exact-rational ones in legendre_ref.py, is the
high-degree rows: raw H_n and L_n overflow long before the degrees sampled here, so
these values cannot be reproduced from the raw kernels at all.
"""

import os

from mpmath import mp, mpf, sqrt, exp, gamma, factorial, hermite, pi

mp.dps = 50

HERE = os.path.dirname(os.path.abspath(__file__))
TESTS = os.path.join(HERE, "..", "tests")


def f64(v):
    v = float(v)
    if v != v:
        return "f64::NAN"
    if v == float("inf"):
        return "f64::INFINITY"
    if v == float("-inf"):
        return "f64::NEG_INFINITY"
    return repr(v)


def psi(n, x):
    """Orthonormal Hermite function."""
    x = mpf(x)
    return hermite(n, x) * exp(-x * x / 2) / sqrt(2**n * factorial(n) * sqrt(pi))


def laguerre_rec(n, a, x):
    """L_n^{(a)}(x) by the three-term recurrence at high working precision.

    mpmath's `laguerre` goes through a hypergeometric sum that fails to converge for the
    high-degree, large-x rows below; the recurrence at 400 digits has no such trouble and
    the cancellation it suffers is far below that.
    """
    with mp.workdps(400):
        if n == 0:
            return mpf(1)
        p0, p1 = mpf(1), 1 + a - x
        for k in range(1, n):
            p0, p1 = p1, ((2 * k + a + 1 - x) * p1 - (k + a) * p0) / (k + 1)
        return +p1


def lag_fn(n, a, x):
    """Orthonormal generalized Laguerre function."""
    x, a = mpf(x), mpf(a)
    with mp.workdps(400):
        v = sqrt(factorial(n) / gamma(n + a + 1)) * x ** (a / 2) * exp(-x / 2) * laguerre_rec(n, a, x)
    return +v


def write(path, body):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(body)
    print("wrote", os.path.relpath(path, os.path.join(HERE, "..", "..", "..")))


def hermite_table():
    xs = [mpf(0), mpf(1) / 4, mpf(1) / 2, mpf(1), mpf(3) / 2, mpf(5) / 2, mpf(4), mpf(6), mpf(17) / 2, -mpf(3) / 4, -mpf(7) / 2]
    degrees = list(range(0, 13))

    # High degree, chosen to sit inside, at and past the turning point sqrt(2n+1), and past
    # every degree at which the raw polynomial is still finite in either format.
    spots = [
        (50, mpf(0)), (50, mpf(5)), (50, mpf(10)), (50, mpf(12)),
        (100, mpf(0)), (100, mpf(7)), (100, mpf(14)), (100, mpf(16)),
        (150, mpf(0)), (150, mpf(10)), (150, mpf(17)), (150, mpf(19)),
        (300, mpf(0)), (300, mpf(20)), (300, mpf(24)),
        (1000, mpf(0)), (1000, mpf(30)), (1000, mpf(44)), (1000, mpf(47)),
    ]

    # Seed-stress rows. Every x above is an integer, whose square is exact, so the
    # Best-tier residual on x^2 is identically zero there. These are the f64 nearest to
    # full-mantissa decimals: `mpf(float(...))` is the exact binary value, so the reference
    # is at precisely the argument the kernel receives, and x*x rounds by up to half an ulp
    # of x^2, i.e. up to ~x^2/4 * eps of relative error in the seed for the residual to
    # recover. (An earlier attempt used x = integer + 2^-30, whose square has a residual
    # of 2^-60 - exact for all practical purposes. Not a stress at all.)
    spots += [
        (150, mpf(float("10.3"))),
        (300, mpf(float("20.7"))),
        (1000, mpf(float("30.3"))),
        (1000, mpf(float("44.6"))),
        (1000, mpf(float("38.9"))),
    ]

    out = []
    out.append("// Generated by scripts/orthonormal_ref.py (mpmath, 50 dps), rounded to f64 once.")
    out.append("// Do not hand-edit.")
    out.append("")
    out.append(f"const HF_XS: [f64; {len(xs)}] = [" + ", ".join(f64(x) for x in xs) + "];")
    out.append("")
    out.append("// psi_n(x) for n = 0..=12 down the rows, HF_XS across.")
    out.append("#[rustfmt::skip]")
    out.append(f"const HF: [[f64; {len(xs)}]; {len(degrees)}] = [")
    for n in degrees:
        out.append("    [" + ", ".join(f64(psi(n, x)) for x in xs) + "],")
    out.append("];")
    out.append("")
    out.append("// (n, x, psi_n(x)) at degrees the raw polynomial cannot reach.")
    out.append("#[rustfmt::skip]")
    out.append(f"const HF_HIGH: [(usize, f64, f64); {len(spots)}] = [")
    for n, x in spots:
        out.append(f"    ({n}, {f64(x)}, {f64(psi(n, x))}),")
    out.append("];")
    out.append("")
    write(os.path.join(TESTS, "hermite_ref", "table.rs"), "\n".join(out))


def laguerre_table():
    xs = [mpf(0), mpf(1) / 4, mpf(1), mpf(5) / 2, mpf(5), mpf(10), mpf(20), mpf(35)]
    alphas = [mpf(0), mpf(1) / 2, mpf(1), mpf(2), -mpf(1) / 2]
    degrees = list(range(0, 9))

    # Turning point of l_n^a is near 4n, so sample inside, near and beyond, at degrees past
    # where raw L_n overflows in f32 (its L_n(0) is 1 but |L_n(x)| ~ x^n/n! elsewhere).
    spots = [
        (40, mpf(0), mpf(50)), (40, mpf(0), mpf(120)), (40, mpf(0), mpf(200)),
        (40, mpf(1), mpf(80)), (40, mpf(1) / 2, mpf(160)),
        (80, mpf(0), mpf(100)), (80, mpf(0), mpf(250)), (80, mpf(0), mpf(330)),
        (80, mpf(2), mpf(300)),
        (300, mpf(0), mpf(500)), (300, mpf(0), mpf(1100)),
        (600, mpf(0), mpf(1000)), (600, mpf(0), mpf(2300)),
    ]

    # Large-alpha rows, near the peak of the weight x^a e^{-x}. These are the ones that
    # catch a seed built as the product x^{a/2} * (1/sqrt(Gamma(a+1))): separately those
    # factors overflow near a = 250 and underflow near a = 320, so their overlap is
    # inf * 0 = NaN even though l_n^{(a)} there is a perfectly ordinary O(1) number.
    spots += [
        (0, mpf(250), mpf(250)),
        (0, mpf(300), mpf(300)),
        (0, mpf(400), mpf(400)),
        (0, mpf(600), mpf(600)),
        (3, mpf(400), mpf(420)),
        (8, mpf(600), mpf(640)),
    ]

    out = []
    out.append("// Generated by scripts/orthonormal_ref.py (mpmath, 50 dps), rounded to f64 once.")
    out.append("// Do not hand-edit.")
    out.append("")
    out.append(f"const LF_XS: [f64; {len(xs)}] = [" + ", ".join(f64(x) for x in xs) + "];")
    out.append(f"const LF_ALPHAS: [f64; {len(alphas)}] = [" + ", ".join(f64(a) for a in alphas) + "];")
    out.append("")
    out.append("// l_n^{(alpha)}(x): [alpha][n][x].")
    out.append("#[rustfmt::skip]")
    out.append(f"const LF: [[[f64; {len(xs)}]; {len(degrees)}]; {len(alphas)}] = [")
    for a in alphas:
        out.append("    [")
        for n in degrees:
            out.append("        [" + ", ".join(f64(lag_fn(n, a, x)) for x in xs) + "],")
        out.append("    ],")
    out.append("];")
    out.append("")
    out.append("// (n, alpha, x, l_n^{(alpha)}(x)) at degrees and arguments the raw polynomial cannot reach.")
    out.append("#[rustfmt::skip]")
    out.append(f"const LF_HIGH: [(usize, f64, f64, f64); {len(spots)}] = [")
    for n, a, x in spots:
        out.append(f"    ({n}, {f64(a)}, {f64(x)}, {f64(lag_fn(n, a, x))}),")
    out.append("];")

    # The seed alone, l_0^{(a)}(x) = sqrt(x^a e^{-x} / Gamma(a+1)), across the branch
    # structure of the kernel: small-Gamma weights, the saddle-point weights (integer and
    # not), and x from well below the peak x = a to well above it. Rows where the value
    # would underflow binary64, or x is past the exp range, are dropped.
    seed_alphas = [mpf(3) / 2, mpf(11) / 2, mpf(17) / 2, mpf(9), mpf(19) / 2, mpf(49) / 4,
                   mpf(61) / 2, mpf(100), mpf(201) / 2, mpf(400), mpf(1000), mpf(1400)]
    seed_ratios = [mpf(1) / 2, mpf(4) / 5, mpf(9) / 10, mpf(1), mpf(21) / 20, mpf(6) / 5, mpf(3) / 2, mpf(5) / 2]
    seed_rows = []
    for a in seed_alphas:
        for r in seed_ratios:
            x = a * r
            if x > 2800:
                continue
            v = lag_fn(0, a, x)
            if abs(v) < mpf(10) ** -290:
                continue
            seed_rows.append((a, x, v))
    out.append("")
    out.append("// (alpha, x, l_0^{(alpha)}(x)): the seed alone, across its branches and the peak.")
    out.append("#[rustfmt::skip]")
    out.append(f"const LF_SEED: [(f64, f64, f64); {len(seed_rows)}] = [")
    for a, x, v in seed_rows:
        out.append(f"    ({f64(a)}, {f64(x)}, {f64(v)}),")
    out.append("];")
    out.append("")
    write(os.path.join(TESTS, "laguerre_ref", "table.rs"), "\n".join(out))


if __name__ == "__main__":
    hermite_table()
    laguerre_table()
