"""Reference Poisson masses for tests/poisson.rs.

Writes crates/thermite-special/tests/poisson_ref/table.rs: (k, lambda, pmf, log pmf) at
integer and real k across the kernel's branches (k < 9 plain, k >= 9 saddle-point) and
lambda from far below the peak k to far above it. mpmath at 50 digits, rounded once.
"""
import os
from mpmath import mp, mpf, exp, log, gamma

mp.dps = 50
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "tests", "poisson_ref", "table.rs")


def f64(v):
    return repr(float(v))


def pmf(k, lam):
    if lam == 0:
        return mpf(1) if k == 0 else mpf(0)
    return lam ** k * exp(-lam) / gamma(k + 1)


ks = [mpf(0), mpf(1), mpf(3), mpf(17) / 2, mpf(9), mpf(19) / 2, mpf(20), mpf(100), mpf(201) / 2, mpf(1000), mpf(5000)]
ratios = [mpf(0), mpf(1) / 4, mpf(1) / 2, mpf(4) / 5, mpf(9) / 10, mpf(1), mpf(21) / 20, mpf(6) / 5, mpf(3) / 2, mpf(3)]
rows = []
for k in ks:
    for r in ratios:
        lam = k * r if k > 0 else r * 4  # k = 0: lambda in 0..12
        p = pmf(k, lam)
        if p != 0 and abs(p) < mpf(10) ** -290:
            continue
        lp = log(p) if p != 0 else mpf("-inf")
        rows.append((k, lam, p, lp))

out = ["// Generated by scripts/poisson_ref.py (mpmath, 50 dps), rounded to f64 once.", "// Do not hand-edit.", "",
       "// (k, lambda, pmf, ln pmf)", "#[rustfmt::skip]", f"const POIS: [(f64, f64, f64, f64); {len(rows)}] = ["]
for k, lam, p, lp in rows:
    lps = "f64::NEG_INFINITY" if lp == mpf("-inf") else f64(lp)
    out.append(f"    ({f64(k)}, {f64(lam)}, {f64(p)}, {lps}),")
out.append("];")
with open(OUT, "w", newline="\n") as f:
    f.write("\n".join(out) + "\n")
print("wrote", OUT, len(rows), "rows")
