"""Reference polygamma values for tests/polygamma.rs.

Writes crates/thermite-special/tests/polygamma_ref/table.rs: (n, x, psi_n(x)) rows for
n >= 2 (n = 0, 1 are digamma/trigamma, tested elsewhere) at positive x spanning the
kernel's regions: below 1, the recurrence range, straddling the transition threshold
N = 0.4*digits10 + 4n, and far into the asymptotic tail. mpmath at 50 digits, rounded
once. Rows whose value overflows or underflows binary64 are skipped. The overflow
behavior is covered by dedicated tests, not the sweep.
"""
import os
from mpmath import mp, mpf, polygamma, factorial

mp.dps = 50
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "tests", "polygamma_ref", "table.rs")

# Sanity-check the recurrence identity the tests also use:
#   psi_n(x + 1) = psi_n(x) + (-1)^n n! x^-(n+1)
for (n, x) in [(2, mpf("0.7")), (5, mpf("3.25")), (10, mpf("1.5"))]:
    lhs = polygamma(n, x + 1)
    rhs = polygamma(n, x) + (-1) ** n * factorial(n) * x ** (-(n + 1))
    assert abs(lhs - rhs) <= abs(lhs) * mpf(10) ** -45, (n, x)

ns = [2, 3, 4, 5, 6, 8, 10, 12, 16, 20, 30, 50, 100, 150]
xs = [mpf(v) for v in [
    "0.05", "0.1", "0.25", "0.5", "0.75", "0.9", "1.0", "1.25", "1.5", "2.0",
    "2.5", "3.5", "5.0", "6.5", "8.0", "10.0", "14.0", "20.0", "35.0", "50.0",
    "75.0", "100.0", "250.0", "1000.0", "10000.0", "1000000.0",
]]

# Negative arguments exercise the reflection (implemented for n <= 20, the cot-pi
# table's reach). Quarter offsets are exact in f32 too. The -0.5 column sits exactly
# where the cot polynomial's terms vanish, and near-integer offsets approach the poles.
xs_neg = [mpf(v) for v in [
    "-0.25", "-0.5", "-0.75", "-1.25", "-1.5", "-2.25", "-3.5", "-4.75", "-6.5",
    "-9.25", "-12.5", "-20.75", "-33.25", "-50.5", "-100.25", "-1000.5",
    "-2.03125", "-2.96875", "-7.984375",
]]

import math

rows = []
for n in ns:
    for x in xs + (xs_neg if n <= 20 else []):
        # mpmath reaches negative arguments through Hurwitz zeta, whose direct sum
        # cancels ~ (n+1) log10(1-x) digits down to the tiny reflected value (at
        # x = -1000.5 the even-n cot term vanishes exactly and psi_n collapses to
        # psi_n(1001.5) ~ 1e-43 out of ~1e24 intermediates). Scale the working
        # precision with the cancellation or the table records oracle noise.
        mp.dps = 50 + (0 if x > 0 else int((n + 1) * math.log10(float(1 - x))) + 15)
        v = polygamma(n, x)
        mp.dps = 50
        if abs(v) > mpf(10) ** 290 or (v != 0 and abs(v) < mpf(10) ** -290):
            continue
        rows.append((n, x, v))

out = [
    "// Generated by scripts/polygamma_ref.py (mpmath, 50 dps), rounded to f64 once.",
    "// Do not hand-edit.",
    "",
    "// (n, x, psi_n(x))",
    "#[rustfmt::skip]",
    f"const POLYGAMMA: [(u32, f64, f64); {len(rows)}] = [",
]
for n, x, v in rows:
    out.append(f"    ({n}, {repr(float(x))}, {repr(float(v))}),")
out.append("];")
with open(OUT, "w", newline="\n") as f:
    f.write("\n".join(out) + "\n")
print("wrote", OUT, len(rows), "rows")
