"""Reference polylogarithm values for tests/polylog.rs.

Writes crates/thermite-special/tests/polylog_ref/table.rs: rows of
`(s, z_re, z_im, li_re, li_im)` from mpmath at 40 digits (more where the near-integer
cancellation asks for it), rounded once. Orders cover the negative integers (the rational
arm), the small positive integers (the tabulated arm), and non-integer reals including
values within 1e-3, 1e-6 and 1e-9 of an integer (the fused near-integer arm). Arguments
cover the real line on both sides of every regime boundary (series / unity / m-th root or
inversion) and rings in the complex plane.

Convention on the cut `z in (1, inf)`: mpmath evaluates real `z > 1` as the limit from
BELOW, `Im Li_s(x) = -pi (ln x)^{s-1} / Gamma(s)` (Wood 3.1, Roughan 2026 eq. 14). The
table stores that value. The tests exercise the from-above side through `z - 0i` versus
`z + 0i` and the conjugate symmetry `Li_s(conj z) = conj Li_s(z)` for real `s`.
"""
import os
from mpmath import mp, mpf, mpc, polylog, nint

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "tests", "polylog_ref", "table.rs")

# Orders. Integers first (negative ones take the rational arm), then reals. The near-integer
# ones sit at every distance the fused arm has to survive; 0.5 is the maximal distance.
ORDERS = [
    -6, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 7, 12, 30,
    "0.5", "-0.5", "-1.5", "1.5", "2.5", "3.25", "7.5", "-3.7",
    "1.4", "2.3", "0.9", "-0.1",
    "2.001", "1.999", "3.000001", "2.999999", "5.000000001", "1.000001", "1.001",
    "0.001", "-0.001", "-1.999",
]

# Real arguments: both sides of the series/unity boundary (0.2323 positive, -0.5113
# negative), the unity/root boundary (|ln z| = 3.217, i.e. z = 25 or z = -2.0 on the
# negative side where |mu|^2 = ln^2|z| + pi^2), z = 1 and its neighbours, and the far field.
REAL_Z = [
    "-1e20", "-1e6", "-1000", "-100", "-30", "-25", "-10", "-5", "-2.5", "-2", "-1.5", "-1.25",
    "-1", "-0.9", "-0.75", "-0.6", "-0.5", "-0.4", "-0.25", "-0.1", "-0.01", "-1e-6",
    "1e-6", "0.01", "0.1", "0.2", "0.25", "0.3", "0.5", "0.75", "0.9", "0.99", "0.999",
    "1", "1.001", "1.01", "1.1", "1.5", "2", "3", "5", "10", "20", "24", "26", "30", "100",
    "1000", "1e6", "1e20",
]

# Complex arguments: rings crossing every boundary, at arguments away from the axes plus
# the negative axis itself.
RADII = ["0.1", "0.3", "0.6", "0.95", "1.05", "1.5", "3", "10", "40", "1e4", "1e12"]
ANGLES = [("0.5", "0.8660254037844386"), ("-0.5", "0.8660254037844386"),
          ("0.0", "1.0"), ("0.0", "-1.0"), ("-0.8660254037844386", "0.5"),
          ("-0.8660254037844386", "-0.5"), ("-1.0", "0.0"), ("0.9659258262890683", "0.25881904510252074")]

mp.dps = 40

rows = []


def add(s, z):
    # Near an integer the two poles of the unity series cancel and mpmath buys precision
    # itself, so give it room so the table records the function, not oracle noise.
    mp.dps = 40
    try:
        v = polylog(s, z)
    except Exception:
        return
    if not mp.isfinite(v.real) or not mp.isfinite(v.imag):
        return
    if abs(v) > mpf(10) ** 290:
        return
    rows.append((s, z, v))


# Every input goes through `float` first: the kernel sees the double, and near z = 1 the
# condition number turns the decimal-vs-double gap into thousands of ulp of phantom error.
for s_raw in ORDERS:
    s = mpf(float(s_raw))
    for z_raw in REAL_Z:
        z = mpf(float(z_raw))
        if z == 1 and s <= 1:
            continue
        add(s, z)
    for r_raw in RADII:
        r = float(r_raw)
        for c, sn in ANGLES:
            z = mpc(mpf(float(r * float(c))), mpf(float(r * float(sn))))
            add(s, z)

mp.dps = 40


def lit(v):
    f = float(v)
    s = repr(f)
    if "." not in s and "e" not in s and "inf" not in s and "nan" not in s:
        s += ".0"
    return s


out = [
    "// Generated by scripts/polylog_ref.py (mpmath, 40 dps), rounded to f64 once.",
    "// Do not hand-edit.",
    "",
    "// (s, z_re, z_im, Li_s(z)_re, Li_s(z)_im). Real z > 1 is the from-below value.",
    "#[rustfmt::skip]",
    f"static POLYLOG: [(f64, f64, f64, f64, f64); {len(rows)}] = [",
]
for s, z, v in rows:
    out.append(f"    ({lit(s)}, {lit(z.real)}, {lit(z.imag)}, {lit(v.real)}, {lit(v.imag)}),")
out.append("];")
out.append("")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", newline="\n") as f:
    f.write("\n".join(out))
print(f"wrote {len(rows)} rows to {OUT}")
