[package]
name = "thermite-special"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "Extended special functions for the Thermite SIMD library"
keywords = ["simd", "special-functions", "erf", "gamma", "math"]
categories = ["mathematics", "science", "no-std", "hardware-support"]
readme = "README.md"
include = ["/src", "/README.md", "/katex-header.html", "/LICENSE-APACHE", "/LICENSE-MIT"]

[package.metadata.docs.rs]
features = ["std"]
rustdoc-args = ["--cfg", "docsrs", "--html-in-header", "katex-header.html"]

[lints]
workspace = true

[features]
std = ["thermite/std"]
disable_dispatch = ["thermite/disable_dispatch"] # Disable dispatch in thermite for maximum performance, but massive code bloat

[dependencies]
cfg-if = "1"
crunchy = "0.2"
thermite = { workspace = true }
paste = "1"

[dev-dependencies]
libm = "0.2.15"
lambert_w = "2.0.0"
