[package]
name = "thermite-special"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "Extended special functions for the Thermite SIMD library"
publish = false                                                          # not ready for release yet

[package.metadata.docs.rs]
features = ["document_registers", "std"]
rustdoc-args = ["--cfg", "docsrs", "--html-in-header", "katex-header.html"]

[lints]
workspace = true

[features]
disable_dispatch = ["thermite/disable_dispatch"] # Disable dispatch in thermite for maximum performance, but massive code bloat

[dependencies]
cfg-if = "1"
crunchy = "0.2"
thermite = { path = "../thermite", version = "0.2.0-beta.0", default-features = false }
thermite-dispatch = { path = "../dispatch", version = "0.2.0-beta.0", default-features = false }
paste = "1"

[dev-dependencies]
libm = "0.2.15"
lambert_w = "2.0.0"
