[package]
name = "thermite-special"
version = "0.1.0"
authors = ["novacrazy <novacrazy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thermite = { path = "../thermite" }
thermite-complex = { path = "../thermite-complex" }