[package]
name = "thermite-sdf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[dependencies]
thermite = { workspace = true }
thermite-geometry = { workspace = true }

[lints]
workspace = true
