[package]
name = "thermite-sort"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "SIMD sorting algorithms built on Thermite"
keywords = ["simd", "sort", "quicksort", "vectorized", "no_std"]
categories = ["algorithms", "no-std", "hardware-support"]
publish = false                                                  # not ready for release yet

[lints]
workspace = true

[dependencies]
thermite = { workspace = true }

[dev-dependencies]
thermite = { workspace = true, features = ["std"] }

[features]
default = []
std = ["thermite/std"]
