"""Reference values for the complex polygamma psi_n(z), n >= 2.

Writes tests/polygamma_ref/table.rs. mpmath is an independent implementation at
arbitrary precision (its complex polygamma agrees with numerical differentiation of
digamma to full working precision, verified below), so it shares no code with
thermite.

    python polygamma_reference.py

The point set covers both regimes (Re z >= 1/2 direct, Re z < 1/2 reflected through
the cot-pi derivative), the recurrence walk and the pure asymptotic region, the
imaginary axis, near-real reflected points, and a mild near-pole point. |Im z| stays
moderate: sin_pi/cos_pi overflow near |Im z| ~ 233 (f64), a family-wide property the
reflection inherits (see the kernel docs).

Working precision scales per reflected row: mpmath reaches negative real parts
through Hurwitz zeta, whose direct sum cancels ~ (n+1) log10|1-z| digits down to the
reflected value, so a fixed dps records oracle noise (the same trap the real
polygamma table hit at x = -1000.5).
"""
import math
import os

import mpmath as mp

mp.mp.dps = 50
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "polygamma_ref", "table.rs")

# Oracle sanity: complex polygamma against numerical differentiation of digamma.
for (n, zr, zi) in [(2, 1.5, 2.25), (5, -3.25, 0.5), (10, 0.75, -4.0)]:
    a = mp.polygamma(n, mp.mpc(zr, zi))
    b = mp.diff(mp.digamma, mp.mpc(zr, zi), n)
    assert abs(a - b) <= abs(a) * mp.mpf(10) ** -35, (n, zr, zi)

NS = [2, 3, 4, 5, 6, 8, 10, 12, 16, 20]

# All coordinates exact in f32 so the f32 sweep can reuse the table unperturbed.
POINTS = [
    # right half-plane: series region, walk region, near the gate
    (0.75, 0.5), (1.5, 1.0), (2.5, -1.25), (5.0, 3.0), (0.625, 0.125),
    (8.0, -0.25), (10.0, 10.0), (20.0, 5.0), (50.0, -30.0), (100.0, 100.0),
    (1000.0, 1.0),
    # small real part, larger |Im|: the lanes a lexicographic gate would misroute
    (0.5625, 4.0), (0.75, 20.0),
    # the imaginary axis (Re = 0 reflects, not a pole: sin_pi(iy) != 0)
    (0.0, 1.0), (0.0, -3.5),
    # reflected half-plane
    (-0.25, 0.5), (-1.5, 0.5), (-2.25, -1.0), (-5.5, 2.0), (-10.25, -0.5),
    (-20.5, 10.0), (-50.25, -15.0),
    # reflected, hugging the real axis (near-real reflection is the delicate path)
    (-2.5, 0.0009765625), (-7.75, -0.0009765625),
    # reflected at large |Im|: the bounded-variable regrouping's reach (the naive
    # cosine-power form NaNs here). f32 covers the first, f64 all three
    (-1.5, 25.0), (-3.5, 100.0), (-3.5, -200.0),
    # mildly near a pole
    (-3.015625, 0.015625),
]

rows = []
for n in NS:
    for (zr, zi) in POINTS:
        z = mp.mpc(zr, zi)
        extra = 0 if zr >= 0.5 else int((n + 1) * math.log10(abs(complex(1 - z))) ) + 15
        mp.mp.dps = 50 + max(0, extra)
        v = mp.polygamma(n, z)
        mp.mp.dps = 50
        m = max(abs(float(v.real)), abs(float(v.imag)))
        if m > 1e290 or (m != 0 and abs(complex(v)) < 1e-290):
            continue
        rows.append((n, zr, zi, float(v.real), float(v.imag)))

out = [
    "// Generated by polygamma_reference.py (mpmath, 50+ dps, precision scaled per",
    "// reflected row), rounded to f64 once. Do not hand-edit.",
    "",
    "// (n, Re z, Im z, Re psi_n, Im psi_n)",
    "#[rustfmt::skip]",
    f"const POLYGAMMA_C: [(u32, f64, f64, f64, f64); {len(rows)}] = [",
]
for n, zr, zi, vr, vi in rows:
    out.append(f"    ({n}, {zr!r}, {zi!r}, {vr!r}, {vi!r}),")
out.append("];")
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", newline="\n") as f:
    f.write("\n".join(out) + "\n")
print("wrote", OUT, len(rows), "rows")
