//! Physicists' Hermite polynomials: `hermite_n::<N>` at a const degree.
//!
//! `laguerre.rs` already checks that `hermitev` agrees with `hermite` lane by lane, but
//! that is a consistency check between two kernels: a `hermite` that is simply wrong
//! passes it. These are the absolute values it was missing.
//!
//! References come from `scripts/legendre_ref.py`, which runs `H_{n+1} = 2x H_n - 2n H_{n-1}`
//! in exact rational arithmetic at dyadic `x` and rounds to f64 exactly once.
//!
//! Tolerances are scaled by `sum |c_k| |x|^k` rather than being flat. Hermite coefficients
//! grow fast and alternate, so the cancellation is severe well before the top of this
//! table: `H_9(0.75)` cancels terms totalling 69450 down to -1050. A flat ulp bound would
//! be a false alarm at high degree and vacuous at low degree.
//!
//! The orthonormal Hermite *functions* are covered separately in `hermite_function.rs`.
#![cfg(any(
    target_arch = "x86",
    target_arch = "x86_64",
    all(target_arch = "wasm32", feature = "wasm"),
    target_arch = "aarch64"
))]

use thermite::prelude::*;
use thermite_special::SpecialMath;

type D = Vector<f64>;
type F = Vector<f32>;

#[track_caller]
fn close_cond(name: &str, got: f64, want: f64, cond: f64, eps: f64) {
    let bound = eps * cond.max(1.0);
    let err = (got - want).abs();
    assert!(
        err <= bound,
        "{name}: got {got:?}, want {want:?} (err {err:e} > bound {bound:e})"
    );
}

// Generated by scripts/legendre_ref.py: exact rational arithmetic, rounded to f64 once.
// Do not hand-edit.

const XS: [f64; 9] = [0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, -0.3125, -0.6875];

#[rustfmt::skip]
const HERMITE: [[f64; 9]; 12] = [
    [0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, -0.625, -1.375],
    [-1.9375, -1.75, -1.4375, -1.0, -0.4375, 0.25, 1.0625, -1.609375, -0.109375],
    [-1.484375, -2.875, -4.078125, -5.0, -5.546875, -5.625, -5.140625, 3.505859375, 5.650390625],
    [11.25390625, 9.0625, 5.56640625, 1.0, -4.30859375, -9.9375, -15.37109375, 7.465087890625, -7.113037109375],
    [14.6884765625, 27.53125, 36.7998046875, 41.0, 38.9892578125, 30.09375, 14.2255859375, -32.712554931640625, -35.422698974609375],
    [-108.866943359375, -76.859375, -28.064208984375, 31.0, 91.822509765625, 144.515625, 178.605712890625, -54.20553207397461, 119.83658218383789],
    [-203.47845458984375, -368.8046875, -462.64581298828125, -461.0, -353.09295654296875, -144.3515625, 141.85296630859375, 426.42911672592163, 260.2970871925354],
    [1473.267593383789, 891.62890625, 45.91456604003906, -895.0, -1726.881332397461, -2239.74609375, -2252.237289428711, 492.3592510819435, -2035.6206454634666],
    [3623.9721717834473, 6346.689453125, 7436.768932342529, 6481.0, 3490.885639190674, -1049.994140625, -6211.062717437744, -7130.590399540961, -1365.7750075682998],
    [-25612.82363796234, -12875.9755859375, 4751.114510536194, 22591.0, 35447.47103214264, 38740.4384765625, 29670.911454200745, -4405.847519761883, 38519.11225374881],
    [-78882.64934515953, -133371.77685546875, -145172.04276394844, -107029.0, -25508.373993635178, 79110.54052734375, 176145.3493936062, 145365.4626906704, -25648.27919753862],
    [543761.4576988816, 216585.57446289062, -213403.5513047576, -604031.0, -811729.830199182, -733623.8356933594, -344505.69055360556, 6075.231253092425, -812154.0856858583],
];

#[rustfmt::skip]
const HERMITE_COND: [[f64; 9]; 12] = [
    [0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 0.625, 1.375],
    [2.0625, 2.25, 2.5625, 3.0, 3.5625, 4.25, 5.0625, 2.390625, 3.890625],
    [1.515625, 3.125, 4.921875, 7.0, 9.453125, 12.375, 15.859375, 3.994140625, 10.849609375],
    [12.75390625, 15.0625, 19.06640625, 25.0, 33.19140625, 44.0625, 58.12890625, 16.840087890625, 38.261962890625],
    [15.3134765625, 32.53125, 53.6748046875, 81.0, 117.1142578125, 165.09375, 228.6005859375, 42.478179931640625, 139.40707397460938],
    [131.367431640625, 166.890625, 230.920166015625, 331.0, 478.306884765625, 688.265625, 981.340087890625, 194.9497413635254, 574.3043556213379],
    [216.60357666015625, 473.8203125, 817.2877807617188, 1303.0, 2003.2546997070312, 3013.5234375, 4460.552185058594, 631.5817475318909, 2462.553376674652],
    [1893.294937133789, 2573.37890625, 3845.848159790039, 5937.0, 9200.364761352539, 14156.00390625, 21544.72755432129, 3124.0349712967873, 11426.271871626377],
    [3938.9809608459473, 8867.814453125, 15960.99061203003, 26785.0, 43552.531147003174, 69450.380859375, 109072.10818099976, 12057.829817570746, 55111.9778502807],
    [35064.05410861969, 50754.7275390625, 81196.00983524323, 133651.0, 220047.22963809967, 358983.6416015625, 578681.2852945328, 63768.77311932389, 281451.86323341075],
    [87545.63274407387, 202733.65283203125, 380116.819617033, 669351.0, 1146109.659987688, 1927483.0795898438, 3194134.4128854275, 281012.07955099235, 1489235.868951554],
    [793295.5985756516, 1217970.8322753906, 2071399.8310881257, 3609673.0, 6273676.127022803, 10788864.73461914, 18320723.49902922, 1578545.5583444957, 8239640.310943423],
];

/// `hermite` takes its degree as a const generic, so the sweep has to be unrolled.
macro_rules! for_each_degree {
    ($mac:ident) => {
        $mac!(1);
        $mac!(2);
        $mac!(3);
        $mac!(4);
        $mac!(5);
        $mac!(6);
        $mac!(7);
        $mac!(8);
        $mac!(9);
        $mac!(10);
        $mac!(11);
        $mac!(12);
    };
}

#[test]
fn every_degree_matches_the_exact_reference() {
    macro_rules! check {
        ($n:literal) => {
            for (j, &x) in XS.iter().enumerate() {
                let got = D::splat(x).hermite_n::<$n>().extract::<0>();
                close_cond(
                    &format!("H_{}({x})", $n),
                    got,
                    HERMITE[$n - 1][j],
                    HERMITE_COND[$n - 1][j],
                    f64::EPSILON,
                );
            }
        };
    }
    for_each_degree!(check);
}

#[test]
fn degree_zero_is_one() {
    for &x in &XS {
        assert_eq!(D::splat(x).hermite_n::<0>().extract::<0>(), 1.0);
    }
}

/// Degrees for which `n - 1`, `n` and `n + 1` all have table rows. Kept separate from
/// `for_each_degree!` on purpose: a runtime `if n + 1 <= 12` inside the full sweep still
/// *compiles* the out-of-range index for the top degree, which is a real out-of-bounds
/// expression that only a never-taken branch hides.
macro_rules! for_each_interior_degree {
    ($mac:ident) => {
        $mac!(2);
        $mac!(3);
        $mac!(4);
        $mac!(5);
        $mac!(6);
        $mac!(7);
        $mac!(8);
        $mac!(9);
        $mac!(10);
        $mac!(11);
    };
}

#[test]
fn satisfies_the_two_term_recurrence() {
    // H_{n+1} = 2x H_n - 2n H_{n-1}, as a residual against the size of the terms. This is
    // the structural counterpart to the value table: it needs no reference at all, and it
    // fails at any x if a single degree's coefficients are wrong.
    macro_rules! check {
        ($n:literal) => {
            for (j, &x) in XS.iter().enumerate() {
                let v = D::splat(x);
                let hm = HERMITE[$n - 2][j];
                let h0 = v.hermite_n::<$n>().extract::<0>();
                let hp = v.hermite_n::<{ $n + 1 }>().extract::<0>();

                let residual = hp - 2.0 * x * h0 + 2.0 * ($n as f64) * hm;
                let bound = f64::EPSILON
                    * (HERMITE_COND[$n][j]
                        + 2.0 * x.abs() * HERMITE_COND[$n - 1][j]
                        + 2.0 * ($n as f64) * HERMITE_COND[$n - 2][j]);
                assert!(
                    residual.abs() <= bound,
                    "recurrence at n={}, x={x}: residual {residual:e} > bound {bound:e}",
                    $n
                );
            }
        };
    }
    for_each_interior_degree!(check);
}

#[test]
fn parity_follows_the_degree() {
    // H_n(-x) = (-1)^n H_n(x). The recurrence mixes x and n, so a sign slip in the
    // `2n H_{n-1}` term breaks parity while still matching at x = 0.
    macro_rules! check {
        ($n:literal) => {
            for &x in &XS {
                let pos = D::splat(x).hermite_n::<$n>().extract::<0>();
                let neg = D::splat(-x).hermite_n::<$n>().extract::<0>();
                let want = if $n % 2 == 0 { pos } else { -pos };
                assert!(
                    (neg - want).abs() <= 1e-9 * pos.abs().max(1.0),
                    "parity H_{}({x}): got {neg}, want {want}",
                    $n
                );
            }
        };
    }
    for_each_degree!(check);
}

#[test]
fn values_at_the_origin_match_the_closed_form() {
    // H_n(0) = 0 for odd n, and (-2)^{n/2} (n-1)!! for even n.
    assert_eq!(D::splat(0.0).hermite_n::<0>().extract::<0>(), 1.0);

    macro_rules! check {
        ($n:literal) => {{
            let got = D::splat(0.0).hermite_n::<$n>().extract::<0>();
            if $n % 2 == 1 {
                assert!(got.abs() <= 1e-12, "H_{}(0) should vanish, got {got:e}", $n);
            } else {
                // (-2)^{n/2} * (n-1)!!
                let mut want = 1.0f64;
                let mut k = 1i64;
                while k < $n {
                    want *= -2.0 * k as f64;
                    k += 2;
                }
                assert!(
                    (got - want).abs() <= 1e-9 * want.abs(),
                    "H_{}(0): got {got}, want {want}",
                    $n
                );
            }
        }};
    }
    for_each_degree!(check);
}

#[test]
fn lanes_carrying_different_arguments_stay_independent() {
    use thermite::backend::scalar::Scalar;
    type D4 = thermite::simd::f64x4<Scalar>;

    let xs = [XS[0], XS[3], XS[6], XS[8]];
    macro_rules! check {
        ($n:literal) => {{
            let got = D4::new(xs).hermite_n::<$n>();
            for (lane, &x) in xs.iter().enumerate() {
                let want = D::splat(x).hermite_n::<$n>().extract::<0>();
                assert_eq!(got.as_slice()[lane], want, "H_{} lane {lane} at x={x}", $n);
            }
        }};
    }
    for_each_degree!(check);
}

// --- f32 ---

#[test]
fn f32_tracks_the_same_reference() {
    macro_rules! check {
        ($n:literal) => {
            if $n <= 8 {
                for (j, &x) in XS.iter().enumerate() {
                    let got = F::splat(x as f32).hermite_n::<$n>().extract::<0>() as f64;
                    close_cond(
                        &format!("f32 H_{}({x})", $n),
                        got,
                        HERMITE[$n - 1][j],
                        HERMITE_COND[$n - 1][j],
                        f32::EPSILON as f64,
                    );
                }
            }
        };
    }
    for_each_degree!(check);
}
