//! Legendre polynomials: `legendre(n, 0)` and the associated form `legendre(n, m)`.
//!
//! References come from `scripts/legendre_ref.py`, which runs the defining recurrences in
//! exact rational arithmetic (Python `fractions`) at dyadic `x` and rounds to f64 exactly
//! once. The x values are exact in binary64, so the tables carry no floating-point history
//! and the tolerances below measure this kernel rather than an oracle's own drift.
//!
//! Coverage is organized around the four things that can independently go wrong.
//!
//! The hand-tuned Estrin polynomials for degrees 1..13 are each a separate literal
//! coefficient set, so a typo in one degree is invisible from any other. The value table
//! pins every one of them.
//!
//! The runtime recurrence that takes over at degree 14 is a different code path seeded
//! from degrees 12 and 13, so the handover is checked explicitly rather than assumed.
//!
//! The three-term recurrence check is the structural counterpart to the table: it holds
//! for every degree at once, needs no reference values, and runs far past the table's
//! range. A wrong coefficient fails it even at an x the table happens not to sample.
//!
//! The associated form (m > 0) routes through `jacobi` and applies the Condon-Shortley
//! phase itself, so it needs both absolute values and a convention check: the sign of
//! `P_1^1` is exactly what a CS/no-CS mix-up gets wrong.
//!
//! `legendre_series` (Clenshaw over the same recurrence) is covered at the end: against a
//! double-double forward sum, against the single kernel through a unit coefficient, and
//! against the Henyey-Greenstein phase function, whose Legendre-moment expansion has a
//! closed form and is the series' headline application.
#![cfg(any(
    target_arch = "x86",
    target_arch = "x86_64",
    all(target_arch = "wasm32", feature = "wasm"),
    target_arch = "aarch64"
))]

use thermite::prelude::*;
use thermite_special::SpecialMath;

type D = Vector<f64>;
type F = Vector<f32>;

#[track_caller]
fn close(name: &str, got: f64, want: f64, tol: f64) {
    // Mixed absolute/relative: several probes sit near a root of P_n, where a pure
    // relative bound measures the conditioning of the problem rather than the kernel.
    let err = (got - want).abs() / want.abs().max(1.0);
    assert!(err <= tol, "{name}: got {got:?}, want {want:?} (err {err:e})");
}

/// Assert against the *conditioning* of the evaluation rather than a flat ulp count.
///
/// A monomial-basis evaluation of `P_n` has to cancel through terms of size
/// `sum |c_k| |x|^k`, and for the higher hard-coded degrees that dwarfs the result:
/// `P_12(0.875)` cancels terms of order 2000 down to 0.23, so an honest bound there is
/// about 1e-12, not 1e-16. A flat tolerance is therefore either vacuous at low degree or
/// a false alarm at high degree. `LEGENDRE_COND` carries the exact scale per (n, x), so
/// each degree gets the bound it actually deserves.
#[track_caller]
fn close_cond(name: &str, got: f64, want: f64, cond: f64, eps: f64) {
    let bound = eps * cond.max(1.0);
    let err = (got - want).abs();
    assert!(
        err <= bound,
        "{name}: got {got:?}, want {want:?} (err {err:e} > bound {bound:e})"
    );
}

/// Upper bound on that same conditioning, independent of `x` (valid for `|x| <= 1`).
///
/// Degrees past 13 leave the unrolled Estrin table for a runtime recurrence seeded from
/// degrees 12 and 13, so they inherit the seeds' error but do not keep growing like the
/// monomial sum does. Clamping at 14 keeps the bound valid without letting it explode.
fn sigma(n: u32) -> f64 {
    LEGENDRE_SIGMA[(n as usize).min(LEGENDRE_SIGMA.len() - 1)]
}

// Generated by scripts/legendre_ref.py: exact rational arithmetic, rounded to f64 once.
// Do not hand-edit.

const XS: [f64; 9] = [0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, -0.3125, -0.6875];

#[rustfmt::skip]
const LEGENDRE: [[f64; 9]; 16] = [
    [0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, -0.3125, -0.6875],
    [-0.4765625, -0.40625, -0.2890625, -0.125, 0.0859375, 0.34375, 0.6484375, -0.353515625, 0.208984375],
    [-0.1826171875, -0.3359375, -0.4306640625, -0.4375, -0.3271484375, -0.0703125, 0.3623046875, 0.3924560546875, 0.2188720703125],
    [0.317474365234375, 0.15771484375, -0.065826416015625, -0.2890625, -0.422271728515625, -0.35009765625, 0.068450927734375, 0.05051231384277344, -0.42006874084472656],
    [0.21752548217773438, 0.3397216796875, 0.3000984191894531, 0.08984375, -0.21333694458007812, -0.4163818359375, -0.18203353881835938, -0.34237802028656006, 0.3447374105453491],
    [-0.21471238136291504, 0.0242767333984375, 0.2611730098724365, 0.3232421875, 0.10744452476501465, -0.2807769775390625, -0.34905457496643066, 0.1540604792535305, -0.08445549383759499],
    [-0.23629435896873474, -0.2799186706542969, -0.07533887028694153, 0.22314453125, 0.3075726330280304, -0.034183502197265625, -0.4111849367618561, 0.2040567749645561, -0.18765764101408422],
    [0.13249184330925345, -0.15245401859283447, -0.2814990268088877, -0.073638916015625, 0.2664227201603353, 0.1976093053817749, -0.3691775337792933, -0.2543674359276338, 0.31580098497761355],
    [0.24132222653133795, 0.1768244206905365, -0.13242725929012522, -0.2678985595703125, 0.04112892638659105, 0.3103318512439728, -0.24467070231912658, -0.03123635515009937, -0.24329587597924274],
    [-0.061928630177135346, 0.22120021656155586, 0.15899470188378473, -0.18822860717773438, -0.1909398480602249, 0.2643745131790638, -0.07450526220418396, 0.2474772782052419, 0.03358435151803363],
    [-0.23416226541166907, -0.05517664272338152, 0.23421417002145972, 0.06387138366699219, -0.2652158881505784, 0.09641637001186609, 0.09797025728994413, -0.11924600788371875, 0.17709860770461971],
    [0.00066653490749502, -0.22920567315304652, 0.02259629130945484, 0.23375296592712402, -0.1426783386251742, -0.10374477185541764, 0.2326007760171791, -0.1554307815494527, -0.2641499667523058],
    [0.2163100081943039, -0.05926274957892019, -0.19990229301779827, 0.16580426692962646, 0.07332627821450721, -0.2386316086485749, 0.30096145291511256, 0.203481159650748, 0.18576109700767837],
    [0.05152723741845289, 0.1842607279522781, -0.16555446455915146, -0.05717363953590393, 0.22087138192836242, -0.24882914578665805, 0.29188601692115757, 0.021694848256407048, -0.0010171996732181927],
    [-0.18943692527189088, 0.14437125145059326, 0.06654848667789358, -0.21001850068569183, 0.1984483934965645, -0.13807942665198425, 0.21287648923751984, -0.20302305316227742, -0.1720249959748473],
    [-0.09418604041908565, -0.10281460753387961, 0.20355894537611155, -0.14985513547435403, 0.03324168094190634, 0.032630657321327305, 0.08724903229689761, 0.10258519397896604, 0.23009629511326285],
];

// sum |c_k| |x|^k for P_n at each grid point: the scale any monomial-basis evaluation
// must cancel through, and therefore the error the kernel is entitled to.
#[rustfmt::skip]
const LEGENDRE_COND: [[f64; 9]; 16] = [
    [0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 0.3125, 0.6875],
    [0.5234375, 0.59375, 0.7109375, 0.875, 1.0859375, 1.34375, 1.6484375, 0.646484375, 1.208984375],
    [0.1923828125, 0.4140625, 0.6943359375, 1.0625, 1.5478515625, 2.1796875, 2.9873046875, 0.5450439453125, 1.8436279296875],
    [0.434661865234375, 0.62646484375, 0.988861083984375, 1.5859375, 2.507415771484375, 3.86865234375, 5.810638427734375, 0.7829341888427734, 3.1248531341552734],
    [0.2517051696777344, 0.6131591796875, 1.2229499816894531, 2.27734375, 4.059123992919922, 6.9664306640625, 11.54159927368164, 0.8764356374740601, 5.341908097267151],
    [0.41990065574645996, 0.8030853271484375, 1.6648290157318115, 3.4091796875, 6.74059271812439, 12.802719116210938, 23.356847524642944, 1.1545697413384914, 9.337074276059866],
    [0.3132242262363434, 0.8984260559082031, 2.207677334547043, 5.11767578125, 11.303151398897171, 23.803585052490234, 47.84767660498619, 1.4212933427188545, 16.500221417983994],
    [0.44082500180229545, 1.123836874961853, 3.0089985146187246, 7.780853271484375, 19.143899173941463, 44.67617070674896, 98.93733601411805, 1.8430375916705088, 29.439756663172375],
    [0.38250521541340277, 1.3293016850948334, 4.093753800785635, 11.897628784179688, 32.6476822127006, 84.44998410344124, 206.05269844998838, 2.3512759941667127, 52.89765859385545],
    [0.48758749028274906, 1.6428714878857136, 5.624898246216617, 18.30551528930664, 55.99863188412928, 160.54978098347783, 431.60621358581193, 3.0548039540399436, 95.59334753507882],
    [0.46408811964784036, 1.9925538329407573, 7.748510154255655, 28.289472579956055, 96.4962605096548, 306.65080832038075, 908.2991962853798, 3.959991899095842, 173.55504917965956],
    [0.5581429780914817, 2.460730908846017, 10.725398399069817, 43.89080023765564, 166.9265579626425, 587.9811695287353, 1918.9324728906, 5.172107105765895, 316.3221698366028],
    [0.562558018639228, 3.0223241673520533, 14.887133218642107, 68.31605184078217, 289.70635340631895, 1131.1120483467967, 4067.402938454341, 6.763614580995858, 578.4190680171173],
    [0.6538922877211898, 3.7421564246160415, 20.72588593047564, 106.63193592429161, 504.20285480328465, 2182.0552987782994, 8645.60832632583, 8.878956457293514, 1060.6494398531127],
    [0.6830781202625671, 4.629544828093003, 28.920924970327473, 166.83918644487858, 879.6377127331999, 4219.684761685545, 18421.73016125858, 11.677076468544298, 1949.637677287405],
    [0.7784570019897059, 5.750707424185087, 40.443377608574465, 261.5929017974995, 1537.8764691409388, 8177.4062619289625, 39335.84721993915, 15.3941265717766, 3591.3371621865317],
];

#[rustfmt::skip]
const LEGENDRE_SIGMA: [f64; 15] = [
    1.0, 1.0, 2.0, 4.0, 8.5, 18.5, 41.0, 92.0, 208.375, 475.375, 1090.75, 2514.5, 5819.3125,
    13512.0625, 31462.625,
];

// (n, m, values); the value is the entry times sqrt(1-x^2) iff m is odd, which keeps the
// even-m constants exact and confines the irrational factor to one multiply in the test.
#[rustfmt::skip]
const ASSOC: [(u32, u32, [f64; 9]); 21] = [
    (1, 1, [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]),
    (2, 1, [-0.375, -0.75, -1.125, -1.5, -1.875, -2.25, -2.625, 0.9375, 2.0625]),
    (2, 2, [2.953125, 2.8125, 2.578125, 2.25, 1.828125, 1.3125, 0.703125, 2.70703125, 1.58203125]),
    (3, 1, [1.3828125, 1.03125, 0.4453125, -0.375, -1.4296875, -2.71875, -4.2421875, 0.767578125, -2.044921875]),
    (3, 2, [1.845703125, 3.515625, 4.833984375, 5.625, 5.712890625, 4.921875, 3.076171875, -4.229736328125, -5.438232421875]),
    (3, 3, [-14.765625, -14.0625, -12.890625, -11.25, -9.140625, -6.5625, -3.515625, -13.53515625, -7.91015625]),
    (4, 1, [0.9033203125, 1.6015625, 1.8896484375, 1.5625, 0.4150390625, -1.7578125, -5.1611328125, -1.8096923828125, 0.5303955078125]),
    (4, 2, [-6.5753173828125, -3.955078125, -0.1007080078125, 4.21875, 7.9266357421875, 9.638671875, 7.6629638671875, -2.1413040161132812, 9.130668640136719]),
    (4, 3, [-12.919921875, -24.609375, -33.837890625, -39.375, -39.990234375, -34.453125, -21.533203125, 29.608154296875, 38.067626953125]),
    (4, 4, [101.744384765625, 92.28515625, 77.545166015625, 59.0625, 38.990478515625, 20.09765625, 5.767822265625, 85.49354553222656, 29.199600219726562]),
    (5, 1, [-1.474456787109375, -0.38818359375, 1.037750244140625, 2.2265625, 2.370758056640625, 0.43212890625, -4.858245849609375, 0.31296730041503906, 1.735696792602539]),
    (5, 2, [-6.1571502685546875, -9.99755859375, -9.781265258789062, -4.921875, 3.4366607666015625, 11.84326171875, 13.962936401367188, 10.466945171356201, -7.955539226531982]),
    (5, 3, [44.4122314453125, 21.533203125, -11.9842529296875, -49.21875, -80.4803466796875, -93.310546875, -72.4822998046875, 5.736579895019531, -90.08617401123047]),
    (5, 4, [114.46243286132812, 207.6416015625, 261.7149353027344, 265.78125, 219.32144165039062, 135.6591796875, 45.421600341796875, -240.4505968093872, -180.6725263595581]),
    (5, 5, [-915.699462890625, -830.56640625, -697.906494140625, -531.5625, -350.914306640625, -180.87890625, -51.910400390625, -769.4419097900391, -262.79640197753906]),
    (6, 1, [-1.4894599914550781, -2.1353759765625, -1.4114341735839844, 0.57421875, 2.7617454528808594, 2.8223876953125, -3.158763885498047, 1.9564658403396606, -3.2617160081863403]),
    (6, 2, [9.390285015106201, 0.048065185546875, -9.910690784454346, -14.150390625, -7.9648518562316895, 7.559051513671875, 20.18812894821167, -5.247748978435993, -0.9377287700772285]),
    (6, 3, [54.80873107910156, 85.36376953125, 73.75602722167969, 14.765625, -77.79350280761719, -164.72900390625, -175.12550354003906, -85.52824258804321, 125.5785584449768]),
    (6, 4, [-379.1568088531494, -129.7760009765625, 190.83380699157715, 465.1171875, 578.4603023529053, 469.1546630859375, 192.63625144958496, 28.55350837111473, 551.7697893083096]),
    (6, 5, [-1259.0867614746094, -2284.0576171875, -2878.864288330078, -2923.59375, -2412.535858154297, -1492.2509765625, -499.6376037597656, 2644.9565649032593, 1987.3977899551392]),
    (6, 6, [9915.308246612549, 8565.216064453125, 6597.397327423096, 4385.390625, 2352.2224617004395, 870.479736328125, 133.83150100708008, 7637.312081158161, 1524.4244411587715]),
];

// --- P_n(x), the m = 0 case ---

#[test]
fn every_hardcoded_degree_matches_the_exact_reference() {
    // Degrees 1..13 are individually hand-tuned Estrin polynomials with their own literal
    // coefficients, so this is the only test that can see a typo in any single one.
    for (i, row) in LEGENDRE.iter().enumerate().take(13) {
        let n = i as u32 + 1;
        for (j, &x) in XS.iter().enumerate() {
            let got = D::splat(x).legendre(n, 0).extract::<0>();
            close_cond(&format!("P_{n}({x})"), got, row[j], LEGENDRE_COND[i][j], f64::EPSILON);
        }
    }
}

#[test]
fn the_runtime_recurrence_takes_over_cleanly_at_degree_14() {
    // Degrees up to 13 come from the unrolled table; 14 and up are produced by a loop
    // seeded with degrees 12 and 13. A handover that is off by one degree, or that seeds
    // from the wrong pair, shows up here and nowhere else.
    for (i, row) in LEGENDRE.iter().enumerate().skip(13) {
        let n = i as u32 + 1;
        for (j, &x) in XS.iter().enumerate() {
            let got = D::splat(x).legendre(n, 0).extract::<0>();
            close_cond(&format!("P_{n}({x})"), got, row[j], LEGENDRE_COND[i][j], f64::EPSILON);
        }
    }
}

#[test]
fn degree_zero_is_one_everywhere() {
    for &x in &XS {
        assert_eq!(D::splat(x).legendre(0, 0).extract::<0>(), 1.0);
    }
    // Including outside [-1, 1], where P_0 is still identically 1.
    assert_eq!(D::splat(4.5).legendre(0, 0).extract::<0>(), 1.0);
}

#[test]
fn satisfies_the_three_term_recurrence_well_past_the_table() {
    // (n+1) P_{n+1} = (2n+1) x P_n - n P_{n-1}, checked as a residual against the size of
    // the terms rather than of the result: the identity sums to zero, so scaling by the
    // result would measure cancellation instead of the kernel.
    for &x in &[-0.9375, -0.5, -0.125, 0.0, 0.25, 0.625, 0.9375, 1.0, -1.0] {
        let v = D::splat(x);
        for n in 1..40u32 {
            let pm = v.legendre(n - 1, 0).extract::<0>();
            let p0 = v.legendre(n, 0).extract::<0>();
            let pp = v.legendre(n + 1, 0).extract::<0>();

            let a = (n + 1) as f64 * pp;
            let b = (2 * n + 1) as f64 * x * p0;
            let c = n as f64 * pm;

            // The identity sums to zero, so the residual has to be judged against what the
            // three inputs are each entitled to be wrong by, propagated through their own
            // multipliers, not against the (zero) result.
            let bound = f64::EPSILON
                * ((n + 1) as f64 * sigma(n + 1) + (2 * n + 1) as f64 * sigma(n) + n as f64 * sigma(n - 1));

            let residual = a - b + c;
            assert!(
                residual.abs() <= bound,
                "recurrence at n={n}, x={x}: residual {residual:e} > bound {bound:e}"
            );
        }
    }
}

#[test]
fn endpoints_and_parity_are_exact() {
    for n in 0..20u32 {
        // P_n(1) = 1 and P_n(-1) = (-1)^n, both exactly representable.
        close(
            &format!("P_{n}(1)"),
            D::splat(1.0).legendre(n, 0).extract::<0>(),
            1.0,
            1e-14,
        );
        let want = if n % 2 == 0 { 1.0 } else { -1.0 };
        close(
            &format!("P_{n}(-1)"),
            D::splat(-1.0).legendre(n, 0).extract::<0>(),
            want,
            1e-14,
        );

        // P_n(-x) = (-1)^n P_n(x). The Estrin forms are written in x^2 and x^4, so a
        // misplaced odd/even term breaks parity while still matching at some points.
        for &x in &XS {
            let pos = D::splat(x).legendre(n, 0).extract::<0>();
            let neg = D::splat(-x).legendre(n, 0).extract::<0>();
            close(
                &format!("parity P_{n}({x})"),
                neg,
                if n % 2 == 0 { pos } else { -pos },
                1e-13,
            );
        }
    }
}

#[test]
fn odd_degrees_vanish_at_the_origin() {
    // P_n(0) = 0 for odd n, and for even n it is (-1)^{n/2} (n-1)!! / n!!.
    let mut want = 1.0f64;
    for n in 0..16u32 {
        let got = D::splat(0.0).legendre(n, 0).extract::<0>();
        if n % 2 == 1 {
            assert!(got.abs() <= 1e-15, "P_{n}(0) should vanish, got {got:e}");
        } else {
            close(&format!("P_{n}(0)"), got, want, 1e-14);
            // Advance to the next even degree's value: multiply by -(n+1)/(n+2).
            want *= -((n + 1) as f64) / ((n + 2) as f64);
        }
    }
}

#[test]
fn lanes_carrying_different_arguments_stay_independent() {
    // The degree is scalar but x is not, so a kernel that accidentally reduced across
    // lanes (or reused lane 0) would pass every one-lane test above.
    use thermite::backend::scalar::Scalar;
    type D4 = thermite::simd::f64x4<Scalar>;

    let xs = [XS[0], XS[3], XS[6], XS[8]];
    for n in 0..14u32 {
        let got = D4::new(xs).legendre(n, 0);
        for (lane, &x) in xs.iter().enumerate() {
            let want = D::splat(x).legendre(n, 0).extract::<0>();
            close(&format!("P_{n} lane {lane}"), got.as_slice()[lane], want, 1e-14);
        }
    }
}

// --- P_n^m(x), the associated form ---

#[test]
fn associated_values_match_the_exact_reference() {
    for &(n, m, ref row) in ASSOC.iter() {
        for (j, &x) in XS.iter().enumerate() {
            // Odd m carries a half power of (1 - x^2); the table holds the rational part.
            let want = if m % 2 == 1 {
                row[j] * (1.0 - x * x).sqrt()
            } else {
                row[j]
            };
            let got = D::splat(x).legendre(n, m).extract::<0>();
            close(&format!("P_{n}^{m}({x})"), got, want, 1e-12);
        }
    }
}

#[test]
fn the_condon_shortley_phase_is_present() {
    // P_1^1(x) = -sqrt(1 - x^2) with the phase, +sqrt(1 - x^2) without it. This single
    // sign is the whole difference between the two conventions in the literature, and a
    // magnitude-only test cannot see it.
    for &x in &XS {
        let got = D::splat(x).legendre(1, 1).extract::<0>();
        let mag = (1.0 - x * x).sqrt();
        close(&format!("P_1^1({x})"), got, -mag, 1e-14);
        assert!(
            got < 0.0,
            "P_1^1({x}) must be negative under Condon-Shortley, got {got}"
        );
    }
}

#[test]
fn orders_above_the_degree_vanish() {
    for n in 0..8u32 {
        for m in (n + 1)..(n + 4) {
            for &x in &XS {
                let got = D::splat(x).legendre(n, m).extract::<0>();
                assert_eq!(got, 0.0, "P_{n}^{m}({x}) should be exactly zero, got {got}");
            }
        }
    }
}

#[test]
fn the_associated_form_satisfies_its_own_recurrence_in_n() {
    // (n-m+1) P_{n+1}^m = (2n+1) x P_n^m - (n+m) P_{n-1}^m. This holds under either sign
    // convention, so it checks the recurrence independently of the phase test above.
    for &x in &[-0.6875, -0.3125, 0.125, 0.5, 0.875] {
        let v = D::splat(x);
        for m in 1..5u32 {
            for n in (m + 1)..12u32 {
                let pm = v.legendre(n - 1, m).extract::<0>();
                let p0 = v.legendre(n, m).extract::<0>();
                let pp = v.legendre(n + 1, m).extract::<0>();

                let a = (n - m + 1) as f64 * pp;
                let b = (2 * n + 1) as f64 * x * p0;
                let c = (n + m) as f64 * pm;

                let residual = a - b + c;
                let scale = a.abs().max(b.abs()).max(c.abs()).max(1.0);
                assert!(
                    residual.abs() / scale <= 1e-11,
                    "assoc recurrence n={n} m={m} x={x}: residual {residual:e} scale {scale:e}"
                );
            }
        }
    }
}

// --- legendre_series ---

// Minimal double-double for the forward reference: both the P_k recurrence and the
// accumulation, since the recurrence is itself the cancellation-prone step (the same lesson
// as the Chebyshev test's oracle).
type Dd = (f64, f64);

fn two_sum(a: f64, b: f64) -> Dd {
    let s = a + b;
    let bb = s - a;
    (s, (a - (s - bb)) + (b - bb))
}

fn quick_two_sum(a: f64, b: f64) -> Dd {
    let s = a + b;
    (s, b - (s - a))
}

fn two_prod(a: f64, b: f64) -> Dd {
    let p = a * b;
    (p, a.mul_add(b, -p))
}

fn dd_add(a: Dd, b: Dd) -> Dd {
    let (s, e) = two_sum(a.0, b.0);
    quick_two_sum(s, e + a.1 + b.1)
}

fn dd_mul_f64(a: Dd, b: f64) -> Dd {
    let (p, e) = two_prod(a.0, b);
    quick_two_sum(p, e + a.1 * b)
}

fn dd_div_f64(a: Dd, b: f64) -> Dd {
    let q1 = a.0 / b;
    let (p, e) = two_prod(q1, b);
    let r = ((a.0 - p) - e + a.1) / b;
    quick_two_sum(q1, r)
}

/// `sum c_k P_k(x)` with the recurrence `(k+1) P_{k+1} = (2k+1) x P_k - k P_{k-1}` and the
/// accumulation both in double-double.
fn series_reference(coeffs: &[f64], x: f64) -> f64 {
    let mut prev: Dd = (1.0, 0.0);
    let mut cur: Dd = (x, 0.0);
    let mut sum: Dd = (coeffs[0], 0.0);
    for (k, &c) in coeffs.iter().enumerate().skip(1) {
        sum = dd_add(sum, dd_mul_f64(cur, c));
        // (2k+1) x P_k - k P_{k-1}, then / (k+1)
        let a = dd_mul_f64(dd_mul_f64(cur, (2 * k + 1) as f64), x);
        let b = dd_mul_f64(prev, -(k as f64));
        let next = dd_div_f64(dd_add(a, b), (k + 1) as f64);
        prev = cur;
        cur = next;
    }
    sum.0 + sum.1
}

/// `sum |c_k P_k(x)|`, the scale the summation cancels through.
fn series_condition(coeffs: &[f64], x: f64) -> f64 {
    let (mut prev, mut cur) = (1.0, x);
    let mut s = coeffs[0].abs();
    for (k, &c) in coeffs.iter().enumerate().skip(1) {
        s += (c * cur).abs();
        let next = ((2 * k + 1) as f64 * x * cur - k as f64 * prev) / (k + 1) as f64;
        prev = cur;
        cur = next;
    }
    s
}

const SN: usize = 24;

fn decaying() -> [f64; SN] {
    let mut c = [0.0; SN];
    for (k, slot) in c.iter_mut().enumerate() {
        *slot = if k % 2 == 0 { 1.0 } else { -1.0 } * 0.75f64.powi(k as i32);
    }
    c
}

#[test]
fn series_matches_the_double_double_forward_sum() {
    let c = decaying();
    let xs: Vec<f64> = (-20..=20).map(|i| i as f64 / 20.0).collect();
    for &x in &xs {
        let want = series_reference(&c, x);
        let got = D::splat(x).legendre_series::<SN>(&c).extract::<0>();
        let bound = 4.0 * f64::EPSILON * series_condition(&c, x).max(1.0);
        assert!(
            (got - want).abs() <= bound,
            "series at x={x}: got {got}, want {want} (err {:e} > {bound:e})",
            (got - want).abs()
        );
    }
}

#[test]
fn series_with_a_unit_coefficient_is_the_single_polynomial() {
    // Ties Clenshaw to `legendre(n, 0)`, whose Estrin table is pinned above.
    for n in 0..SN {
        let mut unit = [0.0f64; SN];
        unit[n] = 1.0;
        for &x in &XS {
            let got = D::splat(x).legendre_series::<SN>(&unit).extract::<0>();
            let want = D::splat(x).legendre(n as u32, 0).extract::<0>();
            close_cond(
                &format!("unit series P_{n}({x})"),
                got,
                want,
                sigma(n as u32),
                4.0 * f64::EPSILON,
            );
        }
    }
}

#[test]
fn series_short_forms() {
    for &x in &XS {
        let v = D::splat(x);
        assert_eq!(v.legendre_series::<1>(&[2.5]).extract::<0>(), 2.5);
        let want = 2.5 - 1.25 * x;
        let got = v.legendre_series::<2>(&[2.5, -1.25]).extract::<0>();
        assert!((got - want).abs() <= 2.0 * f64::EPSILON, "N=2 at {x}");
        // N = 3 is the first to enter the loop-hoist path.
        let want = 2.5 - 1.25 * x + 0.5 * (1.5 * x * x - 0.5);
        let got = v.legendre_series::<3>(&[2.5, -1.25, 0.5]).extract::<0>();
        assert!((got - want).abs() <= 8.0 * f64::EPSILON, "N=3 at {x}: {got} vs {want}");
    }
}

#[test]
fn henyey_greenstein_moments_reproduce_the_closed_form() {
    // p(mu) = (1 - g^2) / (1 + g^2 - 2 g mu)^{3/2} = sum (2l+1) g^l P_l(mu). The Legendre
    // moments of the phase function are (2l+1) g^l. This is the series' headline use in a
    // renderer, and its closed form is an oracle independent of every kernel in this crate.
    //
    // Truncation after N terms is bounded by the tail with |P_l| <= 1 (attained at mu = 1):
    //     sum_{l>=N} (2l+1) |g|^l = |g|^N [ (2N+1)/(1-|g|) + 2|g|/(1-|g|)^2 ]
    const N: usize = 40;
    for &g in &[0.2f64, 0.4, 0.5, -0.3] {
        let mut c = [0.0f64; N];
        for (l, slot) in c.iter_mut().enumerate() {
            *slot = (2 * l + 1) as f64 * g.powi(l as i32);
        }
        let ag = g.abs();
        let trunc = ag.powi(N as i32) * ((2 * N + 1) as f64 / (1.0 - ag) + 2.0 * ag / ((1.0 - ag) * (1.0 - ag)));

        for i in 0..=40 {
            let mu = -1.0 + i as f64 / 20.0;
            let want = (1.0 - g * g) / (1.0 + g * g - 2.0 * g * mu).powf(1.5);
            let got = D::splat(mu).legendre_series::<N>(&c).extract::<0>();
            let bound = trunc + 1e-14 * want.abs().max(1.0);
            assert!(
                (got - want).abs() <= bound,
                "HG g={g} mu={mu}: got {got}, want {want} (err {:e} > {bound:e})",
                (got - want).abs()
            );
        }
    }
}

#[test]
fn series_lanes_stay_independent() {
    use thermite::backend::scalar::Scalar;
    type D4 = thermite::simd::f64x4<Scalar>;
    let c = decaying();
    let xs = [-0.9375, -0.25, 0.5, 0.99];
    let got = D4::new(xs).legendre_series::<SN>(&c);
    for (lane, &x) in xs.iter().enumerate() {
        assert_eq!(
            got.as_slice()[lane],
            D::splat(x).legendre_series::<SN>(&c).extract::<0>(),
            "lane {lane}"
        );
    }
}

#[test]
fn f32_series_tracks_the_reference() {
    let c = decaying();
    let mut c32 = [0.0f32; SN];
    for (o, &v) in c32.iter_mut().zip(c.iter()) {
        *o = v as f32;
    }
    let mut cw = [0.0f64; SN];
    for (o, &v) in cw.iter_mut().zip(c32.iter()) {
        *o = v as f64;
    }
    for i in -16..=16 {
        let x = i as f64 / 16.0;
        let want = series_reference(&cw, x);
        let got = F::splat(x as f32).legendre_series::<SN>(&c32).extract::<0>() as f64;
        let bound = 4.0 * f32::EPSILON as f64 * series_condition(&cw, x).max(1.0);
        assert!(
            (got - want).abs() <= bound,
            "f32 series at x={x}: err {:e} > {bound:e}",
            (got - want).abs()
        );
    }
}

// --- f32 ---

#[test]
fn f32_tracks_the_same_reference() {
    // Single precision over the low degrees, where the f64 table is still a valid target
    // at f32 resolution. The point is that the f32 impl selects the same coefficients,
    // not that it is as accurate.
    for (i, row) in LEGENDRE.iter().enumerate().take(10) {
        let n = i as u32 + 1;
        for (j, &x) in XS.iter().enumerate() {
            let got = F::splat(x as f32).legendre(n, 0).extract::<0>() as f64;
            // Same conditioning, f32's epsilon.
            close_cond(
                &format!("f32 P_{n}({x})"),
                got,
                row[j],
                LEGENDRE_COND[i][j],
                f32::EPSILON as f64,
            );
        }
    }
}

#[test]
fn f32_associated_values_track_the_reference() {
    for &(n, m, ref row) in ASSOC.iter() {
        for (j, &x) in XS.iter().enumerate() {
            let want = if m % 2 == 1 {
                row[j] * (1.0 - x * x).sqrt()
            } else {
                row[j]
            };
            let got = F::splat(x as f32).legendre(n, m).extract::<0>() as f64;
            close(&format!("f32 P_{n}^{m}({x})"), got, want, 5e-5);
        }
    }
}
