//! Comprehensive benchmarks of every `LinAlg3Vector` / `LinAlg4Vector` trait
//! method across the three implemented x86 backends (Scalar, x86-v2, x86-v3),
//! for both `f32x4` and `f64x4`.
//!
//! # Layout
//!
//! Each `(backend, element)` pair becomes its own module (`scalar_f32`,
//! `v2_f64`, `v3_f32`, ...) generated by the `defk!` macro. Every timed kernel
//! in a module is wrapped in that backend's `#[target_feature]` (Scalar: none,
//! v2: `sse4.2`, v3: `avx2,fma`). Because the `Vector`/register trait methods
//! are all `#[inline(always)]`, they inline into the `#[target_feature]` kernel
//! and get genuine backend codegen - the same trick `benches/nm.rs` uses. This
//! is what makes the comparison honest: without it, v2/v3 intrinsics would not
//! be enabled and every backend would compile to roughly the same scalar code.
//!
//! Criterion groups are keyed by **operation**, so all six configurations show
//! up side-by-side in each group's report (e.g. group `cross3` contains
//! `scalar/f32`, `v2/f32`, `v3/f32`, `scalar/f64`, ...). Each timed iteration
//! runs the op over a batch of `N` inputs, so the reported time is per-batch;
//! divide by `N` for per-op latency. Relative numbers across backends are the
//! point.
//!
//! # Running
//!
//! ```text
//! cargo bench --bench linalg                 # everything
//! cargo bench --bench linalg -- cross3       # one operation, all backends
//! cargo bench --bench linalg -- v3/          # one backend, all operations
//! cargo bench --bench linalg -- mat4_product/v3/f32
//! ```
//!
//! # Note
//!
//! The kernels *force* a specific backend regardless of the host CPU. The host
//! must therefore actually support the forced ISA (AVX2+FMA for the `v3`
//! configs, SSE4.2 for `v2`) or those benchmarks will fault - exactly the same
//! caveat as `benches/nm.rs`. This benchmark targets x86 and is only meant to
//! be built/run on an x86-64 host.

#![allow(non_camel_case_types, dead_code)]

use criterion::{Criterion, criterion_group, criterion_main};
use rand::RngExt;
use std::hint::black_box;

use thermite::Vector;
use thermite::backend::scalar::Scalar;
use thermite::backend::x86_v2::X86V2;
use thermite::backend::x86_v3::X86V3;
use thermite::simd::Simd;
use thermite::vector::{GenericVector, LinAlg3Vector, LinAlg4Vector};

/// Batch size: number of inputs processed per timed iteration.
const N: usize = 1024;

/// Generate one `(backend, element)` benchmark module.
///
/// The optional trailing `#[target_feature(...)]` is applied to every timed
/// kernel so the (inlined) register methods get real backend codegen. Scalar
/// omits it. Kernels are declared `unsafe fn` uniformly so the call sites stay
/// identical whether or not the attribute is present.
macro_rules! defk {
    ($mod:ident, $backend:ty, $reg:ident, $e:ty $(, #[$tf:meta])?) => {
        pub mod $mod {
            use super::*;

            /// The vector type under test for this backend/element pair.
            type V = Vector<<$backend as Simd>::$reg>;

            /// Pre-generated, randomized inputs. Built once, outside the timed
            /// region, and only read by the kernels.
            pub struct Data {
                /// `N` random 4-vectors (`a` operand).
                va: Vec<V>,
                /// `N` random 4-vectors (`b` operand).
                vb: Vec<V>,
                /// `N` random 3x3 matrices (3 columns; 4th lane unused).
                m3: Vec<[V; 3]>,
                /// `N` random 4x4 matrices (`lhs` operand).
                m4: Vec<[V; 4]>,
                /// `N` random 4x4 matrices (`rhs` operand for matrix*matrix).
                n4: Vec<[V; 4]>,
            }

            /// One random vector with moderate finite lanes in `[-8, 8]`.
            fn rvec(rng: &mut impl RngExt) -> V {
                let a: [$e; 4] = [
                    rng.random_range(-8.0..8.0),
                    rng.random_range(-8.0..8.0),
                    rng.random_range(-8.0..8.0),
                    rng.random_range(-8.0..8.0),
                ];
                V::new(a)
            }

            pub fn make_data() -> Data {
                let mut rng = rand::rng();
                Data {
                    va: (0..N).map(|_| rvec(&mut rng)).collect(),
                    vb: (0..N).map(|_| rvec(&mut rng)).collect(),
                    m3: (0..N).map(|_| [rvec(&mut rng), rvec(&mut rng), rvec(&mut rng)]).collect(),
                    m4: (0..N).map(|_| [rvec(&mut rng), rvec(&mut rng), rvec(&mut rng), rvec(&mut rng)]).collect(),
                    n4: (0..N).map(|_| [rvec(&mut rng), rvec(&mut rng), rvec(&mut rng), rvec(&mut rng)]).collect(),
                }
            }

            // ---- LinAlg3Vector --------------------------------------------

            $(#[$tf])? pub unsafe fn dot3(d: &Data) {
                for (&a, &b) in d.va.iter().zip(&d.vb) {
                    black_box(black_box(a).dot3(black_box(b)));
                }
            }

            $(#[$tf])? pub unsafe fn cross3(d: &Data) {
                for (&a, &b) in d.va.iter().zip(&d.vb) {
                    black_box(black_box(a).cross3::<false>(black_box(b)));
                }
            }

            $(#[$tf])? pub unsafe fn cross3_dop(d: &Data) {
                for (&a, &b) in d.va.iter().zip(&d.vb) {
                    black_box(black_box(a).cross3::<true>(black_box(b)));
                }
            }

            $(#[$tf])? pub unsafe fn zero4(d: &Data) {
                for &a in &d.va {
                    black_box(black_box(a).zero4());
                }
            }

            $(#[$tf])? pub unsafe fn one4(d: &Data) {
                for &a in &d.va {
                    black_box(black_box(a).one4());
                }
            }

            $(#[$tf])? pub unsafe fn min_element3(d: &Data) {
                for &a in &d.va {
                    black_box(black_box(a).min_element3());
                }
            }

            $(#[$tf])? pub unsafe fn max_element3(d: &Data) {
                for &a in &d.va {
                    black_box(black_box(a).max_element3());
                }
            }

            $(#[$tf])? pub unsafe fn sum_elements3(d: &Data) {
                for &a in &d.va {
                    black_box(black_box(a).sum_elements3());
                }
            }

            $(#[$tf])? pub unsafe fn prod_elements3(d: &Data) {
                for &a in &d.va {
                    black_box(black_box(a).prod_elements3());
                }
            }

            $(#[$tf])? pub unsafe fn mat3_transpose(d: &Data) {
                for m in &d.m3 {
                    black_box(V::mat3_transpose(black_box(m)));
                }
            }

            $(#[$tf])? pub unsafe fn mat3_vec3_col(d: &Data) {
                for (&v, m) in d.va.iter().zip(&d.m3) {
                    black_box(black_box(v).mat3_vec3_product::<true>(black_box(m)));
                }
            }

            $(#[$tf])? pub unsafe fn mat3_vec3_row(d: &Data) {
                for (&v, m) in d.va.iter().zip(&d.m3) {
                    black_box(black_box(v).mat3_vec3_product::<false>(black_box(m)));
                }
            }

            // ---- LinAlg4Vector --------------------------------------------

            $(#[$tf])? pub unsafe fn dot4(d: &Data) {
                for (&a, &b) in d.va.iter().zip(&d.vb) {
                    black_box(black_box(a).dot4(black_box(b)));
                }
            }

            $(#[$tf])? pub unsafe fn quat4_product(d: &Data) {
                for (&a, &b) in d.va.iter().zip(&d.vb) {
                    black_box(black_box(a).quat4_product(black_box(b)));
                }
            }

            $(#[$tf])? pub unsafe fn quat4_vec3(d: &Data) {
                for (&q, &v) in d.va.iter().zip(&d.vb) {
                    black_box(black_box(q).quat4_vec3_product::<false>(black_box(v)));
                }
            }

            $(#[$tf])? pub unsafe fn quat4_vec3_dop(d: &Data) {
                for (&q, &v) in d.va.iter().zip(&d.vb) {
                    black_box(black_box(q).quat4_vec3_product::<true>(black_box(v)));
                }
            }

            $(#[$tf])? pub unsafe fn mat4_transpose(d: &Data) {
                for m in &d.m4 {
                    black_box(V::mat4_transpose(black_box(m)));
                }
            }

            $(#[$tf])? pub unsafe fn mat4_vec4_col(d: &Data) {
                for (&v, m) in d.va.iter().zip(&d.m4) {
                    black_box(black_box(v).mat4_vec4_product::<true>(black_box(m)));
                }
            }

            $(#[$tf])? pub unsafe fn mat4_vec4_row(d: &Data) {
                for (&v, m) in d.va.iter().zip(&d.m4) {
                    black_box(black_box(v).mat4_vec4_product::<false>(black_box(m)));
                }
            }

            $(#[$tf])? pub unsafe fn mat4_vec3_col(d: &Data) {
                for (&v, m) in d.va.iter().zip(&d.m4) {
                    black_box(black_box(v).mat4_vec3_product::<true>(black_box(m)));
                }
            }

            $(#[$tf])? pub unsafe fn mat4_vec3_row(d: &Data) {
                for (&v, m) in d.va.iter().zip(&d.m4) {
                    black_box(black_box(v).mat4_vec3_product::<false>(black_box(m)));
                }
            }

            $(#[$tf])? pub unsafe fn mat4_product_col(d: &Data) {
                for (l, r) in d.m4.iter().zip(&d.n4) {
                    black_box(V::mat4_product::<true>(black_box(l), black_box(r)));
                }
            }

            $(#[$tf])? pub unsafe fn mat4_product_row(d: &Data) {
                for (l, r) in d.m4.iter().zip(&d.n4) {
                    black_box(V::mat4_product::<false>(black_box(l), black_box(r)));
                }
            }

            $(#[$tf])? pub unsafe fn mat4_det(d: &Data) {
                for m in &d.m4 {
                    black_box(V::mat4_det(black_box(m)));
                }
            }

            $(#[$tf])? pub unsafe fn mat4_inverse(d: &Data) {
                for m in &d.m4 {
                    black_box(V::mat4_inverse(black_box(m)));
                }
            }

            $(#[$tf])? pub unsafe fn mat4_inverse_inplace(d: &Data) {
                for m in &d.m4 {
                    let mut mm = *m;
                    let mut det: $e = 0.0;
                    let ok = V::mat4_inverse_inplace::<false>(&mut mm, &mut det);
                    black_box((ok, mm, det));
                }
            }

            $(#[$tf])? pub unsafe fn mat4_inverse_det_only(d: &Data) {
                for m in &d.m4 {
                    let mut mm = *m;
                    let mut det: $e = 0.0;
                    let ok = V::mat4_inverse_inplace::<true>(&mut mm, &mut det);
                    black_box((ok, mm, det));
                }
            }
        }
    };
}

defk!(scalar_f32, Scalar, f32x4, f32);
defk!(scalar_f64, Scalar, f64x4, f64);
defk!(v2_f32, X86V2, f32x4, f32, #[target_feature(enable = "sse4.2")]);
defk!(v2_f64, X86V2, f64x4, f64, #[target_feature(enable = "sse4.2")]);
defk!(v3_f32, X86V3, f32x4, f32, #[target_feature(enable = "avx2,fma")]);
defk!(v3_f64, X86V3, f64x4, f64, #[target_feature(enable = "avx2,fma")]);

/// All six pre-generated datasets, built once and shared across every group.
struct All {
    s32: scalar_f32::Data,
    s64: scalar_f64::Data,
    v2a: v2_f32::Data,
    v2b: v2_f64::Data,
    v3a: v3_f32::Data,
    v3b: v3_f64::Data,
}

impl All {
    fn make() -> Self {
        All {
            s32: scalar_f32::make_data(),
            s64: scalar_f64::make_data(),
            v2a: v2_f32::make_data(),
            v2b: v2_f64::make_data(),
            v3a: v3_f32::make_data(),
            v3b: v3_f64::make_data(),
        }
    }
}

/// Register one criterion group named `$name` containing all six backend
/// configurations for kernel `$k`.
macro_rules! group {
    ($c:expr, $all:expr, $name:literal, $k:ident) => {{
        let mut g = $c.benchmark_group($name);
        g.bench_function("scalar/f32", |b| b.iter(|| unsafe { scalar_f32::$k(&$all.s32) }));
        g.bench_function("scalar/f64", |b| b.iter(|| unsafe { scalar_f64::$k(&$all.s64) }));
        g.bench_function("v2/f32", |b| b.iter(|| unsafe { v2_f32::$k(&$all.v2a) }));
        g.bench_function("v2/f64", |b| b.iter(|| unsafe { v2_f64::$k(&$all.v2b) }));
        g.bench_function("v3/f32", |b| b.iter(|| unsafe { v3_f32::$k(&$all.v3a) }));
        g.bench_function("v3/f64", |b| b.iter(|| unsafe { v3_f64::$k(&$all.v3b) }));
        g.finish();
    }};
}

fn bench_linalg3(c: &mut Criterion, all: &All) {
    group!(c, all, "dot3", dot3);
    group!(c, all, "cross3", cross3);
    group!(c, all, "cross3_dop", cross3_dop);
    group!(c, all, "zero4", zero4);
    group!(c, all, "one4", one4);
    group!(c, all, "min_element3", min_element3);
    group!(c, all, "max_element3", max_element3);
    group!(c, all, "sum_elements3", sum_elements3);
    group!(c, all, "prod_elements3", prod_elements3);
    group!(c, all, "mat3_transpose", mat3_transpose);
    group!(c, all, "mat3_vec3_col", mat3_vec3_col);
    group!(c, all, "mat3_vec3_row", mat3_vec3_row);
}

fn bench_linalg4(c: &mut Criterion, all: &All) {
    group!(c, all, "dot4", dot4);
    group!(c, all, "quat4_product", quat4_product);
    group!(c, all, "quat4_vec3", quat4_vec3);
    group!(c, all, "quat4_vec3_dop", quat4_vec3_dop);
    group!(c, all, "mat4_transpose", mat4_transpose);
    group!(c, all, "mat4_vec4_col", mat4_vec4_col);
    group!(c, all, "mat4_vec4_row", mat4_vec4_row);
    group!(c, all, "mat4_vec3_col", mat4_vec3_col);
    group!(c, all, "mat4_vec3_row", mat4_vec3_row);
    group!(c, all, "mat4_product_col", mat4_product_col);
    group!(c, all, "mat4_product_row", mat4_product_row);
    group!(c, all, "mat4_det", mat4_det);
    group!(c, all, "mat4_inverse", mat4_inverse);
    group!(c, all, "mat4_inverse_inplace", mat4_inverse_inplace);
    group!(c, all, "mat4_inverse_det_only", mat4_inverse_det_only);
}

fn benches(c: &mut Criterion) {
    let all = All::make();
    bench_linalg3(c, &all);
    bench_linalg4(c, &all);
}

criterion_group!(linalg, benches);
criterion_main!(linalg);
