"""Generates cot_pi.rs: coefficient rows for the n-th derivative of cot(pi x).

The general form (Boost.Math `poly_cot_pi`) is

    d^n/dx^n cot(pi x) = pi^n * sum_k C[k,n] cos^k(pi x) / sin^(n+1)(pi x)

with the integer coefficient triangle

    C[0,1] = -1;  C[k-1,n+1] -= k * C[k,n];  C[k+1,n+1] += (k - n - 1) * C[k,n]

Only every other cos power is nonzero (k = n-1 mod 2), so each row stores just the
nonzero entries, ascending in cos^2: for odd n the value is pi^n * P(c^2) / s^(n+1),
for even n it is pi^n * c * P(c^2) / s^(n+1). The cosine-power form (rather than
multiple angles) is what keeps every polynomial term zero at half-integers, where the
function has its minimum, so no cancellation there.

Rows 1..=20, matching Boost's tabulated range. Every row is verified against
mpmath.diff of cot(pi x) before anything is written.
"""
import os
import struct
from fractions import Fraction

from mpmath import mp, mpf, cot, pi, diff

mp.dps = 50
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "cot_pi.rs")
N_MAX = 20

# --- the integer triangle ---
rows_full = {1: {0: Fraction(-1)}}
for n in range(1, N_MAX):
    nxt = {}
    for k, cv in rows_full[n].items():
        if k >= 1:
            nxt[k - 1] = nxt.get(k - 1, Fraction(0)) - k * cv
        nxt[k + 1] = nxt.get(k + 1, Fraction(0)) + (k - n - 1) * cv
    rows_full[n + 1] = {k: v for k, v in nxt.items() if v != 0}

# packed: ascending powers of c^2, with the odd single c factored out for even n
rows = []
for n in range(1, N_MAX + 1):
    off = 0 if n % 2 == 1 else 1
    top = max(rows_full[n])
    packed = [rows_full[n].get(2 * j + off, Fraction(0)) for j in range((top - off) // 2 + 1)]
    assert all(v.denominator == 1 for v in packed), n
    rows.append([int(v) for v in packed])

# --- verify every row against mpmath ---
for n in range(1, N_MAX + 1):
    for xs in ("0.3", "-2.6", "1.75", "-0.45"):
        x = mpf(xs)
        s, c = mp.sinpi(x), mp.cospi(x)
        p_val = sum(mpf(v) * c ** (2 * j) for j, v in enumerate(rows[n - 1]))
        if n % 2 == 0:
            p_val *= c
        got = pi ** n * p_val / s ** (n + 1)
        want = diff(lambda u: cot(pi * u), x, n)
        assert abs(got - want) <= abs(want) * mpf(10) ** -35, (n, xs, got, want)


def f32_round(v):
    return struct.unpack("<f", struct.pack("<f", float(v)))[0]


def lit(v, fmt):
    """Shortest decimal literal that parses back to exactly the rounded value."""
    if fmt == "f64":
        s = repr(float(v))
    else:
        f = f32_round(v)
        s = next(f"{f:.{p}g}" for p in range(1, 18) if f32_round(float(f"{f:.{p}g}")) == f)
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s


w = []
p = w.append
p("// @generated by cot_pi.py, alongside. DO NOT EDIT BY HAND.")
p("//! Coefficient rows for the n-th derivative of `$\\cot(\\pi x)$`, the polygamma")
p("//! reflection kernel.")
p("//!")
p("//! Row `n - 1` holds the nonzero coefficients of the cosine polynomial in")
p("//!")
p("//! ```math")
p("//! \\frac{\\mathrm{d}^n}{\\mathrm{d}x^n}\\cot(\\pi x)")
p("//!     = \\pi^n\\,\\frac{P_n(\\cos\\pi x)}{\\sin^{n+1}(\\pi x)}")
p("//! ```")
p("//!")
p("//! ascending in `$\\cos^2$`; `$P_n$` is even for odd `n` and `$\\cos\\pi x$` times an")
p("//! even polynomial for even `n` (the caller multiplies that single factor back).")
p("//! Cosine powers rather than multiple angles keep every term zero at half-integer")
p("//! arguments, right where the derivative has its minimum, so there is no")
p("//! cancellation there (Boost.Math `poly_cot_pi`).")
p("//!")
p("//! The exact integer coefficients outgrow every float format (row 20 tops out near")
p("//! `$5\\times10^{18}$`). Each entry here is the format's nearest value, one rounding.")
p("//! Rows stop at `n = 20`, Boost's tabulated range. Past it the reflection is not")
p("//! implemented (see `polygamma_impl`).")
p("")
p("use thermite::element::FloatElement;")
p("")
p("/// Coefficient rows for the derivatives of `$\\cot(\\pi x)$`; see the [module docs](self).")
p("pub trait CotPiDerivatives: FloatElement {")
p("    /// Row `n - 1` is the polynomial for the n-th derivative.")
p("    const COT_PI_ROWS: &'static [&'static [Self]];")
p("}")
for fmt in ("f32", "f64"):
    p("")
    p(f"impl CotPiDerivatives for {fmt} {{")
    p("    #[rustfmt::skip]")
    p(f"    const COT_PI_ROWS: &'static [&'static [{fmt}]] = &[")
    for n, row in enumerate(rows, start=1):
        body = ", ".join(lit(v, fmt) for v in row)
        p(f"        &[{body}],  // n = {n}")
    p("    ];")
    p("}")
p("")
with open(OUT, "w", newline="\n") as f:
    f.write("\n".join(w) + "\n")
print("wrote", OUT, len(rows), "rows")
