//! Raw approximation coefficients, shared across crates.
//!
//! The whole module is `#[doc(hidden)]`, and the sibling crates are its entire intended
//! audience: `thermite-complex` builds the complex Gamma family and the Faddeeva
//! function on the same constants the real kernels here use. Nothing in it is stable
//! surface. Coefficients, array orders and names follow whatever the current
//! approximation needs. Depend on the functions, not on these.
//!
//! * [`gamma`]: Lanczos and asymptotic coefficients behind the Gamma family, as bare
//!   elements, plus the shared real implementations that consume them.
//! * [`primal`]: the same Gamma coefficients lifted into a _primal_ vector type, so a
//!   composite reaches the real table its `Primal` would.
//! * [`weideman`]: the Faddeeva approximation, meaning its two traits, the precision
//!   ladder, and the generated coefficient tables. Generated by `weideman.py`, alongside.
//!
//! # A warning about reuse
//!
//! The _tables_ generalize, the _implementations_ beside them do not. The `*_impl`
//! helpers in [`gamma`] branch on real orderings (`cmp_lt`, `floor`, `signum`) and are
//! bounded on `FloatVectorWithBits`, so none of them applies over C even where the
//! coefficients do.

pub mod gamma;
pub mod primal;
pub mod weideman;
