// @generated by gen_consts.py at the workspace root. DO NOT EDIT BY HAND.
//! Constants behind the polylogarithm kernel: `$\zeta$` at the positive integers and the
//! Stieltjes constants, one table per float format.
//!
//! # `ZETA_INT` ends where the format does
//!
//! Entry `i` is `$\zeta(i + 2)$`. The table stops at the last `$n$` for which
//! `$\zeta(n)$` is distinguishable from 1 in the format: `$\zeta(n) - 1 \approx 2^{-n}$`, so
//! past the table the nearest float is exactly `1.0`, and a kernel reads that value for
//! every order beyond it without a branch worth having. `ZETA_INT.len() + 1` is the last
//! tabulated `$n$`.
//!
//! | format | entries | last tabulated |
//! |---|---|---|
//! | `f32` | 23 | `$\zeta(24)$` |
//! | `f64` | 52 | `$\zeta(53)$` |
//!
//! # `STIELTJES`
//!
//! `$\gamma_0, \gamma_1, \ldots$` in the Laurent expansion about the pole,
//!
//! ```math
//! \zeta(1 + \varepsilon) - \frac{1}{\varepsilon} = \sum_{k \ge 0} \frac{(-1)^k}{k!}\gamma_k\,\varepsilon^k ,
//! ```
//!
//! which is entire, so the sum converges for every `$\varepsilon$`. The kernel uses it for
//! `$|\varepsilon| \le 1/10$`, where 24 terms hold binary64 accuracy.

use thermite::element::FloatElement;

/// Static polylogarithm constant tables for a float format.
pub trait PolylogConsts: FloatElement {
    /// `$\zeta(n)$` for `$n = 2, 3, \ldots$`. Entry `i` is `$\zeta(i + 2)$`. See the [module docs](self).
    const ZETA_INT: &'static [Self];
    /// The Stieltjes constants `$\gamma_0, \gamma_1, \ldots$`. Entry `i` is `$\gamma_i$`.
    const STIELTJES: &'static [Self];
}

impl PolylogConsts for f32 {
    #[rustfmt::skip]
    const ZETA_INT: &'static [f32] = &[
        1.644934,  // zeta(2)
        1.2020569,  // zeta(3)
        1.0823232,  // zeta(4)
        1.0369277,  // zeta(5)
        1.017343,  // zeta(6)
        1.0083493,  // zeta(7)
        1.0040773,  // zeta(8)
        1.0020084,  // zeta(9)
        1.0009946,  // zeta(10)
        1.0004942,  // zeta(11)
        1.000246,  // zeta(12)
        1.0001227,  // zeta(13)
        1.0000613,  // zeta(14)
        1.0000306,  // zeta(15)
        1.0000153,  // zeta(16)
        1.0000076,  // zeta(17)
        1.0000038,  // zeta(18)
        1.0000019,  // zeta(19)
        1.000001,  // zeta(20)
        1.0000005,  // zeta(21)
        1.0000002,  // zeta(22)
        1.0000001,  // zeta(23)
        1.0000001,  // zeta(24)
    ];

    #[rustfmt::skip]
    const STIELTJES: &'static [f32] = &[
        0.5772157,  // gamma_0
        -0.07281584,  // gamma_1
        -0.009690363,  // gamma_2
        0.0020538345,  // gamma_3
        0.00232537,  // gamma_4
        0.0007933238,  // gamma_5
        -0.00023876934,  // gamma_6
        -0.0005272896,  // gamma_7
        -0.00035212334,  // gamma_8
        -3.4394776e-05,  // gamma_9
        0.00020533282,  // gamma_10
        0.00027018445,  // gamma_11
        0.00016727291,  // gamma_12
        -2.7463806e-05,  // gamma_13
        -0.00020920926,  // gamma_14
        -0.00028346866,  // gamma_15
        -0.00019969686,  // gamma_16
        2.6277037e-05,  // gamma_17
        0.0003073684,  // gamma_18
        0.00050360546,  // gamma_19
        0.00046634357,  // gamma_20
        0.00010443777,  // gamma_21
        -0.0005415996,  // gamma_22
        -0.0012439621,  // gamma_23
    ];
}

impl PolylogConsts for f64 {
    #[rustfmt::skip]
    const ZETA_INT: &'static [f64] = &[
        1.6449340668482264,  // zeta(2)
        1.2020569031595942,  // zeta(3)
        1.0823232337111381,  // zeta(4)
        1.03692775514337,  // zeta(5)
        1.0173430619844492,  // zeta(6)
        1.008349277381923,  // zeta(7)
        1.0040773561979444,  // zeta(8)
        1.0020083928260821,  // zeta(9)
        1.000994575127818,  // zeta(10)
        1.0004941886041194,  // zeta(11)
        1.000246086553308,  // zeta(12)
        1.0001227133475785,  // zeta(13)
        1.0000612481350588,  // zeta(14)
        1.000030588236307,  // zeta(15)
        1.0000152822594086,  // zeta(16)
        1.0000076371976379,  // zeta(17)
        1.000003817293265,  // zeta(18)
        1.0000019082127165,  // zeta(19)
        1.0000009539620338,  // zeta(20)
        1.0000004769329869,  // zeta(21)
        1.0000002384505027,  // zeta(22)
        1.000000119219926,  // zeta(23)
        1.000000059608189,  // zeta(24)
        1.0000000298035034,  // zeta(25)
        1.0000000149015549,  // zeta(26)
        1.0000000074507118,  // zeta(27)
        1.000000003725334,  // zeta(28)
        1.0000000018626598,  // zeta(29)
        1.0000000009313275,  // zeta(30)
        1.0000000004656628,  // zeta(31)
        1.000000000232831,  // zeta(32)
        1.0000000001164155,  // zeta(33)
        1.0000000000582077,  // zeta(34)
        1.0000000000291038,  // zeta(35)
        1.000000000014552,  // zeta(36)
        1.000000000007276,  // zeta(37)
        1.000000000003638,  // zeta(38)
        1.000000000001819,  // zeta(39)
        1.0000000000009095,  // zeta(40)
        1.0000000000004547,  // zeta(41)
        1.0000000000002274,  // zeta(42)
        1.0000000000001137,  // zeta(43)
        1.0000000000000568,  // zeta(44)
        1.0000000000000284,  // zeta(45)
        1.0000000000000142,  // zeta(46)
        1.000000000000007,  // zeta(47)
        1.0000000000000036,  // zeta(48)
        1.0000000000000018,  // zeta(49)
        1.0000000000000009,  // zeta(50)
        1.0000000000000004,  // zeta(51)
        1.0000000000000002,  // zeta(52)
        1.0000000000000002,  // zeta(53)
    ];

    #[rustfmt::skip]
    const STIELTJES: &'static [f64] = &[
        0.5772156649015329,  // gamma_0
        -0.07281584548367673,  // gamma_1
        -0.00969036319287232,  // gamma_2
        0.002053834420303346,  // gamma_3
        0.0023253700654673,  // gamma_4
        0.0007933238173010627,  // gamma_5
        -0.0002387693454301996,  // gamma_6
        -0.000527289567057751,  // gamma_7
        -0.0003521233538030395,  // gamma_8
        -3.439477441808805e-05,  // gamma_9
        0.0002053328149090648,  // gamma_10
        0.0002701844395439035,  // gamma_11
        0.0001672729121051402,  // gamma_12
        -2.7463806603760158e-05,  // gamma_13
        -0.00020920926205929996,  // gamma_14
        -0.0002834686553202414,  // gamma_15
        -0.00019969685830896976,  // gamma_16
        2.6277037109918338e-05,  // gamma_17
        0.0003073684081492528,  // gamma_18
        0.0005036054530473557,  // gamma_19
        0.00046634356151155945,  // gamma_20
        0.00010443776975600011,  // gamma_21
        -0.0005415995822039977,  // gamma_22
        -0.0012439620904082457,  // gamma_23
    ];
}
