#!/usr/bin/env python3
"""Generates `weideman.rs` - Weideman's coefficients for the Faddeeva function w(z).

    pip install mpmath && python weideman.py > weideman.rs

A direct transcription of Weideman's `cef` MATLAB routine (1995), the reference
implementation accompanying "Computation of the complex error function", SIAM J. Numer.
Anal. 31(5), 1497-1518, 1994:

    M = 2*N;  M2 = 2*M;  k = [-M+1:1:M-1]';
    L = sqrt(N/sqrt(2));                       % Optimal choice of L.
    theta = k*pi/M; t = L*tan(theta/2);        % Define variables theta and t.
    f = exp(-t.^2).*(L^2+t.^2); f = [0; f];    % Function to be transformed.
    a = real(fft(fftshift(f)))/M2;             % Coefficients of transform.
    a = flipud(a(2:N+1));                      % Reorder coefficients.

The transform is only 4N points at N <= 40, so a naive O(n^2) DFT is fine and no FFT
is needed - but it MUST be evaluated in extended precision, hence mpmath. Doing it in
f64 costs a factor of 10 in the final accuracy of w(z) at N = 40 (8.9e-15 rather than
8.7e-16, measured): the leading coefficients are down at 1e-15, so f64 rounding in the
samples destroys them completely, and no amount of careful summation (Kahan, fsum)
recovers it because the error is in the inputs rather than the accumulation. At 60
digits the result agrees with numpy's FFT to the last bit at every N.

The `flipud` is what leaves the coefficients in MATLAB `polyval` order, i.e.
LEADING-TERM-FIRST. That is the order `tables.rs` stores and the order `poly_rev`
expects. Do not "fix" it to constant-term-first: the reversed array is a different
polynomial that happens to agree at Z = 1, which is exactly how one of these got
shipped wrong in this workspace before.
"""

import struct

import mpmath as mp

mp.mp.dps = 60

NS = (8, 16, 24, 32, 40)


def coefficients(n):
    """Returns `(L, a)` with `a` leading-term-first, per cef.m."""
    m = 2 * n
    m2 = 2 * m
    ell = mp.sqrt(mp.mpf(n) / mp.sqrt(2))

    # f = [0; exp(-t^2) * (L^2 + t^2)] over the tangent grid, length M2 = 4N
    f = [mp.mpf(0)]
    for k in range(-m + 1, m):
        t = ell * mp.tan((mp.mpf(k) * mp.pi / m) / 2)
        f.append(mp.exp(-(t**2)) * (ell**2 + t**2))
    assert len(f) == m2

    # fftshift, then a forward DFT. Only the real part of entries 1..N is kept, and
    # the input is real, so the sine half of each twiddle never contributes.
    shifted = f[m2 // 2 :] + f[: m2 // 2]

    a = [
        mp.fsum(x * mp.cos(-2 * mp.pi * i * j / m2) for i, x in enumerate(shifted)) / m2
        for j in range(1, n + 1)
    ]

    a.reverse()  # flipud: ascending -> leading-term-first
    return ell, a


def as_f32(v):
    return struct.unpack("f", struct.pack("f", float(v)))[0]


def fmt(v, f32):
    """Shortest decimal that round-trips through the target format."""
    target = as_f32(v) if f32 else float(v)
    round_trip = as_f32 if f32 else float

    for p in range(1, 18):
        s = "%.*g" % (p, target)
        if round_trip(s) == target:
            break

    # Rust needs a decimal point or an exponent to infer a float literal
    if "." not in s and "e" not in s:
        s += ".0"

    return s


HEADER = r'''//! Weideman's rational approximation to the Faddeeva function, and its coefficients.
//!
//! **Generated by `weideman.py`, in this directory. Do not edit by hand.**
//!
//! Weideman, _Computation of the complex error function_, SIAM J. Numer. Anal. **31**(5),
//! 1497-1518 (1994). With `$L = 2^{-1/4}\sqrt{N}$` and `$\operatorname{Im} z \ge 0$`:
//!
//! ```math
//! Z = \frac{L + iz}{L - iz}, \qquad
//! w(z) \approx \frac{1}{\sqrt{\pi}\,(L - iz)} + \frac{2\,P(Z)}{(L - iz)^2}
//! ```
//!
//! where `$P$` has degree `$N-1$` and **real** coefficients, and `$|Z| \le 1$` over the
//! whole closed upper half-plane.
//!
//! # Why this lives here
//!
//! Two crates evaluate this, at different arguments, and only the tables are shared:
//!
//! * `thermite-complex` uses it as written, over the whole plane, for `faddeeva_w` and
//!   the complex `erfcx`/`erf`/`erfc` family built on it. That is where the complex
//!   narrative lives (the reflection, the near-real-axis strip that `REAL_AXIS_Y` and
//!   `REAL_AXIS_X` bound, and the `HUGE` overflow guard).
//! * This crate uses it on the **imaginary axis**, where it degenerates to real
//!   arithmetic. See [`erfcx`](crate::SpecialMath::erfcx).
//!
//! `thermite-complex` depends on this crate for its special functions and not the other
//! way round, so the tables sit on this side of that edge.
//!
//! # Accuracy
//!
//! Measured against a 50-digit oracle over a grid covering `$|z|$` from `1e-8` to `1e5`
//! and `$\operatorname{Im} z$` from `0` to `30`:
//!
//! | N | 8 | 16 | 24 | 32 | 40 |
//! |---|---|----|----|----|----|
//! | max relative error | 3.1e-4 | 4.3e-7 | 4.2e-10 | 3.1e-13 | 8.7e-16 |
//!
//! Convergence is geometric, about `$10^{-0.385 N}$`. `N = 40` reaches the binary64
//! roundoff floor and `N = 48` measures no better, so 40 ends the ladder and
//! [`weideman_n`] never exceeds it. f32 floors at `N = 16` for the same reason.
//!
//! The error is **normwise**, relative to `$|w|$`, and uniform over the upper
//! half-plane. On the imaginary axis, where `$w$` is real and no cancellation between
//! components can occur, it lands in full as relative error on the value: `erfcx` at
//! `N = 40` measures 1.22 ulp worst over `$x \in [0, 10^{15}]$`.
#![allow(clippy::excessive_precision)]

/// Weideman's coefficients for an `N`-term approximation.
///
/// `A` is stored **leading-term-first**, matching both MATLAB's `polyval` order (which
/// is what the reference `cef.m` produces after its `flipud`) and
/// [`poly_rev`](thermite::math::specialized::SpecializedCoreMath::poly_rev). Feeding it
/// to a constant-term-first evaluator silently produces a different polynomial that
/// happens to agree at `Z = 1`. That exact confusion has already caused one shipped bug
/// in this workspace's Lanczos denominator.
///
/// The values come from the recipe in `cef.m`: sample `$e^{-t^2}(L^2 + t^2)$` on the
/// tangent grid `$t = L\tan(\theta/2)$` at `$4N$` points, take the real FFT, keep and
/// reverse entries `$1..N$`. They are tabulated rather than computed because the FFT is
/// not available at const-eval time.
///
/// The f32 tables are the same values rounded, not a separate fit.
/// `Weideman<24|32|40> for f32` exist only to satisfy the [`WeidemanTables`] supertrait
/// bound, since f32 clamps at `MAX_N = 16` and never instantiates them.
pub trait Weideman<const N: usize>: Sized {
    /// The scaling parameter `$L = 2^{-1/4}\sqrt{N}$`.
    const L: Self;

    /// Polynomial coefficients, leading-term-first.
    const A: [Self; N];
}

/// The tiers of [`Weideman`] an element type provides, and where its ladder stops.
///
/// The last three are read only by `thermite-complex`. They are ordinary scalar
/// constants of the element format, so they ride along here rather than justifying a
/// second trait on the other side of the crate edge.
pub trait WeidemanTables: Weideman<8> + Weideman<16> + Weideman<24> + Weideman<32> + Weideman<40> {
    /// The largest `N` worth using: past it the element's own roundoff dominates and
    /// more terms measure no better.
    const MAX_N: usize;

    /// `$|z|$` past which `$(L + y)^2 + x^2$` would overflow the element even though
    /// `$w(z)$` itself is perfectly representable. Roughly `$\sqrt{\text{MAX}}$`.
    const HUGE: Self;

    /// `$\operatorname{Im} z$` below which the near-real-axis path takes over the real
    /// part. The correction is gated at `Best` and above.
    const REAL_AXIS_Y: Self;

    /// `$|\operatorname{Re} z|$` above which it does not, the correction's own error
    /// growing like `$x^2$` until the direct evaluation is the better of the two.
    const REAL_AXIS_X: Self;
}

/// The term count for a precision tier, clamped to what `max_n` can deliver.
///
/// Each tier is the smallest `N` whose measured error (see the [module docs](self))
/// clears the next format-relevant threshold.
pub const fn weideman_n(precision: thermite::math::policy::PrecisionPolicy, max_n: usize) -> usize {
    use thermite::math::policy::PrecisionPolicy;

    let n = if precision.le(PrecisionPolicy::Worst) {
        8 // 3.1e-4
    } else if precision.le(PrecisionPolicy::Medium) {
        16 // 4.3e-7, the f32 floor
    } else if precision.le(PrecisionPolicy::Average) {
        24 // 4.2e-10
    } else if precision.le(PrecisionPolicy::Best) {
        32 // 3.1e-13
    } else {
        40 // 8.7e-16, the f64 floor
    };

    if n > max_n { max_n } else { n }
}
'''

FOOTER = """
impl WeidemanTables for f64 {
    const MAX_N: usize = 40;
    // sqrt(f64::MAX) is ~1.34e154, so back off for the (L + y)^2 headroom.
    const HUGE: Self = 1.0e150;
    // Measured crossover: inside this box the correction is never worse than the direct
    // evaluation and up to 4 orders better. Outside it, the direct one wins.
    const REAL_AXIS_Y: Self = 1.0e-5;
    const REAL_AXIS_X: Self = 1.0e3;
}

impl WeidemanTables for f32 {
    // f32 Horner roundoff floors at ~5e-7 (N = 16), and more terms measure no better.
    const MAX_N: usize = 16;
    // sqrt(f32::MAX) is ~1.84e19.
    const HUGE: Self = 1.0e17;
    const REAL_AXIS_Y: Self = 1.0e-3;
    const REAL_AXIS_X: Self = 1.0e2;
}
"""


def main():
    out = [HEADER]

    tables = {n: coefficients(n) for n in NS}

    for ty in ("f64", "f32"):
        f32 = ty == "f32"
        for n in NS:
            ell, a = tables[n]
            out.append(f"impl Weideman<{n}> for {ty} {{")
            out.append(f"    const L: Self = {fmt(ell, f32)};")
            out.append(f"    const A: [Self; {n}] = [")
            out.extend(f"        {fmt(v, f32)}," for v in a)
            out.append("    ];")
            out.append("}")
            out.append("")

    out.append(FOOTER.strip())
    print("\n".join(out))


if __name__ == "__main__":
    main()
